### ISSUE TITLE
"Browser Tabs"-style SSB with only one tab behaves like "App Window" SSB

### ISSUE THREAD

**Issue by cbeams** [dmarmor/epichrome#10]
This is with v2.1.0.

Repro:

1. Create a new SSB
2. Choose "Browser Tabs"
3. Enter a single tab, e.g. https://github.com
4. Finish the creation process and Launch the new SSB

Notice that the address bar is not present in the new SSB, and there is no way to make it appear. The SSB behaves as if the user had chosen "App Window" instead of "Browser Tabs".

While it might seem to make sense to default to "App Window" for an SSB with a single browser tab, in practice it is not what I want, because I for some applications, I want to be able to see and manipulate the URL. When Chrome is in "app mode", this is (unfortunately) impossible.

**Comment by dmarmor** [comment]
Just reproduced this on my system and I know why it's happening. Simple problem--I'll have it fixed in the next dot release. Thanks for the report!

**Comment by cbeams** [comment]
Great, thanks :)

**Comment by dmarmor** [comment]
Closing this. The fix is in 2.1.1. Reopen if any more problems...
