### ISSUE TITLE
Remove apps created by Epichrome from Open With list

### ISSUE THREAD

**Issue by chamini2** [dmarmor/epichrome#100]
Google Chrome can handle some file types that normally users don't want to open with their Epichrome app. I read [here](http://mac-how-to.wonderhowto.com/how-to/remove-duplicates-customize-open-with-menu-mac-os-x-0157100/) that changing the `CFBundleTypeExtensions` in `Info.plist` is eough to remove them.

**Comment by dmarmor** [comment]
Thanks for the idea! I'll add it to the to-do list to set up as an option. I don't think it makes sense to unilaterally remove them given that some users might want the option for their Open With menus...
