### ISSUE TITLE
Chrome://flags to enable "Add to Applications..."

### ISSUE THREAD

**Issue by bramvandenbulcke** [dmarmor/epichrome#101]
I'm a daily user of Epichrome. I really like the program. 

Today I saw a tip on Twitter to open a URL in a separate chromeless window on Mac, just like on Windows. 

I had to enable the following flags (chrome://flags): "The new bookmark app system" and "Allow hosted apps to be opened in windows". After a reboot there's a new menu under Hamburger menu > More Tools > "Add to Applications..." When adding, there is an option to open a URL as a window. 

I think this is new, because I've been looking a long time to have a feature like this.

**Comment by ripienaar** [comment]
Do these apps have separate cookie jars @bramvandenbulcke? That's one of the main reasons for using epichrome

**Comment by bramvandenbulcke** [comment]
I haven't tested but I suppose not.

**Comment by dmarmor** [comment]
Thanks for the update! Yeah, there have been extensions and such that would do this. My whole purpose with Epichrome was to create separate instances with their own settings and such and be able to switch between them using the OS task switcher. Slightly different functionality from what you're describing.

**Comment by bramvandenbulcke** [comment]
The method I described ("Add to Application") creates a real site-specific browser, so (1) a chromeless window (no tabs, no URL bar), (2) possibility to CMD + tab between them (icon is created by using the favicon) and (3) separate instance when using 'force quit'. Similar to the functionality in Windows.

**Comment by dmarmor** [comment]
I just played around with this a bit, and it could be a good, simple solution for some uses. For my own purposes, it won't replace the functionality of Epichrome for a few reasons:
1. There doesn't seem to be a way to use Chrome extensions with these apps.
2. It relies on having Chrome running in the background. If you quit your main instance of Chrome, all your apps close too.
3. As @ripienaar pointed out, it seems to share all cookies with your main Chrome instance.
4. There's no way to handle link redirection if you want certain URLs to be routed back to Chrome or other apps.
That said, it looks like Google might be finally extending their Mac app capabilities. Hopefully they'll keep at it!
