### ISSUE TITLE
chromecast support

### ISSUE THREAD

**Issue by troystauffer** [dmarmor/epichrome#102]
Websites (like Slacker Radio) that use a player that detects if Chromecast is available don't seem to recognize Epichrome apps as supporting Chromecast (they display the Chromecast icon in the player in Chrome, but not other browsers).

Can this be supported in Epichrome apps?

**Comment by dmarmor** [comment]
Hey, thanks for the report. I just tried this in a couple of my apps. I don't have a Slacker account or anything to cast it to, but I did successfully cast a YouTube video from an Epichrome app to a Roku. Is it possible there's some other reason you're not seeing the Chromecast icon? I don't really use it that much, so I don't know all the ins and outs.

**Comment by troystauffer** [comment]
So I opened the epichrome app again, and it said there was an update. I'm not sure if that meant from Chrome or epichrome. Either way, Slacker showed the Chromecast icon after that update, so it's working great!

Thanks for making an amazing app!

**Comment by dmarmor** [comment]
Thank you! I'm glad to hear whatever updated seems to have fixed it...
