### ISSUE TITLE
Switching "Main window type" doesn't work

### ISSUE THREAD

**Issue by borislavpetrov** [dmarmor/epichrome#103]
Hello there, I'm a big fan of Epichrome and hope the below issue report will help you to make it even better, for me and all other users.

The Epichrome Helper Options page has the following instructions for switching "Main window type":

"You can switch the main window between app-style and tab-style (in case you need access to the address bar or toolbar). You can use the context menu (right click anywhere on the page), or hit ⌘-⇧-L.
Note that the page itself must have focus for the hot-key to work. If you have text selected in the address bar, for instance, it won't work."

These instructions are not working for me, despite double-checking to see whether another app has hijacked that shortcut key combo and being extra careful with where the focus was when I was pressing the shortcut keys. For certain, I did not see anything in the context menu about changing between app-style and tab-style. If you think this is due to a Chrome update that took place after the last time you updated these instructions, please either update them again. Otherwise, please look into why this is not working as expected.

**Comment by dmarmor** [comment]
Hi @borislavpetrov,

Sorry for the slow reply. Are you still having this problem? I'm assuming you're running the latest version of Epichrome (2.1.16) and the latest version of Chrome? I'm not seeing the problem in any of my Epichrome apps.

Thanks!

**Comment by borislavpetrov** [comment]
I honestly haven't tried reproducing this since I originally posted, and I've been getting good mileage out of Epichrome, so I'm fine closing this out (especially if you can't repro yourself).
