### ISSUE TITLE
Closing with ⓧ leaves you with a blank tab

### ISSUE THREAD

**Issue by Akahadaka** [dmarmor/epichrome#104]
<⌘-q> quits the app as expected, but clicking the ⓧ closes only the active tab, leaving the app open although now minimized. Maximizing returns to a blank tab with no way to access the original app content. This is the same result as using <⌘-w>.

Having ⓧ hide the app without closing the active tab would also be acceptable (in some cases, preferred even)

**Comment by mickaelperrin** [comment]
Can confirm the issue, would be great to have a workaround.

**Comment by opswhisperer** [comment]
+1 this is really annoying

**Comment by acjackman** [comment]
+1 new windows created for an app in "app-style" are regular chrome "tab-style" windows instead of new "app-style" windows

**Comment by breeden** [comment]
I believe this is along the same lines as issue #29. @opswhisperer, I don't understand why this is annoying -- why not just ⌘Q if you intend to quit?

**Comment by Akahadaka** [comment]
@breeden Learning new habits is hard. Sometimes I cmd+q, sometimes I x. Learning that some things work for some apps and not others is more a Windows philosophy.

**Comment by breeden** [comment]
"Learning that some things work for some apps and not others is more a Windows philosophy." 

Lol, sick burn. :-D

**Comment by dmarmor** [comment]
Workarounds for this are on my to-do list. Thanks!
