### ISSUE TITLE
Trying to reopen the app-window after closing the window but not quitting the app fully.

### ISSUE THREAD

**Issue by graphicagenda** [dmarmor/epichrome#106]
I am only left with a tabbed-browser version of the chrome session after closing out of the app-enabled window. If I hit new window within the app after closing the main app window, I can never get it working like an app until I exit fully and then re-open.

**Comment by breeden** [comment]
This is covered in #104 and #29. When you launch your SSB, the window is initialized by an Applescript-based app. Once you close that window, the only way to get back to your SSB is to re-run that same launch process (i.e., quit then restart.)

**Comment by dmarmor** [comment]
Thank you, @breeden! Yes, this is just standard macOS behavior. I have it in my to-do list to see if the Epichrome Helper extension can have an option to either reopen the default window or quit when all windows are closed. Not sure if it'll be feasible, but I'll give it a shot.
