### ISSUE TITLE
enable-native-notifications results in no notifications

### ISSUE THREAD

**Issue by dsemaya** [dmarmor/epichrome#108]
In my experience enabling chrome://flags/#enable-native-notifications in an Epichrome app results in no notifications at all.  I'd like to use native notifications because Chrome notifications from multiple Epichrome apps appear on top of each other.

**Comment by dsemaya** [comment]
I've figured out that I had notifications disabled for Chrome in System Preferences.  I was expecting to see each app separately but apparently the setting for Chrome impacts all Epichrome apps.

**Comment by dmarmor** [comment]
Thanks @dsemaya, glad you got it solved!
