### ISSUE TITLE
Certain extensions are not accessible in "App Window"-style SSBs

### ISSUE THREAD

**Issue by cbeams** [dmarmor/epichrome#11]
Repro:

_Note: the following steps require the 1Password application to be installed. If you don't have this installed, you'll get the point just by reading the steps._

1. Create a new SSB. Choose "App Window" when prompted. Launch the SSB.
2. Hit CMD-T to bring up a window where you can navigate to https://agilebits.com/onepassword/extensions.
3. Install the 1Password Chrome extension into the SSB.
4. When installation is complete—and while still in the second window where you installed it—press CMD-\ to bring up the 1Password prompt. Notice that this works as expected: the 1Password extension menu pops up as expected.
5. Now navigate back to the original "App Window"-style window. Press CMD-\ and notice that nothing happens. There is no way to activate the extension.

Closing and restarting the SSB (i.e. to ensure that installation has taken full effect) makes no difference.

One of my primary reasons for wanting a Chrome-based SSB (i.e. not Safari-based, like Fluid) is to take advantage of extensions (like 1Password). Not being able to do this in App Window-style SSBs basically forces me back to Fluid (because having the full screen real estate is more important in the long run than having to manually enter passwords on occasion).

**Comment by dmarmor** [comment]
I've noticed this myself. I'm a heavy 1Password user. It seems to me it didn't always do this, and I'm not sure why it's happening now. It may be that something changed in an update of Chrome or 1Password, beyond my control. I'll poke around to see if I can find any fixes. Otherwise, the only answer may be in the other issue you just opened (which I'll comment on separately).

**Comment by dmarmor** [comment]
I investigated this a bit more, and I think it's a 1Password problem. I had an older version of the extension (4.3.1.90) in one of my older SSBs that I hadn't run in a while. Fired it up and it worked fine in the app window. When I updated the extension to the latest version (4.4.1.90)--voila, 1Password won't fill out forms in an app window any more.

I'll post in the AgileBits forums. Maybe if you enough of us care, they'll take it seriously?

**Comment by pattulus** [comment]
Strange. I'm a new (4 days old) Epichrome user and so far the 1Password extension worked every time for me (after an initial relaunch of the SBB in question).

The only pain I feel when it comes to passwords is that my all my BitTorrent Sync SBB's won't remember their password… which is `.htaccess` based I guess:

![login](https://cloud.githubusercontent.com/assets/591759/8750639/df329f7e-2ca8-11e5-9d0d-230a577e95cf.png)

_Fluid used to remember these. Maybe I've to do some research._

**Comment by cbeams** [comment]
Ok, sounds good. Paste a link to the AgileBits forum if you do post something there, thanks.

**Comment by pattulus** [comment]
Whoops. @cbeams you're right – I forgot that you refered to **"App window" SBB's** _(and hence deleted my old comment)_. Also: +1 for a link to the AgileBits forum.

**Comment by dmarmor** [comment]
I just posted in the AgileBits forum about this:

https://discussions.agilebits.com/discussion/44602/1password-not-filling-logins-in-chrome-popup-style-windows#latest

I didn't mention Epichrome since it seemed that would just confuse matters, and anyway the problem happens just the same in regular Chrome.

So we'll see what happens. They're usually pretty good about replying.

**Comment by dmarmor** [comment]
I'll close this issue since I don't think it's something I can address in Epichrome. Someone from AgileBits has replied to my post, so I'll post another comment here if and when anything changes with 1Password. Thanks!

**Comment by dmarmor** [comment]
I don't know if anybody's been following the thread, but it sounds like they're looking into it (it took a little doing to get them to believe it was a real problem). Hopefully they'll get it fixed in the next update.

**Comment by cbeams** [comment]
Nice!

**Comment by dmarmor** [comment]
New update on the AgileBits forum. They seem to have fixed it! It's in the current beta of the extension (4.4.3.2), which you can install from [here](https://agilebits.com/onepassword/extensions?beta=true). I've tried it with one of my apps so far and it's working great.
