### ISSUE TITLE
Background color/alpha

### ISSUE THREAD

**Issue by stimpy2318** [dmarmor/epichrome#110]
Is there a way to adjust the background color or transparency of an SSB app created using epichrome? I am trying to use it for some Window Capture sources in a live stream and unfortunately it is loading StreamLabs pages with a white background. If I can change this to green or better yet completely transparent, I could actually use it to make my stream setup much easier to maintain.

**Comment by dmarmor** [comment]
This isn't something Epichrome can do. Remember that all Epichrome does is act as a wrapper for Chrome. If I'm understanding what you want to do, I'd recommend something like [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en "Tampermonkey) (or I think you can manually install user scripts in Chrome, though I've never tried this). Hope that helps!
