### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by eheaton** [dmarmor/epichrome#111]
Is there a way to create new SSB's via. the command line? Would love to integrate this into my .dotfiles / Mac bootstrap script.

**Comment by dmarmor** [comment]
It is technically possible to do this, though I wouldn't necessarily recommend it, as it's *very* un-user-friendly and definitely undocumented.

That said, if you're technical, then look in main.applescript and you'll see where it calls build.sh (it actually calls it twice). You'll need to set up your arguments to that script very carefully, as it's really not meant to be called from anywhere else but the controlled environment of main.applescript. But if you give it just the right arguments (you'll have to have your icons pre-built I believe) it should spit out an Epichrome app.

Good luck!
