### ISSUE TITLE
Sync between multiple computers

### ISSUE THREAD

**Issue by seanyhc** [dmarmor/epichrome#112]
First of all, this is an awesome app. Thanks so much for creating it. In combination with apps like Browser Fairy, it allows me to create native apps for many of the major sites.

Because I use it on both my work and personal Macs, many times if I change a settings for one app, it's troublesome to remember to do the same on the other one.

I know sync is a big task. So perhaps an easier workaround would be showing me where it stores extensions and their data? The most frequent changes are usually installing a new extension and adding a rule, which is a content under the extension "Epichrome".

If I know where they are, at least I can use a file sync app to only look into those folders, rather than the entire Epichrome/Gmail folder. Or please advise if there's a better way.

Many Thanks,
Sean

**Comment by alvint** [comment]
This sounds like a great idea for a paid feature (since you'll need server time). I for one would be willing to pay thousands of dollars for this. Maybe not quite that much.

**Comment by henderea** [comment]
If you're talking about the type of syncing you can get with a google account, that data will probably be in `/Users/yourusername/Library/Application Support/Epichrome/Apps/appname/Default`.  Of course, that assumes you haven't done any configuration with profiles.  If you have multiple profiles in your epichrome app, you'll probably also have folders like `Profile 1` or whatever in the same folder that `Default` is in.  However, if you haven't done that sort of advanced config, you probably just have settings in the `Default` folder.

**Comment by dmarmor** [comment]
Hi @seanyhc -- @henderea is exactly right. You should be able to use Dropbox or any good sync software to sync between the Default (or Profile) folders on each computer. Note: do not try to use Dropbox or any other "live" sync if you are ever running your Epichrome app at the same time on multiple systems. In that case, you definitely need to use something like ChronoSync where you can decide when to run it and resolve any conflicts.
