### ISSUE TITLE
Expose the setup URLs so that they can be edited.

### ISSUE THREAD

**Issue by gnyrd** [dmarmor/epichrome#117]
Sometime things change.. reasons for using a site specific browser, the desired entry point into a web, or maybe just because...

It would be excellent to have access in the extension settings to those config'd URLS.

**Comment by dmarmor** [comment]
Hi @gnyrd -- this is on my feature wish-list too, but will likely have to wait until I have time to build the version of Epichrome that runs as a Chrome extension. Unfortunately my day job is still more than full-time, so I'm not sure when I'll get to this, but I really would like this feature myself, so it will eventually happen!
