### ISSUE TITLE
Regular Chrome icons turning into Epichrome app icons

### ISSUE THREAD

**Issue by wizonesolutions** [dmarmor/epichrome#119]
My Google Chrome icon has turned into one of my Epichrome app icons. It still works properly otherwise. The Cmd-Tab name is "ChromeEngine".

This happened after applying the script in https://github.com/dmarmor/epichrome/issues/114 — though not immediately. I think it happened after i put my computer to sleep for a longer time, and it went into hibernation.

It seemed to use the most recently-opened app icon, but it might be random too. It persisted even after a computer restart.

It's probably related to how the system can't see Chrome as a browser anymore — it thinks that ChromeEngine and one of the Epichrome apps _is_ Chrome (and it behaves that way too).

So this is basically a visual issue, but kind of weird and disorienting.

**Comment by dmarmor** [comment]
Hey @wizonesolutions, I think this is related to the same problem in #116, which I believe I've solved in 2.1.17. Once I've got the release up, you'll need to update all your Epichrome apps and then shouldn't have this problem any more.
