### ISSUE TITLE
After updating to 2.1.17, apps open in low resolution

### ISSUE THREAD

**Issue by linusbobcat** [dmarmor/epichrome#120]
I opened an Epichrome app in which it asked me to go to Github to download a new runtime and then update the app, which I did. For the sake of making things easier to explain, I'll call it "Trello.app".

After I updated Trello.app, it opens in a blurry lower resolution mode. I right clicked in Finder and checked to see if "Low Resolution Mode" was ticked, which it was not. I tried to run it trough Retinizer, however, it reported that it was already retina compatible.

One odd thing I found is that upon looking trough the contents of Trello.app, "ChromeEngine.app" was renamed into "zzzzChromeEngine.app" Upon renaming it back to "ChromeRuntime.app" and reopening that again, Epichrome complaints that "Chrome was moved, attempting to relink" (That is paraphrased) and renames it back to "zzzzChromeEngine.app." After checking the Resources folder again, there is now "ChromeEngine.app" and "zzzzChromeEngine.app." Opening either one also shows Chrome in low resolution, however clicking the hamburger menu shows the dropdown in full retina resolution.

I have a 2016 Macbook Pro with a Touchbar and Intel graphics. I run things as a *non*-admin accounts for security reasons, although I have full control over the admin account. 

See the screenshots below. You should zoom in to see the effects.

If you need any logs, please tell me how to get them.

<img width="1440" alt="2017-07-15-09 32 pm 46" src="https://user-images.githubusercontent.com/3782109/28244711-cce988ae-69a6-11e7-990a-0436d184b06f.png">
<img width="1440" alt="2017-07-15-09 40 pm 03" src="https://user-images.githubusercontent.com/3782109/28244710-cce9506e-69a6-11e7-8a72-e72d1134b98e.png">

Edit: I'm on macOS 10.12.5

**Comment by daviddumonde** [comment]
Same here. **Left** is an epichrome app that has **not** been updated. **Right** is an epichrome app on **2.1.17**. Running MacOS 10.12.6 Beta. Almost looks like it's not using the retina display. 

<img width="1280" alt="screen shot 2017-07-16 at 9 20 27 am" src="https://user-images.githubusercontent.com/1297037/28248301-46c2db60-6a08-11e7-88b1-0ba3215a427f.png">

**Comment by InvaderJ** [comment]
Same here, just updated to latest Epichrome, made a new SSB, and same blurriness as above. MacBook 12", 10.12.2.

**Comment by dmarmor** [comment]
Thanks, @linusbobcat, @daviddumonde & @InvaderJ! I'd only tested 2.1.17 on my external display so hadn't yet noticed the low-res. In 2.1.17 I changed the Chrome Engine a bit and apparently that caused it to need an extra Info.plist key. Not sure why. New release 2.1.18 is up, and should fix the problem. Let me know if you still have trouble.

And @linusbobcat: zzzzChromeEngine is the correct name for the internal Chrome Engine app now. I had to change it to avoid macOS getting confused between the potentially many Chrome Engines on a system and the real Google Chrome--apparently it works alphabetically. So in that Trello.app you can delete your renamed ChromeEngine.app folder--it's not used any more.

**Comment by breeden** [comment]
You so smart!
