### ISSUE TITLE
After update, links not loading...

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#121]
Been having an odd and disrupting issue.  After the update I've found that clicking links that normally loaded up in Epichrome instances now start the Epichrome instance and spawn a new window, but they do not load the actual URL...  Any ideas here?

**Comment by dmarmor** [comment]
Can you give me some more specifics? Are you using Browser Fairy? I just tried a couple different links, both a .webloc file loaded from the Finder, and a link clicked from another Epichrome app, and they both loaded properly in the intended app, whether it was already running or not. Maybe you can help me recreate the problem you're having?

**Comment by dmarmor** [comment]
Hey @ylluminate -- not at all sure if this will actually help or not, but I just tried rolling back one change I made to the Chrome engine. If you have a chance, would you try this and see if it helps? *(Back up your apps and Epichrome 2.1.18 first so you can roll back if you need to.)

https://www.dropbox.com/s/srvu6zz0o9mm2st/Epichrome.app.zip?dl=1

**Comment by ylluminate** [comment]
So yes, using Browser Fairy... When I am clicking on links in Unibox, for example, that should open up in a Google Drive Epichrome app, it pops up the main window (which I have a no-tab primary window for this app) and then it loads its homepage and never opens up a new tabbed window or the usual behavior of loading up in an existing window (last used) as a new tab...

I'll give that a shot here.

**Comment by ylluminate** [comment]
Yes, this build you posted with the rollback works perfectly again with opening links as such...

**Comment by dmarmor** [comment]
OK, great. I'm waiting on one other user who reported a different issue to see if the rollback helps them too (or at least doesn't make things worse) and then I'll post a new release with the fix. Chances are I won't change anything else in that release (including version number) so you can just keep the version you have now, no need to d/l the new one.
