### ISSUE TITLE
Regression: Cmd-Shift-L is not working to show address bar

### ISSUE THREAD

**Issue by wizonesolutions** [dmarmor/epichrome#124]
Before, `Cmd-Shift-L` would let me see the address bar/extensions/etc. I wanted to tweak some Epichrome Helper settings, since suddenly non-app links aren't opening in my default browser anymore after upgrading.

Expected: Pressing `Cmd-Shift-L` switches app to full-browser mode and back.
Actual: Nothing happens.

I checked that my keyboard layout is correct. I don't _think_ I'm mis-remembering the shortcut, and I didn't see any release notes about it changing lately. The last change was when `Cmd-L` was removed as an alternative.

**Comment by dmarmor** [comment]
The shortcut still seems to be working for me. Have you confirmed that the Epichrome Helper extension is still enabled in your app? The latest update to Chrome has taken a very conservative approach to auto-installed extensions and it now starts them off disabled with no notification. (I'm working on having new Epichrome apps pop up a first-run page to warn users to turn on the extension. Not an ideal solution, but at least it'll hopefully help somewhat.)

Let me know if that solves the problem for you. If shortcut is still not working even with the extension re-enabled, we can diagnose further. Thanks!

**Comment by wizonesolutions** [comment]
It was that! Thanks

24. jul. 2017 17:55 je oseba "dmarmor" <notifications@github.com> napisala:

**Comment by dmarmor** [comment]
Excellent! Glad that worked.
