### ISSUE TITLE
Epichrome.app is not codesigned

### ISSUE THREAD

**Issue by henderea** [dmarmor/epichrome#127]
Recently, my company added restrictions that prevent installation of unsigned apps.  I have my own codesigning signature, so I've codesigned it for my own use, but that doesn't help other users.  I have created a version of the latest build dmg that has the app and dmg codesigned with my identity.  You can find it at https://epgsoftware.s3.amazonaws.com/epichrome-2.1.20-signed.dmg, but feel free to add the file to the github releases page.

If you'd be interested in having me codesign Epichrome.app for you for each release, I'd be happy to do so, but I won't guarantee immediate turnaround.  You could always release it and then add the codesigned version afterwards.  You can find my email address on my github profile page.

Since I use epichrome myself and need a codesigned version, I'll be codesigning it for my own use anyway, so it isn't much extra effort to share that with other users.

**Comment by bknowles** [comment]
I can't seem to run this app at all without having it be codesigned.  Clicking the "open anyway" button for EpiChrome doesn't do anything.

**Comment by henderea** [comment]
Feel free to use the version I codesigned.  If the official release isn't getting codesigned, I can keep creating a codesigned version of it with each release since I need that myself anyway.  It isn't hard for me to do, and only takes me a few minutes.

**Comment by dmarmor** [comment]
Hi @henderea! Thank you for reporting this and for the offer. I had to do some heavy work on Epichrome to get it working again with Chrome 69, and took the opportunity to finally get my act together and join the Apple Developer Program, so going forward Epichrome will be codesigned and shouldn't cause problems with GateKeeper. Hoping to get the new release out tonight.
