### ISSUE TITLE
SSB fails to use vector image as custom icon.

### ISSUE THREAD

**Issue by charlescbeebe** [dmarmor/epichrome#129]
Epichrome version: 2.1.20
Chrome version: 60.0.3112.113 (64-bit)
Icon: https://www.seeklogo.net/wp-content/uploads/2017/03/Google-Calendar-icon.png

Perhaps a clue to the issue is that Epichrome never renders a preview of the logo when selecting it via a system dialog:

<img width="824" alt="screen shot 2017-09-01 at 11 29 02" src="https://user-images.githubusercontent.com/904205/29978098-cbdb1c02-8f0d-11e7-919a-d29e53b4297b.png">

The final product is just a generic placeholder logo:

![screen shot 2017-09-01 at 11 33 27](https://user-images.githubusercontent.com/904205/29978122-dc5b7612-8f0d-11e7-8ff0-22c5c3e7e68c.png)
 
<img width="752" alt="screen shot 2017-09-01 at 11 30 26" src="https://user-images.githubusercontent.com/904205/29978115-d87e0a1e-8f0d-11e7-936d-f2d956374d5f.png">

As you can see in that final screenshot, my "Gmail" and "Google Hangouts" SSB's use custom icons just fine; unfortunately, I don't have a link to the originals that I used for those, so I can't tell if they were vector images or not.

**Comment by dmarmor** [comment]
Could you upload or send a link to one (or more) non-working vector images? I'll take a look. No guarantees here--I'm relying on built-in Apple tools to do the icon processing, so I might not be able to easily convert all formats. But if I have some samples I can give it a shot. Thanks!

**Comment by dmarmor** [comment]
Closing this issue for now. If you still want me to take a look at vector images, please send a sample and I'll reopen and take a look.
