### ISSUE TITLE
Created SSBs stuck as browser-style with no default tabs

### ISSUE THREAD

**Issue by sashaweiss** [dmarmor/epichrome#13]
Hi,

I've downloaded the new release, and I've noticed that a problem I had before has persisted: no matter what option I select in creation (app- or browser-style) and what default tab(s) I give, the created SSB is coming out as a browser-style SSB with no default tabs, simply asking me to sign into Chrome.

I deleted all previous SSBs I had made with earlier versions of this tool, and even delved into ~/Library/Application Support to clear out everything left by earlier versions of the tool.  However, I'm still experiencing this problem with any new SSBs I try to create.

Thanks so much,
Sasha

**Comment by dmarmor** [comment]
Hmm. I have no idea what's going on then. Could you do me a favor? Run Epichrome, create an app that should be app-style, and send me a screen capture of the "Step 7 of 7" dialog? The one that looks like this:
![screen shot 2015-07-16 at 9 17 57 am](https://cloud.githubusercontent.com/assets/3878113/8728730/b4a4f7ce-2b9b-11e5-87d3-da743508e21e.png)
Then after the app has been created, and you've confirmed that it's a browser-tab style app and not the app-style it's supposed to be, I need to see one of the files inside the app bundle. Here's how to find it:

  1. Find the app on your system. Right click and choose "Show Package Contents"
  2. Navigate to Contents/Resources/Scripts
  3. Send me config.sh.

Thanks!
  Dave

**Comment by sashaweiss** [comment]
Of course.

Screenshot of the window:
<img width="1089" alt="screen shot 2015-07-16 at 13 44 53" src="https://cloud.githubusercontent.com/assets/9013117/8732173/70bfb6d6-2bc1-11e5-8974-e9dbdfeaa45e.png">

I can't attach the .sh here, but I've copy-pasted the contents below:

# config.sh -- autogenerated Thu Jul 16 13:45:27 CDT 2015

CFBundleDisplayName=xkcdTEST
CFBundleName=xkcdTEST
CFBundleIdentifier=org.epichrome.app.xkcdTEST
SSBVersion=2.1.0
SSBProfilePath=Library/Application\ Support/Epichrome/Apps/xkcdTEST
SSBChromePath=/Applications/Google\ Chrome.app
SSBChromeVersion=43.0.2357.134
SSBRegisterBrowser=No
SSBCustomIcon=No
SSBFirstRunSinceVersion=''
SSBHostInstallError=''
SSBCommandLine=( --app=www.xkcd.com )

Best,
Sasha

**Comment by dmarmor** [comment]
OK, I think I see the problem. You have to include the scheme at the beginning of your URL (http:// or https:// or whatever). I usually find the best bet is to open the site I want in Chrome, then just select the whole text in the address bar and copy-paste it. That way I know I didn't make any typos.

Sorry for the confusion--the AppleScript front end is pretty dumb, so I don't do a lot of data checks. I'll be rewriting it at some point.

Anyway, give that a try and let me know if it solves your problem.

Cheers!
  Dave

**Comment by sashaweiss** [comment]
That did it! Thanks so much!

**Comment by dmarmor** [comment]
Great! Glad it's working.
