### ISSUE TITLE
Epichrome Helper not visible/present

### ISSUE THREAD

**Issue by Pofadda** [dmarmor/epichrome#131]
Just installed Epichrome on my 10.12 iMac.  Came to the end of the initial install and saw that the Helper extension needed to be enabled. I have looked in More Tools > Extensions including 'more extensions' and don't see it anywhere. Following other advice, I trashed and emptied the GoogleSoftwareUpdate folder (in ~/Library/Google/( not /Library/ as per advice. No 'Google' subfolder in there...) and uninstalled/reinstalled Chrome.  Still no Helper to be seen.

What might I have missed, please?

**Comment by tdhopper** [comment]
I am having this same issue.

**Comment by dmarmor** [comment]
Hey @Pofadda & @tdhopper, has this been fixed for you in more recent releases of Epichrome?

**Comment by tdhopper** [comment]
I have tried

**Comment by dmarmor** [comment]
Closing this for now. @Pofadda & @tdhopper, if you're still having this problem with the current release of Epichrome, please let me know and I'll reopen.
