### ISSUE TITLE
My Epichrome app seems to have been renamed to Google Chrome?

### ISSUE THREAD

**Issue by alanhogan** [dmarmor/epichrome#132]
The Epichrome app I had created (called Gmail) went missing from my Dock when I restarted. (I’m using the July 22 build; been a longtime user.)

When I launched Google Chrome.app, I realized it was actually my Gmail app! 

So I renamed it to Gmail.app. (Of course, my custom icon was lost.)

But when I relaunched it, it actually just opened Google Chrome (!?) with my real Chrome profiles, extensions, etc!

Very confusing. Not sure how to go forward.

**Comment by dmarmor** [comment]
Closing this issue. I believe it's solved by version 2.2.4. Happy to reopen if you're still experiencing this.
