### ISSUE TITLE
Hide Menu Bar?

### ISSUE THREAD

**Issue by thomasthechan** [dmarmor/epichrome#134]
I'm as green as they come...loving Epichrome, but wondering if there was a way to hide the menu bar? It's obvious that it is a Chrome browser and I'm looking for a way to disable the menu bar to get the right feel.

**Comment by ssssamstrup** [comment]
When creating an app, step 3 gives you the choice of choosing the app style.

![image](https://user-images.githubusercontent.com/4302516/34073830-259fbd90-e2a3-11e7-9a5f-3c14658f908b.png)

If you choose App window you don't get the chrome menubar, but just a normal app menubar.

If you meant a way to hide the normal menubar that is shown on all apps I guess this won't be doable without risking overlapping the Exit, Minimize and Fullscreen/Expand buttons onto something on the webapp.

**Comment by dmarmor** [comment]
Thanks @ssssamstrup & @jameschao. I agree with what you both said here. Closing this issue for now, but @thomasthechan if you have more info about what you're trying to do and it's something that's possible within Epichrome, I'll take a look.
