### ISSUE TITLE
Epichrome apps should have unique bundle identifiers when running ChromeEngine

### ISSUE THREAD

**Issue by dsemaya** [dmarmor/epichrome#135]
Since the OS thinks that Epichrome apps are simply another instance of Chrome the following items don't work:

- Can't set mailto protocol helper for an Epichrome Gmail app (Chrome opens instead)
- Can't individually control notifications settings in System Preferences for Epichrome apps (Only all Chrome-based apps)
- Notifications always show Chrome icon instead of the Epichrome app's icon

If Epichrome had an option to copy all of the Chrome components into itself and change the bundle identifier per-app I think it would solve these problems.

**Comment by dmarmor** [comment]
Unfortunately there's just no way to have the Chrome engine run under anything but the Chrome bundle ID. This is now especially true under Chrome 69 (and presumably later), which is very strict about checking that nothing about itself has been altered.

**Comment by octplane** [comment]
Hello @dmarmor, I suppose this is still the case, and explains why the bundle Id of the running epichrome windows is `com.google.Chrome`, right?

**Comment by dmarmor** [comment]
That's exactly right, @octplane. I've been unable to find any workaround for this.

**Comment by dmarmor** [comment]
Hey @octplane, I wanted to (quite belatedly) let you know that the current version of Epichrome addresses this. There's now a built-in engine option, based on Brave, that allows its running engine to have a unique ID, which solves all the problems you mentioned.

**Comment by octplane** [comment]
Thanks for the feedback! Will definitely retry my use cases 🙇

**Comment by seroy** [comment]
Hello @dmarmor 
I know it's so late, but it might be helpful to someone.
We can append our ID to the end of `com.google.Chrome` to get unique bundle ID like this `com.google.Chrome.app.SOME_UNIQ_ID` 
I got that from the Youtube PWA and it work for me at least on 104.0.5112.79.
I just change `CFBundleIdentifier` value in `Info.plist` on existing Epichrome app and it works like a charm.
Finally i can set default browser correctly in system preferences 🎉

**Comment by dmarmor** [comment]
That's cool! I never figured out a way to make it work that wouldn't break Gatekeeper. Glad that's helping you!
