### ISSUE TITLE
Some SSBs created with Epichrome cannot update their Chrome version

### ISSUE THREAD

**Issue by jbyler** [dmarmor/epichrome#137]
Some of my Epichrome-created SSBs are on recent Chrome versions.  Since they have been around for a while, I believe this means they must be updating themselves successfully.

But others are on old Chrome versions, as reported in chrome://help/ .  They don't show any indication of a new version being available.  Quitting and restarting them doesn't trigger an update.

I'm having trouble finding information on how to troubleshoot this.  It appears though as if Epichrome SSBs are supposed to update their Chrome versions, but some of mine are not.  Are there any known issues or workarounds for this?

**Comment by bradsmith74** [comment]
I think I'm seeing the same issue. As of today, my normal Chrome reports that it is up to date on:
Version 67.0.3396.87 (Official Build) (64-bit)

However I have a few Epichrome SSBs that all list their version as:
Version 66.0.3359.181 (Official Build) unknown (64-bit)

It appears that came out on May 15, 2018, which is over a month ago. I'm not sure if the Epichrome version trails the official build by some period of time, or if they're just not being updated at all. I've had these SSBs for a while (many months at least), so it would seem that they must have updated at some point. But I'm not sure if they are still being updated. I'll keep an eye on them and post back here in another month or so.

**Comment by dmarmor** [comment]
Epichrome apps should always report as being the same version of Chrome that is installed on your system, as all they are is a wrapper around Chrome. So I'd suspect something else might be going on on your systems. Please let me know if this behavior persists under Epichrome 2.2.0.
