### ISSUE TITLE
Backup and restore epichrome aps?

### ISSUE THREAD

**Issue by samlimster** [dmarmor/epichrome#139]
Hi folks!

Is there a way to backup my epichrome apps?  I've created several of them and want to be able to restore them onto a fresh computer.

Thanks in advance!

Sam.

**Comment by ylluminarious** [comment]
Related discussion here: https://github.com/dmarmor/epichrome/issues/126

**Comment by dmarmor** [comment]
Hi @samlimster. If you just want to copy the apps themselves and don't mind starting fresh in terms of settings and extension, then it's as simple as making sure the apps are not running and then copying them over. It might make life simpler to zip them up first and then unzip them at the destination.

If you want to copy your settings over, that's a stickier problem, and @ylluminarious has pointed you to the right issue, #126.
