### ISSUE TITLE
Custom Icons no longer work

### ISSUE THREAD

**Issue by jdsimcoe** [dmarmor/epichrome#14]
All new SSBs display an Epichrome icon by default even when a custom `ICNS` file is selected:

![screen shot 2015-07-17 at 7 56 35 am](https://cloud.githubusercontent.com/assets/275617/8749926/640815a8-2c59-11e5-81d2-21987a35c710.png)

**Comment by pattulus** [comment]
I can confirm this… at least for a SBB I deleted and recreated. Haven't tested making a new one yet.

**Comment by jdsimcoe** [comment]
I have confirmed it with new SSBs and old ones I deleted.

**Comment by pattulus** [comment]
I just created a new SSB and used a PNG – this worked without a issue. Normally I use `.icns` files, so this might be `.icns` issue.

**Comment by jdsimcoe** [comment]
Yeah @pattulus It used to work with `ICNS` that's why I posted this. Thanks.

**Comment by dmarmor** [comment]
Hi guys, I rewrote some of the runtime engine and that broke the code for ICNS files. I've fixed it and the fix will be in the next release. Thanks for the reports!

**Comment by dmarmor** [comment]
Just posted a new release (2.1.2) that should solve this problem. Closing the issue--please reopen and let me know if you have any more problems. Thanks!
