### ISSUE TITLE
strange window behavior

### ISSUE THREAD

**Issue by thebai** [dmarmor/epichrome#140]
Hi dmarmor,

Epichrome has been an crucial part of my setup for years now, but recently I noticed a strange behavior. 

With a simple Gmail app (pretty standard configuration)
- checked: Never redirect domain-relative links that would open in the same tab
- checked:  Stop further handling for links sent to default browser (check this if links sent to default browser are erroneously also opening in this app)

I have the app triggered by an Alfred keyboard shortcut workflow so that I can open up the window quickly. This used to work without a hitch, but now every time I trigger the keyboard shortcut, the app would open up another new window, which is really annoying. 

What can I do to get the keyboard shortcut to just open up the existing window? This used to work perfectly, with the keyboard shortcut just hiding and opening the existing window.

Thanks!

Kevin

**Comment by webbower** [comment]
I'm having a similar issue. I have everything unchecked and no rules in the helper extension options (trying to debug) and whenever I Cmd + Click or Cmd + Shift + Click a link inside the SSB, it opens the link in my default browser. What's even more fun is in one of the SSBs I have set up, when I click one of the UI buttons that shows a dropdown menu (marked up with an `<a href="#">`) and no modifier keys, it opens the current page with the # appended to the URL. So it looks like the link click handling for EpiChrome has gone haywire. I didn't have this problem in previous SSBs on my work computer for a previous job. The main difference between the two computers was the old one ran macOS 10.12 and my current one runs 10.13

**Comment by webbower** [comment]
Looks like maybe a bug in the Epichrome extension. I disabled it and the buggy behavior stopped.

**Comment by demmer** [comment]
I ran into the same issue using Quicksilver shortcuts. Disabling the extension stopped the bad behavior as well.

**Comment by dmarmor** [comment]
@webbower & @demmer, this seems to me like a different problem from what @thebai described. I've been (slowly) working on a pretty major rewrite of the extension that I hope might address this problem. I'm hoping to be putting it out as a beta soon and will let you know when it's available to try.

**Comment by dpickett** [comment]
It appears that this is related/similar to #133

**Comment by dmarmor** [comment]
Hi all! Yes, @dpickett, I think this is indeed related to #133, and I'm working on a fairly major update that I believe will solve it (as well as many other long-standing problems). With my work schedule, it may take a while, but I'll let you know when it's ready for testing. Thanks for your patience! I'll close this issue for now and continue the conversation in #133.

One more thing:

#### <shameless_plug>
#### I've set up a [Patreon](https://www.patreon.com/epichrome). If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it.
#### </shameless_plug>
