### ISSUE TITLE
App icon looks gnarly in HiDPI

### ISSUE THREAD

**Issue by dzg** [dmarmor/epichrome#141]
When in HiDPI mode on a Retina display, and using Cmd-Tab to switch apps, the icon for my Epichrome app looks jagged.

![image](https://user-images.githubusercontent.com/466557/33767586-7ddd46bc-dc22-11e7-85b3-40a56a937ab0.png)

Any way to fix this?

**Comment by dmarmor** [comment]
This has to do entirely with the resolution of the image you use to create the icon. If you want icons that will look completely sharp in all contexts in HiDPI, the original image should be at least 1024x1024. I've found that for practical purposes 512x512 images end up looking fine in most contexts (i.e. the dock).
