### ISSUE TITLE
Option to disable some keyboard shortcuts

### ISSUE THREAD

**Issue by mandeepr** [dmarmor/epichrome#144]
I use Epichrome for a web app that already maps the Command+Shift+L shortcut, but whenever I use it, both the app and Epichrome's shortcut are invoked, causing epichrome to switch window type. I want to keep the context menu option for this, but disable the keyboard shortcut.

**Comment by dmarmor** [comment]
Closing this issue. I've got this on the to-do list for the next version of the extension.
