### ISSUE TITLE
Change window style to tabs after creation?

### ISSUE THREAD

**Issue by Zettt** [dmarmor/epichrome#146]
I'm having a problem with one specific SSB. I created it using the "one app in one window" style but now I'd like it to have tabs instead. For some reason, when I press ⇧⌘L and close the browser, the tabs do not show up when I launch the SSB again. It goes back to the window style it had before. Is this a bug or a failure on my end?

**Comment by dmarmor** [comment]
The window style is hardwired when you create an Epichrome app. Eventually I want it to be possible to edit an existing app to change window style, URL and everything else, but right now there's not an easy way to do this. If you don't want to recreate the app (you can find ways to do this in the Readme) then you'd  need to edit the app's config.sh script, which is in:

```
<Your-App.app>/Contents/Resources/Scripts/config.sh
```
First, make sure the app is not running. Then open that file in your text editor, and look for a line like this:

```
SSBCommandLine=( --app=https://www.example.com/ )
```

Remove the "--app=" so it looks like this:

```
SSBCommandLine=( https://www.example.com/ )
```

Save and close it, and next time you run, the app should open with a regular tab-style window.

**Comment by ylluminate** [comment]
In the new builds (Epichrome 2.3) this has moved to: `APPNAME.ap/Contents/Resources/script`
