### ISSUE TITLE
is there a way to stop EpicChrome to trigger Chrome version update?

### ISSUE THREAD

**Issue by williamku** [dmarmor/epichrome#147]
hi, @dmarmor ,  
I have the need to keep using a particular version of Chrome browser.   Is there a way to configure the Epic-Chrome not to automatically update the Chrome browser?  
Thanks!

**Comment by dmarmor** [comment]
I don't know if there's a way to turn off auto-updating in Chrome itself, but that would be the only way to do it. Epichrome apps are just a wrapper for Chrome instances, so if Chrome wants to auto-update, then running an Epichrome app will trigger that, just the same as running Chrome itself would.
