### ISSUE TITLE
1Password 7 beta and Epichrome apps

### ISSUE THREAD

**Issue by Zettt** [dmarmor/epichrome#148]
1Password 7 beta 10 does not have an option to "allow unverified browsers", like mentioned in issue #118". I'd like to ask how we can get 1Password 7 working with Epichrome browsers. Do we have to copy some files or create our own JSON?

**Comment by dmarmor** [comment]
Please let me know if this persists under Epichrome 2.2.0 (hoping to release it tonight).

**Comment by dmarmor** [comment]
Hi @Zettt, are you still having trouble with 1Password 7? I finally upgraded to 7 myself recently and it appears to be working fine with my Epichrome apps. If it's working for you too, I'll close this issue...

**Comment by dmarmor** [comment]
Hi @Zettt, just checking on this again. Has 1Password 7 been working for you? I have found that when Chrome is in the midst of an update and I have Epichrome apps open, this problem can occur. Quitting all Epichrome apps, letting Chrome finish its update, and then reopening the Epichrome apps seems to fix it for me.

**Comment by dmarmor** [comment]
Closing this issue for now. If you're still having trouble or have more info, please let me know and I'll reopen.
