### ISSUE TITLE
mailto: links?

### ISSUE THREAD

**Issue by camner** [dmarmor/epichrome#149]
I use Epichrome to create an SSB for Fastmail.com.  But _mailto:_ links don't work.  Is there a workaround?

**Comment by andresrinivasan** [comment]
I've used [Browser Fairy](http://www.browserfairy.com/) to do similar things with an Epichrome based SSB. It does sometimes take a little playing to get the Epichrome setup to not thwart the redirect.

**Comment by dmarmor** [comment]
Thanks @andresrinivasan. Yeah, Browser Fairy is the chooser I use and have found it to work pretty well. I'll close this issue for now, but @camner if you are still having trouble let us know on this thread and I'll reopen.
