### ISSUE TITLE
Localhost URL

### ISSUE THREAD

**Issue by Vicedivic** [dmarmor/epichrome#152]
I wanted to make my localhost an app, so i gave the localhost "localhost/practice" as the URL, but when i open the app it just opens up a blank Chrome tab. How do i make it react like it was a real website?

**Comment by Vicedivic** [comment]
Thanks, it worked with the http prefix

**Comment by dmarmor** [comment]
Thanks @alvint! Glad this solved the problem. Closing this issue.
