### ISSUE TITLE
Mac media keys

### ISSUE THREAD

**Issue by LETRA** [dmarmor/epichrome#154]
Hi. Is there any way to work the macOS media keys? I am using epichrome with subsonic in Mojave Beta.

**Comment by dmarmor** [comment]
Hi @LETRA, can you elaborate on what exactly you want to do? Epichrome apps are just ordinary Chrome instances, so the media keys should work just as they do in Chrome (i.e. for starting/pausing playback on a web page). If you're trying to customize them in some way, that's beyond the scope of what Epichrome (or Chrome) can do, and you'd need to try something like Keyboard Maestro.

**Comment by LETRA** [comment]
I'm sorry, but more than a year ago from that message. I no longer use epichrome or Subsonic.

**Comment by dmarmor** [comment]
OK, thanks for the update. Closing this issue.
