### ISSUE TITLE
CPU resource consumption from 'lsof' call out.

### ISSUE THREAD

**Issue by pedramamini** [dmarmor/epichrome#155]
The usage of ```lsof``` to wait for Chrome engine exit consumes a lot of CPU resources. The call-out can be found here:

```
# CLEANUP: wait for Chrome engine to die, then clean it up
function cleanup {  # $1 = CHROME ENGINE PID
    # $$$$ old way to get PID from Chrome engine path
    # if pid=( $(/usr/bin/pgrep -foa "$1") )

    # wait for Chrome engine to exit
    /usr/sbin/lsof -p "$1" +r 1 &>/dev/null
```

I modified one of two instances of Epichrome to drop the ```1``` modifier from ```+r```. Falling back to the 15 second default (according to man) and it drastically reduces the overall consumption, though there is a brief usage spike every 15 seconds:

![image](https://user-images.githubusercontent.com/1253573/45136737-24187600-b16b-11e8-9bc0-1093887f05af.png)

Is there another approach entirely?

**Comment by GrogHills** [comment]
I'm seeing six lsof processes on my mac since the upgrade. I'm running six epichrome apps. These processes each use about 20% of my cpu, 100% of the time, with no end. I ended up killing the processes manually. When I restart an epichrome app the same thing occurs. New lsof processes running forever. Hmmm. Anybody else having this problem?

**Comment by pedramamini** [comment]
It's part of the start-up script for monitoring Chrome exit. Seems the strategy for doing has changed from last revision to this. If you edit your Epichrome file, found for example here:

```Pedram.app/Contents/MacOS/Epichrome```

Edit the following line:

```    /usr/sbin/lsof -p "$1" +r 1 &>/dev/null```

To drop the ```1``` after ```+r```:

```    /usr/sbin/lsof -p "$1" +r &>/dev/null```

That'll help for the time being until a proper fix is decided upon.

**Comment by dmarmor** [comment]
I won’t have a chance to look at this till next week, but soon as I can I’ll look for a less CPU-intensive way to wait for the parent process to end. If anybody knows a better way to do this with only default-install commands, I’d be grateful!

**Comment by ylluminate** [comment]
I'm finding the same thing here. Unfortunately I ended up with a boatload of `lsof` processes (9 while running 9 Epichrome apps at once) and hundreds of % cpu utilization by (Epi)Chrome processes as well as a halting system. Even with >100 GB of ram and 16 cores, my system is acting as though it was beaten in the head with a baseball bat.

Hmmm, not sure of a good replacement.

**Comment by ylluminate** [comment]
@henderea happen to have any thoughts on this?

**Comment by ylluminate** [comment]
This is a really good find @henderea. That's a rather obscure usage for `kill` with that signal that I was not aware of!  Extremely useful to know about, thanks!

**Comment by dmarmor** [comment]
Thanks all for bringing this to my attention, and thank you @henderea for the kill -0 loop idea. I've incorporated that into a new version that will hopefully solve the CPU-usage problem. Hopefully will be up tonight or early tomorrow...

**Comment by ylluminate** [comment]
While using `App Tamer` and doing some debugging with the developer, I found that `sleep` is being spawned insanely frequently via Epichrome instances. Something has been gumming up `App Tamer` very badly and I believe that this is it, but will report back once I know for sure...

**Comment by dmarmor** [comment]
Yes, the cleanup monitor that runs along with each Epichrome instance does invoke sleep (it sleeps for about a second, then checks if the app is still running), so that would account for sleep being spawned frequently. But of course each instance of sleep dies before the next is invokes, so it's not like it's spawning them out of control. Also from my tests of CPU usage, it is hardly using any (something like 0.2% on my system). That said, if you're noticing a CPU or resource problem connected with this, I'll look into another way to do this monitoring. But I remember doing a bunch of tests on this back in the day and the sleep method was the lowest footprint I found at the time...

**Comment by ylluminate** [comment]
Hmm. According to the `App Tamer` dev this might be creating some difficult-to-handle housekeeping.  I have yet to hear back from him so perhaps my concern is premature, but he added some debug code in to try to figure out why `App Tamer` has been sometimes consuming way too much CPU time. It goes up to consistently using >50% on each of it's processes at some odd time that we can't isolate.  Even with a few Epichrome apps open after a reboot everything seems fine for several hours to perhaps even a day or two, but then suddenly it begins to chew up a lot of CPU.

As he notes:
```
OK - after testing and going through your logs for the umpteenth time, my suspicion is that you've got a process somewhere that's launching over and over again at a fairly rapid rate. 

When this has happened in the past, I used to point people to the Console log where they'd see messages from launchd saying it was waiting 10 seconds to respawn a process or daemon that was repeatedly crashing. Then they could sort that out. Unfortunately, in Mojave and Catalina the Console log is relatively useless because there's so much information going by so fast. 
```

So ultimately after some more conversation he added some additional instrumentation to the app to accumulate stats on process launches, etc.  When I looked at those logs I found a lot of `sleep` processes, but they don't necessarily seem to be happening too quickly with perhaps at most maybe 8-15 happening each second.  I know that that's not nothing, but it doesn't seem that it should be overwhelming.  I'll have to update this further once he reviews the log more closely to see if he catches something I'm not seeing - sleep simply stood out and when I did `pstree -s sleep` I saw that the two primary culprits were Epichrome instances and Parallels Desktop (which seems to be firing fairly slowly).

**Comment by dmarmor** [comment]
Yeah, please let me know what he comes back with. In the meantime, if you want to find out whether the Epichrome helper app is what's causing any performance issues you're seeing when you have a lot of apps running, you can just kill all the running helpers. This command should find all the running helper apps of both pre- and post-2.3.0 apps:

```bash
ps -x | grep MacOS/Epichrome
```

You can then kill all of them using the PIDs listed by that command. (The new-style cleanup app is called EpichromeHelper.app and it's nested inside the main app. In older apps, it's just the main app executable, which is called Epichrome.)

The only side effect of doing this is that when you quit your apps, the engine won't get cleaned up, so your older apps will be huge. You can slim them back down by running each one once and quitting it while the monitor process is still running.

If you do run this experiment, let me know how it goes and if it makes any difference to your performance. Thanks!
