### ISSUE TITLE
[Total]Finder hangs Epichrome App creation in 10.14...

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#157]
Just a heads up here. Updated to the most recent build of Mojave and had an interesting issue arise. Each time I attempted to create an Epichrome app I was getting an AppleScript hang. I noticed that for some reason it was hanging Finder.  On relaunch of Finder, Epichrome proceeded naturally. I noticed that TotalFinder did not restart on relaunch so it seems like TotalFinder may have some issues that are causing some hangs or such - or it could just be Finder hanging altogether. Either way you slice it, Finder hangs are problematic.

**Comment by dmarmor** [comment]
Hi @ylluminate, has this problem persisted for you? I've never used TotalFinder, so don't really have a way to test that scenario. Hoping that the update I did for Mojave might've fixed this?

**Comment by dmarmor** [comment]
Hey @ylluminate, just checking in on this again. Did this behavior go away? If not, I'm hoping the new update I'm working on will fix it. (I'm sure you've seen 5 different posts about that and the Patreon on other issues, so I'll spare you the spiel...)

**Comment by dmarmor** [comment]
Hey @ylluminate, closing this for now, but if you're still experiencing it and/or have more info, let me know and I'll reopen.
