### ISSUE TITLE
Icon badges

### ISSUE THREAD

**Issue by dsernst** [dmarmor/epichrome#16]
Is there a way to add icon badges to SSB apps, similar to Fluid's premium functionality?

[![image](https://cloud.githubusercontent.com/assets/6340841/8994499/8ab34062-36c0-11e5-936f-b41240db1136.png)](http://rothmanshore.com/2014/04/06/give-gmail-its-own-app-in-the-os-x-dock-including-badges-and-notifications/)

**Comment by dsernst** [comment]
It uses this userscript to grab the number of unread messages from Gmail:

```js
window.fluid.dockBadge = '';
setTimeout(updateDockBadge, 1000);
setTimeout(updateDockBadge, 3000);
setInterval(updateDockBadge, 5000);

var regex = /\s*Inbox\s*\((\d+)\)[^\d]*/;

function updateDockBadge() {
	var newBadge = '';

	// loop thru anchor tags
	var anchorEls = document.getElementsByTagName('a');
	//console.log('anchors: ' + anchorEls.length);

	for (var i = 0; i < anchorEls.length; i++) {
		var anchorEl = anchorEls[i];
		//console.log('anchorEl: '+ anchorEl);
		
		var text = '' + anchorEl.innerText;
		if (!text.length) continue;
		if (-1 == text.indexOf('(')) continue;
		var res = text.match(regex);
		if (res && res.length > 1) {
			//console.log('res: '+ res);
			newBadge = res[1];
			break;
		}
	}

	window.fluid.dockBadge = newBadge;
}
```

**Comment by steiney001** [comment]
dsernst,

If you just need to implement a userscript within your created SSB to get the functionality you're looking for, just install the tampermonkey extension from the Chrome store. It will allow you to install and use the userscript. If you want to install a userstyle also, grab the Stylish extension. Hope that helps!

**Comment by dmarmor** [comment]
Hi @dsernst,

As mentioned in the readme, I've been looking into this. My early experiments haven't been promising, though. Because Epichrome is just a wrapper around Chrome, the only way to do badges would be with some facility that Chrome exposes, and I haven't been able to find any.

I've been doing some experimentation with creating a version of Epichrome that uses Firefox as its engine, and Firefox does have this ability, but that's a long-term project, so I wouldn't hold your breath for it.

Sorry to say, but if badges are a deal-breaker for you, you're probably best off sticking with Fluid for now, and checking back here periodically to see if I've got the Firefox experiment off the ground.

**Comment by steiney001** [comment]
@dsernst,

Did you have any luck with using your script with my suggestion (two comments above)? I tried it on my end and did not get it working, but I'm a total noob with stuff like that, so my inability has no real bearing on the possibility of it.

**Comment by dsernst** [comment]
@steiney001 I don't believe just installing the userscript alone with work. The script depends upon updating this `window.fluid.dockBadge` object, which is not available outside of Fluid. As @dmarmor mentions, there is no similar badge functionality available in Chrome.

@dmarmor Yes, I see what you mean. It seems like Chrome would need to add support to call OS X's native [Notification Center Framework](https://developer.apple.com/library/prerelease/mac/documentation/NotificationCenter/Reference/NotificationCenter_Framework/). From my own research, it seems like Google only wants to stick with its own independent [Notification Center api](https://developer.chrome.com/apps/notifications), which doesn't seem to support badges.

**Comment by steiney001** [comment]
@dsernst Ah, gotcha. That makes sense. Thanks for explaining it!

**Comment by dsernst** [comment]
@steiney001: For sure. And welcome to the wonderful world of open-source! :tada:

**Comment by dmarmor** [comment]
Hey guys,

@dsernst is right. There's no javascript hook in Chrome to display a dock badge. I explored some other ways of trying to do it, but no luck...
