### ISSUE TITLE
No longer shows window previews with Hyperdock

### ISSUE THREAD

**Issue by fatmcgav** [dmarmor/epichrome#160]
Following on from #159, I've noticed that window previews no longer appear to be working in Hyperdock (https://bahoom.com/hyperdock/). 

These worked fine prior to upgrading to 2.2.2, and continue to work fine for the vanilla Google Chrome app... 

E.g. Normal Google Chrome hover:
![image](https://user-images.githubusercontent.com/2235170/45305347-fc7e3080-b511-11e8-953c-f71bf08e26a1.png)

Epichrome app hover:
![image](https://user-images.githubusercontent.com/2235170/45305394-1750a500-b512-11e8-8cf5-055de395dd50.png)

I also created a fresh Epichrome browser instance, and that exhibited the same lack of preview windows... 

Any ideas?

Cheers

**Comment by dmarmor** [comment]
Hi @fatmcgav, I've never used HyperDock, so can't comment on that specifically, but I suspect it's somehow getting confused by the fact that the Epichrome app is basically just a launcher for a wrapped instance of Chrome. In some sense, the Epichrome app itself *doesn't* have any windows, only the underlying Chrome instance. I still would've thought that would be what was appearing in the dock and so its windows would show up, but that's the best theory I can come up with.

If that is the case, then unfortunately there isn't anything I can do about it. The whole architecture of Epichrome is to function as an invisible wrapper around Chrome instances.

I'm going to close this issue for now, as I don't think I can fix it, but if you have more info that might help or point to a solution, please let me know and I'll reopen. Thanks!
