### ISSUE TITLE
Following a desktop notification opens link in ALL open epichrome apps

### ISSUE THREAD

**Issue by JimmySamurai** [dmarmor/epichrome#162]
- I have Gmail set up as an Epichrome app. (I have 7-8 Epichrome apps, usually running simultaneously)
- OSX Desktop notifications are switched ON for Gmail.
- When clicking 'Open' in desktop notification, Gmail is launched in every open Epichrome app as a new tab. 
- This only started occurring since updating to 2.2.2, persists in 2.2.3

Any way to prevent this happening? 
Ideally, it should switch to / open the Gmail app.

**Comment by ostertoaster** [comment]
+1 to experiencing this issue. My notifications are coming from an SSB for Hangouts Chat, but same behavior.

**Comment by aponsin** [comment]
+1 having this issue too. FYI I am a new user of epichrome. Did this use to work properly ? Meaning notification from the right epichrome apps would bring up the right app ? (and not the default browser for instance ?)

**Comment by JimmySamurai** [comment]
> +1 having this issue too. FYI I am a new user of epichrome. Did this use to work properly ? Meaning notification from the right epichrome apps would bring up the right app ? (and not the default browser for instance ?)

Still an issue for me. Considering uninstalling as I need the notifications, but don't need the other windows opening.

**Comment by talleux** [comment]
+1 having this issue with Epichrome 23.2.4, Mac Mojave 10.14.5 (18F132) and Chrome 74.0.3729.131

**Comment by dmarmor** [comment]
Closing this issue and moving discussion to issue #122. If this is solvable at all (which I kind of doubt given how Epichrome works), it'll be the same fix as that issue.
