### ISSUE TITLE
All epichrome apps stopped working showing epichrome crashes on startup

### ISSUE THREAD

**Issue by ja601** [dmarmor/epichrome#164]
All of a sudden _all_ epichrome apps I'm using (Gmail, GCal, Amazon,..) have stopped working simultaneously. Every single one now crashes on startup with an error message that epichrome has crashed. See screenshot:
<img width="802" alt="screen shot 2018-09-20 at 16 45 03" src="https://user-images.githubusercontent.com/23050789/45826467-d8320900-bcf4-11e8-9362-96892b972cec.png">

An epichrome (currently 2.1.20) or maybe a chrome (69.0.3497.100) update problem? 

Any ideas what I could try are greatly appreciated.

Anybody experiencing the same problem?

**Comment by ja601** [comment]
Ok, I put the older Chrome back in (**68**.0.3440.106)
and the epichrome apps are back up. 

So, guys careful with the most recent update. It seems to be incompatible.

Hopefully this incompatibility is fixed soon.

**Comment by ja601** [comment]
I'm still trying to figure out how to suppress Chrome updates for the time being.

`defaults write com.google.Keystone.Agent checkInterval 0`
was already overridden once. :-/

**Comment by tomatic** [comment]
Have you downloaded the latest EpiChrome release? Works fine with Chrome 69 for me.

**Comment by ja601** [comment]
You are absolutely right. I wasn't aware of the version update - somehow thought updates would be automatic or that there would be reminder.

All good now with 2.2.3 in combination with Chrome 69. Thanks.

**Comment by dmarmor** [comment]
Closing this issue.
