### ISSUE TITLE
Chrome Extension Rules Not Working

### ISSUE THREAD

**Issue by pnewell** [dmarmor/epichrome#166]
I am trying to set up rules so that links open in other the default browser but it never seems to work.

I have the following set:
![](https://cl.ly/18fbf846a0bf/Screen%20Shot%202018-09-26%20at%203.02.39%20PM.png)

The rule text is:
`https://support.unqork.com/*`
`https://unqork.zendesk.com/*`

I tried the following two links
https://unqork.zendesk.com/agent/dashboard
https://support.unqork.com/hc/en-us

Both result in the link opening in my default browser.

I have also tried removing the https:// from the rules and still no luck. Any advice?

**Comment by dmarmor** [comment]
@pnewell, those URL patterns should match. Are you certain that those links were set to open in the same tab when clicked? For diagnosis purposes, you could try changing "Same tab" to "Either" and see if it helps. Let me know!

**Comment by dmarmor** [comment]
Closing this issue for now. @pnewell, if you're still having trouble, please let me know and I can reopen.
