### ISSUE TITLE
Unable to Run / Unable to clear old engine

### ISSUE THREAD

**Issue by boywithk9** [dmarmor/epichrome#168]
Recently I've had to start over creating new epichrome apps because when I try to launch an existing app, I get an error: 

Unable to Run
Unable to clear old engine

Is starting from scratch the only solution?

**Comment by boywithk9** [comment]
Recreating the app only solves it until I restart. Then I get the same error again.

**Comment by afsoltys** [comment]
Same problem! Only happening with one of my apps though. @boywithk9 any luck? Anyone else?

**Comment by afsoltys** [comment]
<img width="532" alt="screen shot 2018-11-05 at 8 00 11 pm" src="https://user-images.githubusercontent.com/44791233/48036494-aeaf2e80-e136-11e8-8c0d-bf8a19f5ceb4.png">

**Comment by afsoltys** [comment]
<img width="532" alt="screen shot 2018-11-06 at 12 04 33 pm" src="https://user-images.githubusercontent.com/44791233/48099380-5dae4180-e1ed-11e8-9d4e-3ced85a7e1ae.png">

**Comment by afsoltys** [comment]
This error message also appears sometimes...

**Comment by dmarmor** [comment]
Hmm, I've never seen this behavior, but it does seem like something got corrupted, or possibly there was a permission problem in one of your apps. Is anybody still experiencing this with Epichrome 2.2.4?

**Comment by boywithk9** [comment]
All good for me with 2.2.4
