### ISSUE TITLE
What does "Register app as a browser?" mean

### ISSUE THREAD

**Issue by dsernst** [dmarmor/epichrome#17]
![image](https://cloud.githubusercontent.com/assets/6340841/8995969/b714df2c-36c9-11e5-86bc-3d5d92412919.png)

The implications of this step are not at all clear.

**Comment by dmarmor** [comment]
You can safely leave this as No if you don't know what it is. It registers the app as a browser in OSX, which allows you to use it as a target for programs like Browser Fairy (or you could set it as your default browser in System Preferences). If you don't need that functionality, just set it to No.

**Comment by heyfletch** [comment]
I registered my "Dev Browser" as a browser, but it doesn't show up as an option... for example in CodeKit's list of Browsers to select. Wondering if there's a way to register this, especially after creating the app.

**Comment by dmarmor** [comment]
Hi @heyfletch, did you ever resolve this? There's not really anything more an Epichrome app can do than register itself as a browser. That should allow it to show up in any list of browsers. Does your Dev Browser show up if you go to System Preferences > General and click the Default web browser drop-down menu?

**Comment by heyfletch** [comment]
I'm not sure since I don't use that example any more (CodeKit). I don't recall any issues recently.

**Comment by dmarmor** [comment]
OK, thanks for the update. If you find the problem again, post here and I'll reopen and look into it.
