### ISSUE TITLE
Why do i get this error "Creation failed: Unable to find Chrome executable"

### ISSUE THREAD

**Issue by swealpha** [dmarmor/epichrome#171]
Hello!

I am using mac osx high sierra.

Why do i get this error that says "Creation failed: Unable to find Chrome executable" ?

Thank you.

**Comment by dmarmor** [comment]
Hi @swealpha, are you still having this problem with Epichrome 2.2.4? My first question would be to confirm that you do in fact have Google Chrome installed on your system. Assuming that's the case, do you have Spotlight enabled and indexing wherever Chrome is installed?

When it fails to find Chrome, does Epichrome present a file chooser and ask you to find it? It's supposed to do that...

**Comment by dmarmor** [comment]
Closing this issue for now. If you're still having trouble with this, please let me know and I can reopen.
