### ISSUE TITLE
Choosy won't focus on epichrome browser with epichrome 2.2.3

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#174]
Hello, i have the same problem as issue #123 using choosy: if an epichrome browser is already open, choosy won't focus on it nor send the URL - simply nothing happens. If i choose another browser (tested with Firefox, Safari, Chromium, Chrome Canary, Opera) then it works perfectly.
If the epichrome browser isn't already open, nothing will happend neither.

I use the current latest epichrome 2.2.3, and OSX El Capitan.

I really love epichrome, especially combined with choosy. It has become a central productivity tool in my daily work. What could i do to find a workaround or help finding a solution?

_Originally posted by @talleux in https://github.com/dmarmor/epichrome/issues/123#issuecomment-436551863_

**Comment by ylluminate** [comment]
Have you tried `Browser Fairy.app` yet? I've been using it with great success for quite some time now...

**Comment by nopdotcom** [comment]
I'm not seeing these problems with Choosy on 10.13.

If you want to screw around with Platypus-scripting for this, the magic words are 

/usr/bin/osascript -e 'activate application "Google Chrome"'

or

/usr/bin/osascript -e 'activate application "Twitter Epichrome"'

**Comment by fulltrucker** [comment]
macOS 10.11.6 El Capitan
epichrome 2.2.3
Choosy 1.2.2

Experiencing the same behavior as @talleux describes in the original post. Switched to Browser Fairy.

**Comment by dmarmor** [comment]
Has anybody tried Choosy with Epichrome 2.2.4 to see if it's improved at all?

**Comment by talleux** [comment]
Hello,

since i updated from El Capitan to Mojave, Choosy works again!
Epichrome 2.2.4
Choosy 1.3

I'm not experiencing any problems now.

On El Capitan Choosy wasn't woking at all anymore

**Comment by dmarmor** [comment]
Excellent! Closing the issue for now...
