### ISSUE TITLE
How to disable same-origin policy

### ISSUE THREAD

**Issue by ylluminarious** [dmarmor/epichrome#175]
I am trying to disable the [same-origin policy](https://en.wikipedia.org/wiki/Same_origin_policy) in an Epichrome  browser for testing purposes. According to [this StackOverflow answer,](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome/6083677#6083677) all that's needed to accomplish this is to run Chrome with two extra command-line options:

```sh
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security --user-data-dir=~/path_to_chrome_user_data
```

I have tried to do this, substituting `~/path_to_chrome_user_data`with `~/Library/Application\ Support/Epichrome/Apps/MyAppName`. But whenever I try this, Epichrome doesn't start the SSB as per usual. Instead, I get several windows which say that I've just installed Chrome and ask me to get started and send data to Google, etc.

Clearly something is going on which is causing Epichrome to not act right, either as a result of `--disable-web-security` or `--user-data-dir`. I'm not sure which one is the problem, what exactly the problem is, and how to fix it. This is clearly happening due to the fact that this is an Epichrome browser and not a normal Chrome browser, but that's all I know.

I would appreciate any advice.

**Comment by ylluminate** [comment]
Have you tried poking about in `/Applications/<EPICHROME_APP_NAME.app>/Contents/Resources/Scripts/*` yet?  It seems that `config.sh` is the main place to make changes...

The other thing is: can you make this work with Chrome by itself (no Epichrome) right now?  I can't help but wonder if some of these recent changes by Google have destroyed this function... so maybe its worth trying in just Chrome first as a sanity check.

**Comment by ylluminarious** [comment]
@ylluminate Yes, this is what I tried in `config.sh`

```
SSBCommandLine=( --disable-web-security --user-data-dir ~/Library/Application\ Support/Epichrome/Apps/MyAppName )
```

That line is what causes the aforementioned behavior:

> [...] I get several windows which say that I've just installed Chrome and ask me to get started and send data to Google [...]

And yes, this works fine in Chrome by itself. The problem is specific to Epichrome.

**Comment by dmarmor** [comment]
Hey, @ylluminarious, the problem with this is that Epichrome apps pass the --user-data-dir themselves to point at their profile directories in ~/Library/Application Support/Epichrome/Apps.

Based on my quick read of the Stackoverflow answer, I would try removing the --user-data-dir argument from your edit of config.sh (but leave --disable-web-security). This will point your app at its existing user directory, which should satisfy the needs of the --disable-web-security flag (according to that Stackoverflow answer, anyway).

Let us know how it works!

**Comment by dmarmor** [comment]
Hi @ylluminarious, closing this issue for now, hoping my suggestion helped. If not and you're still looking for a solution, please let me know and I'll reopen.

**Comment by dmarmor** [comment]
Thanks, @vitalybe, glad it's working!
