### ISSUE TITLE
<EPICHROME_APP> wants access to control "System Events.app" in Mojave

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#176]
Been having an odd issue sometimes when either opening an app a second time (to get focus quickly) or sometimes when other apps attempt to open an Epichrome app instance.  The following dialogue pops up and then it seems to fail to open the link:

![example](https://cl.ly/c24aefb4b0af/Image%202018-11-15%20at%203.33.19%20PM.png)

Full dialogue contents for search indexing:
> "APP_NAME.app" wants access to control "System Events.app". Allowing control will provide access to documents and data in "System Events.app", and to perform actions within that app."

**Comment by ylluminate** [comment]
Tentative possible solution, seems to perhaps alleviate the issue so far, is to manually add the app to `System Preferences > Security & Privacy > Privacy > Accessibility`. This is definitely not an optimal solution, but it might help or stop this... I've tried it a couple times and it seemed to help so far, but I'm going to need to allow some time to pass and more testing to be sure since the issue doesn't always seem to actually happen reliably so far...

**Comment by jameschao** [comment]
@ylluminate - I'm not sure if this was the cause, but I've found that the Epichrome apps start really slowly when I enabled the accessibility setting (even on app start, the dock icon bounces really slowly). Did you see that issue as well?

**Comment by ylluminate** [comment]
@jameschao interesting. I haven't really noticed this per se, but it has been sluggish in startup. I normally attribute that to keeping rather large browsing sessions per just about each Epichrome Chrome instance... I'll keep it in mind over the next couple days to see if I have any thoughts.

I am also running beta releases of macOS 10.14.2, so that might also affect things.

**Comment by ylluminate** [comment]
You know @jameschao, I've noticed that Chrome itself in all Epichrome instances is running slower now... It seems that it's just moving at a slow lurch whenever any of them start up now. :(

**Comment by jameschao** [comment]
For me, it's been ok overall in terms of performance. It was super slow only when I have accessibility access.

**Comment by ylluminate** [comment]
@jameschao I think this might be the issue: https://apple.stackexchange.com/questions/352454/system-slowness-how-to-disable-or-short-circuit-tccd-in-mojave-slows-app-su

**Comment by ylluminate** [comment]
@jameschao also note @dmarmor's new update today:
https://github.com/dmarmor/epichrome/issues/163#issuecomment-467684527

**Comment by jameschao** [comment]
Thanks @ylluminate - I just tried it and so far it looks good!

**Comment by dmarmor** [comment]
Hey @ylluminate, has 2.2.4 fixed this problem for you?

**Comment by ylluminate** [comment]
@dmarmor this does seem to have been resolved now from what I'm seeing!
