### ISSUE TITLE
Epichrome Extension Bundled Separately

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#178]
I believe we should bundle the Epichrome extension separately:
https://stackoverflow.com/questions/28618545/chrome-extension-to-open-up-a-specific-url-in-a-different-browser

There's definitely a need...

**Comment by dmarmor** [comment]
I'll add that to the to-do list. It'd be nontrivial, though, as the native messaging host would have to somehow be packaged and installed separately. Right now that's all built into the Epichrome app...
