### ISSUE TITLE
epichrome does not produce edible pinochio's steak n cheese

### ISSUE THREAD

**Issue by davidjk** [dmarmor/epichrome#18]
this is unacceptable

**Comment by dmarmor** [comment]
I understand your concerns, sir. Please rest assured our R&D team has been working non-stop on this issue and will have a solution very soon. Two weeks ago we completed our first successful experiment producing a Pinocchio's Sicilian slice, and are working our way up. We managed to produce a steak n cheese last week, but unfortunately it proved fatal to several members of our beta team. We soldier on in their memory.
