### ISSUE TITLE
Epichrome apps don't inherit system/privacy permissions (like microphone) from Chrome

### ISSUE THREAD

**Issue by mhuusko5** [dmarmor/epichrome#181]
I'm trying to make an Epichrome app of Google Voice on Mojave. However on Mojave, Chrome has to request permission for microphone access. Epichrome apps neither inherit this permission, nor do they trigger the request for their own bundle/id.

**Comment by dmarmor** [comment]
Hmm. I'll take a look at this and see if I can figure out a workaround. Thanks for the report!

**Comment by darrenaalfonso** [comment]
Encountering the same issue.  Mic/webcam are inaccessible from within Epichrome apps.  My specific use case is joining conference calls/online meetings.

**Comment by patrickoshaughnessey** [comment]
Also seeing same. Just updated to Mojave yesterday, and even after re-creating a Google Hangout based app, the camera permission is not carried over, nor prompted for.

**Comment by alatteri** [comment]
For me, I am getting the prompt and allowing, but still not camera/mic access for WebRTC apps.

**Comment by alatteri** [comment]
I see what is happening here.  Epichrome apps will prompt for Camera/Mic access, but won't instigate MacOS prompt for permission, so they are still invisible to browser.  This does work properly with CoherencePro thought.

**Comment by neeerd** [comment]
Same problem here. Please fix it!

**Comment by dmarmor** [comment]
Just updating, I will look into this issue...

**Comment by dmarmor** [comment]
Could someone please send me a URL that requests these permissions (preferably without a lot of setup required) so I can easily test this on my system? Thanks!

**Comment by manishie** [comment]
I used epichrome 2.2.4 with all default options, with the URL https://hangouts.google.com.  Login with any google/gmail account.  Attempt to make a free phone call to something like 800-555-1212.  Or I'm sure a video call to another google/gmail user would have the same issue. Epichrome does ask if you want to allow access to microphone, but it still doesn't work.

**Comment by darrenaalfonso** [comment]
> Could someone please send me a URL that requests these permissions (preferably without a lot of setup required) so I can easily test this on my system? Thanks!

Try this: https://turncameraon.com/

**Comment by flaviolira123** [comment]
Hi! I LOVE Epichrome, but this limitation is making it not possible to use it on my workflow 😭

I have my fingers crossed that Mr. @dmarmor will find the time on his busy schedule to take a look at it! 

@dmarmor , we know you're doing this as a labor of love (at least for the time being, and if the app becomes a paid app down the road I'll gladly pay for it) and we appreciate it 😀

**Comment by dmarmor** [comment]
Hi all,

I wanted to let you know I'm working on a fairly major update that I believe will solve this, as well as many other long-standing problems. With my work schedule, it may take a while, but I'll let you know when it's ready for testing. Thanks for your patience!

One more thing:

<shameless_plug>
I've set up a Patreon. If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it (e.g., assuming I end up with the bundled-Chromium architecture, I would not consider bumping the Chromium build to be a new version).
</shameless_plug>

**Comment by ylluminate** [comment]
This has been resolved in most recent Electron updates: getferdi/sponsors-only#1300

**Comment by dmarmor** [comment]
Hi all! I believe this issue should be solved in 2.3.0, so I'll close it for now. If you notice this problem in the latest update, please let me know and I'll reopen.
