### ISSUE TITLE
multiple OSX profiles

### ISSUE THREAD

**Issue by stevegray** [dmarmor/epichrome#183]
I have 1 laptop with a work profile and a personal profile.  My Epichrome apps are in /Applications.  They only work *correctly* when I open them from the OSX profile I used to create them.  Opening from the other profile doesn't load the single window app.

Is it a preferences thing...?

**Comment by talleux** [comment]
I don't know if it's possible: While your Epichrome Apps are in /Applications all the preferences and data of your Epichrome Apps are under /Users/<USERNAME>/Library/Application Support/Epichrome/Apps/<YOUR EPICHROME APP> so when you call them with another Mac profile than the one with which you created them then won't be able to access their preference and data files.

Not sure if there is a trick to achieve what you want, for example copying or symlinking you preference directories to you other profile?

**Comment by stevegray** [comment]
Thanks for the response and your efforts.  I just duplicated them in ~/Applications and moved on.  I use Epichrome extensively every day.  Please keep up the project!!

**Comment by dmarmor** [comment]
Yes, sorry, during one of the redesigns necessary to keep up with ever-tightening Chrome and macOS security, I had to basically make Epichrome apps single-user only. Going forward, they really should all live in ~/Applications only...
