### ISSUE TITLE
Donations/Support?

### ISSUE THREAD

**Issue by bfenster** [dmarmor/epichrome#184]
Exact duplicate of #88, except we've now traveled into the distant future of 2019.

I respect being uneasy about taking donations from people who may then be frustrated at the slow release schedule. Counterargument: _any_ Epichrome is better than no Epichrome.

When Mojave broke everything I was plenty frustrated, but not so much at the lack of an Epichrome patch as at the complete lack of any viable alternatives anywhere on the planet. When the 2.2.4 announcement popped up I literally jumped out of my chair and did a little happy dance. (I'm not even exaggerating.)

Surely that's worth a few dollars, if nothing else!

Maybe just link in the Github README to a Patreon account taking "per release" pledges?

**Comment by talleux** [comment]
I completely agree. Epichrome dramatically changed my daily workflow in such a very effective and nice way that i'd like to donate without creating a pressure for future development but simply as thank for past development...

**Comment by dmarmor** [comment]
Hey @bfenster, @talleux (as well as @Felix-N, @GrogHills from other threads),

Thank you all so much for the support. I love knowing that people are getting value out of Epichrome, and appreciate your generosity. And @bfenster, you're right--over the last couple years my time has become so limited I've felt like it'd be unfair to take donations when I'm sometimes not even able to keep up with critical bugs. But your per-release Patreon idea is great, and I'll see if I can get that set up.

In the meantime, the best way to support Epichrome is to keep doing what you're doing: stress-testing it, submitting issues, and helping diagnose problems. On that topic, I'm hoping soon to start a "beta" thread where people who are interested can subscribe and help test the latest beta releases of both the app and extension.

Cheers!

**Comment by GrogHills** [comment]
I love epichrome and can imagine working without it. Several other folks
have created products with a similar concept, but having separate apps for
different work areas, then using browser fairy to route the links to the
correct app is just awesome. Thank you!

I'd love to have the ability to update the list of tabs that launch on
startup of an epichrome browser. Is that possible, even if manually?

- Gregory

Gregory Morse
gmorse@morseinc.com

**Comment by dmarmor** [comment]
Thanks, @GrogHills! It's on my long-term to-do list to allow editing of already-created Epichrome apps, but for now the only way to do that would be to edit the app's config.sh file, which is in:

```
<app-path>.app/Contents/Resources/Scripts.config.sh
```

Make very sure the app is not running, then edit that file. Assuming you created a Browser Tabs app, you'll find a line like this:

```
SSBCommandLine=( http://www.url1.com/ http://www.url2.com/ )
```

Change those URLs to whatever you want (of course leaving the parentheses and spaces, save the file, and next time you launch the app, it should open your new URLs.

**Comment by dmarmor** [comment]
Hi all,

So I've finally set up a Patreon for Epichrome, and I've love it if you considered being the first to join. I've set it up to be a per-release membership, so you'd only be charged when I put out a new version. Your membership would mean a lot to me, and would help cover the costs and time I put into the project.

Thank you all for your support of Epichrome!

**Comment by dmarmor** [comment]
I just realized I forgot to actually include the link to the Patreon page (hazards of writing at an airport in the middle of holiday travel). Here it is:

https://www.patreon.com/epichrome

**Comment by GrogHills** [comment]
Just signed up!

**Comment by dmarmor** [comment]
Received and much appreciated, @GrogHills and everyone else who has signed up so quickly. I really appreciate it!
