### ISSUE TITLE
Error on path to SSB by browser registration? Wrong path when opened? Choosy bug?

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#188]
**Note: I'm not sure how to name this issue as i'm not sure to understand the origin of the following problem. So if the title of this issue needs to be changed, i'm happy for some suggestion.**

I use Choosy to open links in the appropriate SSB(s) and the combination of Choosy and Epichrome ist a dream of productivity for me ;-)
When i click on a link an choose my SSB in Choosy **WHILE** the SSB i choose is already open, it _sometimes_ tries to open the the SSB using the "wrong" path:
instead of opening 
/Applications/MySSB.app
it tries to open
/Applications/MySSB.app/Contents/Resources/ChromeEngine/MySSB.app

The behavior i observe:
The correct SSB jumps in the dock 1 time, then a **new** icon (the generic Epichrome icon, not the one set to my SSB) jumps also 1 time and then closes. Because Mojave shows me in the dock the recently opened applications, i could find out, what it tried to open using CMD+click on this icon.

Because i have little knowledge on how MacOS works with apps, i don't really know what should happen and Choosy _sometimes_ tries top open my SSB under this "wrong" path.

What i noticed: 
The folder 
/Applications/MySSB.app/Contents/Resources/ChromeEngine/MySSB.app
gets created when i start my SSB and gets removed when closing the SSB.

More details on this behavior:
- when the problem  occurs, i usually restart my SSB and then choosing this SSB in Choosy will open the SSB correctly
- this trick doesn't work all the time, nor does it work wit all my SSBs. I have SSBs where this trick never works. I could, if this help, check if i can find a pattern like when have the SSBs been created, for which the trick works or not. In case of the version of Epichrome that created the SSBs matters.
- i tried to delete and re-add the SSB in Choosy's list of browsers.
- it the SSB is not open, then Choosy will open the SSB correctly, all the time and with all my SSBs
- i just created a new SSB, opened it and _then_ added it to Choosy --> the problem can be reproduced and the trick whtih restarting the SSB doesn't wirk
- i did the same but added the browser to Choosy while it wasn't open (and even never opened before) --> same.
- i did the same using Epichrome 2.2.3 --> same

Choosy gets apparently offers me a list a of apps registred as browser, so i see only Epichrome SSBs that have been "registred as browser" in the creation process.

I wonder if the problem has to do with the way Epichrome registers the browser. But then Choosy couldn't open the correct SSB while it is closed, it does.

Could this be a bug in Choosy? Actually i don't think because i 

Any idea on this? Any further tests i could do to help debugging?

I use Epichrome 2.2.4 and MacOS 10.14.6

[Edit: removed possible relation to Issue 136]

**Comment by dmarmor** [comment]
Hmm. I suspect this actually is an issue with Choosy. The way Epichrome apps work, they create the ChromeEngine dynamically when they run, and destroy it when they quit. So when an app is running, there will be a second, identically-named app that is the underlying Chrome instance. Choosy must be getting confused and trying to open links through that instead of the real Epichrome app.

This would be solvable by referencing the app through its bundle ID rather than its name, which is something Choosy would have to do. In the meantime, if you're not too tied to Choosy, you could try [Browser Fairy](http://www.browserfairy.com), which in my experience works flawlessly with Epichrome apps.
