### ISSUE TITLE
Cannot screen share in Catalina OSX 10.15?

### ISSUE THREAD

**Issue by bolaurent** [dmarmor/epichrome#189]
After upgrading to Catalina, my vanilla Chrome instance won't  allow Google Hangouts to screen share unless I add Chrome to the System Preferences/Security & Privacy/Privacy list to permit "Screen Recording". 

I was able to add an Epichrome instance of Chome, but Chrome itself does not get added to the list in System Preferences. There is no manual way to add apps to the list. So, I cannot figure out a way to let Google Hangouts in Chrome screen share.

In the following image, the IGS app is an epichrome instance.

![image](https://user-images.githubusercontent.com/1839790/66851686-1cabca80-ef30-11e9-8f1d-24dc8da91591.png)

**Comment by dmarmor** [comment]
Hi @bolaurent,

I'm currently working on a fairly major update that should solve this and many other Catalina problems. With my work schedule, it may take a while, but I'll let you know when it's ready for testing. Thanks for your patience!

One more thing:

#### <shameless_plug>
#### I've set up a [Patreon](https://www.patreon.com/epichrome). If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it (e.g., assuming I end up with the bundled-Chromium architecture, I would not consider bumping the Chromium build to be a new version).
#### </shameless_plug>

**Comment by dmarmor** [comment]
Hi all! I believe this issue should be solved in 2.3.0. If you update existing apps and retain the external Chrome engine, you'd still need to add Chrome to the permissions list (or really any Chrome-based Epichrome app would do--adding one will add the permission for all of them, and Chrome itself). If you create a new app using the built-in Brave engine (or convert your app on update), then it will retain its own unique permissions and you won't have any confusion.

Closing this issue for now. If you notice problem in the latest update, please let me know and I'll reopen.
