### ISSUE TITLE
Multiple Windows

### ISSUE THREAD

**Issue by steiney001** [dmarmor/epichrome#19]
dmrmor,

Your app is awesome and really helpful to me. The only feature lacking in your implementation of an SSB versus my previous solution is the ability to open multiple SSB browser windows within the same SSB. I like to keep Google Calendar, Google Drive and Google Contacts in one SSB but in separate windows, so I can flip through them with Command+`.

In your implementation, it seems like only one window can be open at a time that hides the tab bar and address bar within a given SSB.

Also, it would be nice if I link opened within a given window would just open a new tab within that window, instead of forcing a new window to open, and show then show the tab bar without also showing the address bar.

Again, thanks for your work on this!

steiney001

**Comment by dmarmor** [comment]
Hi @steiney001,

Thanks for the feedback! Epichrome is just a wrapper around Chrome, and I haven't found a way to launch Chrome with multiple windows, so this functionality wouldn't be easy to implement. It'd have to be done through the helper extension somehow. I'll look into it, but off the top of my head, I can't think of a clean way to do it.

Just out of curiosity: why not just have Google Calendar, Drive and Contacts as separate Epichrome apps? Then they'd be in separate windows and you could flip through them with Command+Tab.

As for a link opening as a new tab within the same window, this isn't possible with Chrome app-style windows. App-style windows by their design in Chrome cannot have any tab-bar decoration, so there'd be no way to navigate between multiple tabs.

The best workaround for this would be to create an Epichrome app that uses browser tabs, but only has one tab defined. Then any new tabs created from that one would open in the same window--but of course it wouldn't be a clean app-style window.

You could also switch the app-style window to tab-style using Command+Shift+L and then open the new tab. But if you then switched back, the app window would detach from the other tabs and become a separate window again.

Sorry there isn't a cleaner solution--it's just the nature of Chrome.

**Comment by steiney001** [comment]
Hey @dmarmor,

No worries, and thank you for the suggestions! To answer your question, I have a lot of apps open during the day for work and I like to be able to keep my tab switcher menu (command+tab) as slimmed down as possible. That's the allure of the three-in-one version, to me. All three of those web apps pertain to a business I run, so it's nice that they're all in one spot, as if they're all one big app. In the Fluid version that I had been using, I named the SSB "Google Suite".

**Comment by dmarmor** [comment]
Gotcha, that makes sense. I'll add this to my to-do list and next time I dive into the code I'll take a look to see if it would be feasible to have multiple app-style windows. Can't promise anything, but if I can add that as an option without breaking anything else I'll do it.

**Comment by steiney001** [comment]
Wow! That's awesome. Thank you so much. This is my first time interacting on Git. You have no idea how pumped I am that you even read and responded to my message. I had been wanting something like what you made for a while, and I finally found it via Googling the other day, and I was like jumping up and down with excitement. That one feature is the only thing missing that would make it the absolute perfect replacement I had in mind!

Anyway, thanks again. And good luck. I wish I could help!

**Comment by dmarmor** [comment]
Hey, glad to have been your first interaction on github! Thank you for using the program and sending your feedback--it's really helpful. Whatever cool features are in the app pretty much came from people letting me know what they needed.

Cheers!

**Comment by cstopnet** [comment]
Just wanted to chime in that support for multiple windows would be incredibly helpful.  My use case is slightly different from steine001's : I use epichrome for Gmail and I like to have multiple gmail windows open at the same time (one showing an email I'm drafting, another showing an older email that has bearing on the email I'm writing, and maybe a third showing all my email).  Fluid is great for this, but I'm shifting to Epichrome so I can take advantage of Chrome extensions.  Any help on this front would be fantastic!

**Comment by dmarmor** [comment]
Thanks for the vote! It's on my to-do list. I just have to figure out the best way to do it. There's no way for Chrome to directly open multiple app-style windows on start-up, so I'm going to need to use the helper extension to somehow abuse Chrome's startup procedure...

**Comment by cstopnet** [comment]
Great to hear it's on your list!  Will be much appreciated.  Thanks for a
great app!

On Wed, Nov 18, 2015 at 11:54 AM, dmarmor <notifications@github.com> wrote:

> Thanks for the vote! It's on my to-do list. I just have to figure out the
> best way to do it. There's no way for Chrome to directly open multiple
> app-style windows on start-up, so I'm going to need to use the helper
> extension to somehow abuse Chrome's startup procedure...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmarmor/epichrome/issues/19#issuecomment-157776995>.
>



-- 
-- 
*Curt Knox*   |   StopTips
Office: (203) 364-4676 | Cell: (203) 913-0684
Email: cknox@stoptips.com <kweiss@brandstudios.com> | Web:www.stoptips.com
<http://www.brandstudios.net/>

**Comment by rafaelliu** [comment]
Just weighing in, I have yet another use: using Epichrime's GMail as the default email client, when I click a "mailto:" link (anywhere in the OS), it opens Epichrome in GMail's compose page at a new tab (a normal chrome tab, no SSB style).

If there were an option to open every new link a new SSB window it would allow "mailto:" links (and any other URL handlers) to work more seamless.

Btw, thanks for the very nice app!

**Comment by dmarmor** [comment]
Noted! Thanks for the feedback. I've had trouble dealing with incoming mailto links myself in my Gmail Epichrome app. It's on the list!
