### ISSUE TITLE
Browser routing no longer works with Mac OS 10.15 (Catalina)

### ISSUE THREAD

**Issue by ixley** [dmarmor/epichrome#190]
After upgrading to Catalina, Epichrome apps unfortunately no longer work for me. The issues seem very similar to routing issues experienced with Mojave (which were eventually fixed).
These are the two main issues I've been experiencing:
- An Epichrome app instance is often erroneously identified as the default browser instead of Chrome. (It's not always the same one.) Quitting the Epichrome app usually temporary fixes this. (i.e. Links route to the correct default Chrome while the 'problem' Epichrome app is not running.) The 'Stop further handling' option has occasionally done what it's supposed to, but usually doesn't. 
- Links triggered from within an Epichrome app open in that app instead of routing to open in the correct default Chrome browser. (If the default browser is set to something else like Safari, it seems to be less of an issue, but I haven't tested this extensively.)

Anyone else experiencing these issues with Catalina? Any suggested fixes? The problems seem very similar to what happened with Mojave so I'm hoping there's a fix for this. (I've tried deleting and recreating Epichrome apps with no success.)

**Comment by whatknows** [comment]
I am also having this problem. But no suggested fixes. :(

**Comment by nathanielread** [comment]
I'm also experiencing these issues.

**Comment by demmer** [comment]
I also had this problem. The best workaround I found was to get BrowserFairy and use that as my default browser, plus the epichrome extension.

With that in place I can get everything routed to Chrome.

**Comment by dmarmor** [comment]
Hi all, I'm working on a fairly major update that I believe will solve this (as well as many other long-standing problems). With my work schedule, it may take a while, but I'll let you know when it's ready for testing. Thanks for your patience!

One more thing:

#### <shameless_plug>
#### I've set up a [Patreon](https://www.patreon.com/epichrome). If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it.
#### </shameless_plug>

**Comment by dmarmor** [comment]
Hi all! I believe this issue should be solved in 2.3.0, so I'll close it for now. If you notice this problem in the latest update, please let me know and I'll reopen.
