### ISSUE TITLE
Catalina upgrade, epiChrome apps stop sending notifications

### ISSUE THREAD

**Issue by KajKandler** [dmarmor/epichrome#191]
I use GCalendar as an EpiCrome app, 2.2.4 and since my Catalina upgrade it stopped sending notifications, which off cause is rather unhelpful. Also only one EpiChrom app shows up in preferences for notifications.

**Comment by KajKandler** [comment]
Workaround, chrome://flags - Enable native notifications = Disabled

**Comment by jonboy345** [comment]
I also updated google chrome in my epichrome apps on Catalina and it fixed notifications as well.

**Comment by dmarmor** [comment]
Hi all,

I'm working on a fairly major update that may solve this (and many other Catalina problems). Given my work schedule, it may take a while, but I'll let you know when it's ready for testing. Thanks for your patience!

One more thing:

<shameless_plug>
I've set up a Patreon. If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it (e.g., assuming I end up with the bundled-Chromium architecture, I would not consider bumping the Chromium build to be a new version).
</shameless_plug>

**Comment by dmarmor** [comment]
Hi all! I believe this issue should be solved in 2.3.0, so I'll close it for now. If you notice this problem in the latest update, please let me know and I'll reopen.
