### ISSUE TITLE
Editing the startup tabs after making the SSB?

### ISSUE THREAD

**Issue by ElvisofDallas** [dmarmor/epichrome#192]
I thought I saw instructions for this in the issues when I worked setting up my first SSB last night, but now I cannot find that or the string of any of my startup pages inside the resources for Epichrome (or in app support).

Can someone point me to any instructions for adding an additional startup page for the browser? 
Thanks!

**Comment by ylluminate** [comment]
The easiest way I've found is to edit the `config.sh` from the shell. For example, open up `Terminal.app` and then enter `nano /Applications/NAME_OF_EPICHROME_APP.app/Contents/Resources/Scripts/config.sh` (replacing `NAME_OF_EPICHROME_APP` with your app name. Then you'll see a line at the bottom that you can edit. I made a test app and populated it with 3 examples:
```
SSBCommandLine=( https://www.google.com/mail/ duckduckgo.com yahoo.com )
```

You can replace these however you like.

**Comment by dmarmor** [comment]
Thank you @ylluminate! @ElvisofDallas, I hope this worked for you. Closing this issue now, but can reopen if you're still having trouble.

One more thing:

#### <shameless_plug>
#### I've set up a [Patreon](https://www.patreon.com/epichrome). If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it.
#### </shameless_plug>
