### ISSUE TITLE
fix/prevent default browser check and add incognito by default as optional feature

### ISSUE THREAD

**Issue by maiux** [dmarmor/epichrome#194]
Using 79.0.3945.117 Chrome on macOS 10.15.2
Since using "Set Chrome as default browser" within Epichrome app will result in setting original Chrome app as default browser and thinking that is too much tricky to fix it, what about setting --no-default-browser-check in all Epichrome apps by default?
Next, what about an option during creation script which permits creating Epichrome apps that start in incognito mode by default?
BTW, really like your work

**Comment by dmarmor** [comment]
These are great ideas. the default-browser check should be easy to fix. I may end up doing it with master prefs rather than a command-line flag, but it's on my to-do list. As for default incognito mode I'll need to do a bit more research to figure out how best to implement that option, but will add it to my list for a later release too. Thanks!

**Comment by dmarmor** [comment]
Hey @maiux, closing this issue for now. The default-browser check has been turned off for 2.3.0 app. Thank you for the suggestion!

As for incognito mode, it is possible to do, but will require a bit bigger architecture change than I can tackle right now. It's on my feature wishlist for a future release, but may be a while. In the meantime, if you don't mind getting your hands a bit dirty, you should be able to force that behavior yourself by mucking around in your app a little:

1. Back up your app (I like to just right-click it in the Finder and choose ```Compress```).
2. Open ```<your-app>.app/Contents/Resources/script``` in your favorite text editor.
3. Find the ```SSBCommandLine``` line. It will look something like:
```SSBCommandLine=( '--app=https://www.google.com/' )```
or
```SSBCommandLine=( 'https://www.google.com/' 'http://anothersite.com/' )```
4. Edit the line to look like this:
```SSBCommandLine=( --incognito '--app=https://www.google.com/' )```

The important thing is that the ```--incognito``` flag comes *first*, before the list of URLs.

If you want to use Epichrome Helper to route links, you'll need to open the Extensions page, click the ```Details``` button for Epichrome Helper and turn on "Allow in incognito" or "Allow in private."

Fair warning: I have not tested this extensively, so your mileage may vary. In my limited testing, you will not be able to use the Epichrome Helper keyboard shortcut or context menu to switch an app-window to show the address bar. Not sure why this doesn't work, but it doesn't.
