### ISSUE TITLE
2.3.0 BETA 2 - recovery question

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#196]
What would be the theoretical recovery process if a backup wasn't made properly for an app? If the old folder is, however, intact, what would need to be copied where to recover bookmarks, history, etc. from 2.2.x to 2.3?

**Comment by dmarmor** [comment]
If your goal is to have the data folder work with a 2.2.x app again, what you'd need to do is take the UserData subfolder and make that the root folder. So it would be a procedure similar to this:

```bash
cd ~/Library/Epichrome/Apps
mv Example/UserData Example.TMP
rm -rf Example
mv Example.TMP Example
```

**Comment by ylluminate** [comment]
So not `~/Library/Application Support/Epichrome/Apps`?

**Comment by dmarmor** [comment]
Sorry, that was a typo. I've edited the post.

**Comment by ylluminate** [comment]
Hey thanks! What about taking a 2.2.x to 2.3+ manually?

**Comment by dmarmor** [comment]
Hmm. I'm glad you got it working, but it really should not have been creating new app IDs on update. Were you updating from a very old version of Epichrome with an app you hadn't used in a long time? I can't think of any other reason that would've happened.

If not, would you mind zipping and sending me the old 2.2.x version of the offending app? That would really help me diagnose what happened.

**Comment by ylluminate** [comment]
Wow, weird. I guess I shouldn't have assumed that you had some logic to auto-name them then...

No, I was updating from the last 2.2.x release and had been using it with that version shortly before the update.

Hrm, that 2.2.x app is entirely gone now...  Hmm.  Hmm. Hmm.

**Comment by dmarmor** [comment]
Yikes, if you don't have a backup then I don't know if we'll be able to diagnose this.

The way it's supposed to work is that any app in the 2.2.x range that you've been using should already have its unique ID set, and on update the new app should pick up that same ID. Obviously that did not happen here, so it somehow created a new ID and started over, and it had to add the 628 because Name was already taken.

Here's a question: You don't have multiple copies of these apps kicking around on your system do you? This still shouldn't have happened, but that might at least explain some of what's going on.

**Comment by ylluminate** [comment]
Right. I may have noted somewhere that this was a semi-minor Epichrome app, so this is why I started there without a backup. I didn't want to lose it and felt it was worthwhile enough to resurrect it, but yeah... 

No, unless there's a backup it recognized on my backup volume, but I thought I had excluded it from Spotlight (but maybe that wasn't enough)...

Hmmm.  I guess we'll have to leave it alone for the time being and bring this back up if I can reproduce it.

**Comment by dmarmor** [comment]
Yeah, unless you could still recover the old 2.2.x version from the backup volume...?

But yeah, if you don't see this behavior again we might have to chalk it up to gremlins. If you're going to update more apps, I'd be grateful if you could back them up beforehand so we can try to capture weird stuff like this.

**Comment by ylluminate** [comment]
Yeah, I'm going to do that with a script that I run prior to each upgrade. Right now I'm basically going to follow this process before upgrading to Chromium:

1) Export Passwords via Chrome Settings
2) Screenshot of Extensions + verify they're bookmarked to an "extensions" Bookmarks Bar folder
3) Save session via Session Buddy with a dated session
4) Run backup script to preserve `/Applications/<EPICRHOME_APP>` & `~/Library/Application Support/Epichrome/Apps/<EPICHROME_APP>` to `~/tmp/Epichrome.backups/<EPICHROME_APP>/`

**Comment by dmarmor** [comment]
That looks great! The only thing to be sure of is not to run that backup script until you've quit the app (I don't know Session Buddy so don't know if that save happens while the app is running or not). This is just because if you compress the app while it's running it'll be huge...

**Comment by ylluminate** [comment]
Yes, Session Buddy runs as an extension and saves data as an extension and therefore it comes back to life when added after the upgrade / switchover so that we don't lose a beat (I leave Epichrome instances often with all tabs / windows open so I can quickly resume tasks and workflows).

And yes, while app is not running for backup.

**Comment by ylluminate** [comment]
Also, as I noted elsewhere, I'm now also having the Chromium missing sessions / no saved passwords issues... so I'm going to hold off on upgrading any more Epichrome apps until we know we've got this sorted out.
