### ISSUE TITLE
Catalina LSD crashes

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#197]
Something new I've noticed with Catalina is that it appears as though when I create a new Epichrome app that some time in the near term afterwards (minutes to an hour perhaps) that LSD crashes and then my entire system becomes unusable and requires `sudo reboot`. It seems to be when I create one that is recognized as a browser by the system.

**Comment by dmarmor** [comment]
Hmm. I've not experienced this myself, and I've created dozens of apps as I've been working on the new verison. Do you have a sense of whether it's to do with running the new app? Or is just creating it enough?

**Comment by ylluminate** [comment]
I'm not entirely sure. It happened with the previous version of Epichrome.  Apple is remaining silent on the issue right now, but the odd thing is that it just dawned on me last night that the crash (and subsequent system devastation / `sudo sync; sudo reboot -qn`) and previous crashes were extremely coincidental to creating a new Epichrome app.  SO, I'm not yet sure how to properly isolate this...

**Comment by ylluminate** [comment]
By the way, I have a feeling that the other issue I created has more to do with the root cause of this if it even is involved with Epichrome:
https://github.com/dmarmor/epichrome/issues/199

So I'll close this for now.

**Comment by dmarmor** [comment]
Cool. If we fix 199 but this crops up again we can reopen.

**Comment by ylluminate** [comment]
Right, somehow #199 encapsulates / demonstrates / expresses this I believe.
