### ISSUE TITLE
Most Epichrome apps gone in Browser Fairy now

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#199]
I hadn't needed to get into Browser Fairy until just today since my upgrade to Catalina, but when I got in there, I found what appears to be a disaster.  Most of my rules are now set to "not found" in the Browser column.

I then clicked on the "Open all other links with:" dropdown and found that only a few Epichrome apps are present! Same for creating new rules or changing the browser on an existing rule.  It's as though they no longer exist.

I thought I'd use Onyx to rebuild my LS database, but still no luck after reboot.

Getting very concerned here and wondering if various other hanging issues I'm having with browsers may have something to do with this peculiarity...

FYI, I've also upgraded only a few Epichrome apps to the 2.3.0 beta at this point because I'm trying to upgrade them to Chromium and moving them to my `~/Applications/Epichrome/` folder in order to organize things better and wanting to make sure things are safe and extensions are stored in a convenient folder, etc. for each upgrade... however I'm not even seeing these ones I've upgraded thus far in Browser Fairy...

Any thoughts?

**Comment by dmarmor** [comment]
This is totally mysterious to me. As you know, I use Browser Fairy extensively myself, and all my upgraded apps have appeared just fine. Are you seeing only your upgraded apps disappearing from Browser Fairy, or are your old un-upgraded ones gone too? If the latter, then I think something else must be going on (since the beta can't be harming apps that haven't even been updated).

If it's only your updated ones that are vanishing, let me know, because then we'll need to look inside a couple and see what's going on...

**Comment by ylluminate** [comment]
Right - I know you also use Browser Fairy.  So no, MOST (nearly all) of my Epichrome apps have disappeared from it.  Even Google Chrome appears to be not showing up properly (although Browser Fairy opens Chrome up still).  This MUST be a Catalina issue in losing these apps, but I don't know how to resolve it.  I tried to rebuild the LS database in Onyx, but that didn't help.  I suspect there must be more drastic measures, but I'm not sure *what* yet...

**Comment by dmarmor** [comment]
Yeah, this doesn't sound Epichrome-related to me. A first test you may or may not have already tried would be to look at System Preferences->General and check the drop-down menu for Default web browser. Your apps (and Chrome and such) should appear there.

If they do, then the problem might be with Browser Fairy itself. But if, as I suspect, they do not, then I think you're right that something bad might've happened to your LS database. The last time I needed to fix mine, I used the terminal commands described here:

https://eclecticlight.co/2017/08/11/launch-services-database-problems-correcting-and-rebuilding/

I think the only one I ended up needing was this:

```bash
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -v -apps u
```

I do remember that it took quite a while for it to rebuild properly and in the meantime icons were missing and things were wonky. Might be a good thing to try last thing at night and then let it churn away overnight.

If you do try that, let me know if it fixes your Browser Fairy problems.

**Comment by ylluminate** [comment]
Man, thats right. I forgot that Apple added that into the System Preferences vs having to use Safari still for default browser. 

So no, they don't appear there - NEITHER does even just "Google Chrome"!

Yes, I'd hoped that Onyx was essentially doing that command, but I'll give this a try tonight:
`lsregister -kill -r -v -apps u`

I did try this a week ago and it didn't do anything for me:
`lsregister -kill -r -domain u -domain s -domain l -v -seed`

**Comment by dmarmor** [comment]
Yeah, give that a try and see if it helps. If the initial command doesn't work, check that URL I linked to, because they had some further commands to try.

**Comment by ylluminate** [comment]
So a lot of browsers came back after issuing the `-kill -r -v -apps u` args, but most Epichrome apps are still gone. `Google Chrome` did show up again... lol.

**Comment by ylluminate** [comment]
Sadly even after running:
`/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -v -all u,s,l`

I'm still missing a large number of Epichrome apps. 

I really don't know where to go from here now.

**Comment by ylluminate** [comment]
This seemed to help to capture a little more, but not nearly all:
`/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user`

At this point I think I may have to resort to this updated info:
https://eclecticlight.co/2019/03/25/lsregister-a-valuable-undocumented-command-for-launchservices/

Register app:
`/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -R -f <PATH_TO_APP+NAME_OF_APP>`

Unregister app:
`/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -R -f -u <PATH_TO_APP+NAME_OF_APP>`

**Comment by ylluminate** [comment]
So I've tried a few more things:

- `lsregister -delete`
- `lsregister -seed`
- `lsregister -r -v -all u,s,l`

Still no real luck in getting all of my browsers to show up in `System Preferences > General` or in Browser Fairy. Not even `Google Chrome.app` is showing up again!

Oddly when I do a `lsregister -dump` I do see it though:
```
--------------------------------------------------------------------------------
bundle id:          Chrome (0x2898)
class:              kLSBundleClassApplication (0x2)
container:          / (0x4)
mount state:        mounted
Mach-O UUIDs:       BE445BC3-9181-3F43-9EAB-CFCAE548FACE
sequenceNum:        10392
path:               /Applications/Google Chrome.app (0x2dd8)
directory:          /Applications
name:               Chrome
displayName:        Google Chrome
...
```

So it seems as though it is registered, but what the heck.....

**Comment by dmarmor** [comment]
Yeah, I have no idea what could be going on here, but this definitely doesn't seem Epichrome-related. I'm afraid something bad has happened to your launch services database...

**Comment by ylluminate** [comment]
It appears as though it has and that there's simply no way to fully recover from it presently. Apple is mum on it right now. I'm hoping that the Browser Fairy dev will add the ability to add browsers that aren't showing up normally via a drag and drop function that is not generally available to the public (since they don't want to have to support strange configurations of users who really aren't advanced enough to deal with exceptional situations).

**Comment by dmarmor** [comment]
Sorry to hear it. Keep us posted if you figure out a way to resolve it (or of course if you determine that Epichrome is in any way involved).

**Comment by ylluminate** [comment]
FYI, I'm still working on this... No info from Apple. One thing that has crossed my mind is if Apple has some kind of a "max number of browsers" threshold where they stop enumerating or showing browsers after some count or the LSD mechanisms go into an "undefined" state where it triggers this... 

I guess I need to try to figure out if there's a way to get app type out of the LS database that would allow me to see what's going on better and count things and then perhaps even archive all Epichrome apps to see if the system somehow regains sanity...

Anyway, this is something I've been thinking about and just need to nail down a little time to further troubleshoot and wanted to write down my thoughts.

**Comment by dmarmor** [comment]
Thanks for the update. Yeah, it's possible Apple didn't ever consider the possibility of that many browsers, and there's some kind of fail in terms of registering them.

One way that I _think_ would work to see if the LSD is actually registering all these as browsers would be to search the output of ```lsregister -dump``` for ```handles-file-url``` which should appear in the ```bundle flags``` for any browsers (at least on my system it does for all Chromium-based browsers, all Epichrome apps registered as browsers, Firefox, and Safari). If that flag isn't showing up in the dump for your known browsers, then something has definitely gone wrong with LSD on your system...

**Comment by dmarmor** [comment]
Haven't heard anything on this for a while, so closing the issue, but if you're still having trouble and want to keep working on it, always happy to reopen!
