### ISSUE TITLE
Password Import missing temporarily...

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#200]
So here's an important issue going on with current versions of Chrome + Chromium. 

When you decide to move to Chromium you're going to have a problem importing an exportation of your passwords.  Obviously it's a pretty darn good idea to save your passwords via the exportation function since they will not be retained in the move (probably need to tell folks about this with a red alert).

However, importation is broken and will be fixed apparently in the next release and this includes a temporary work around (for Windows):
https://support.google.com/chrome/thread/18366464?hl=en

Obviously this needs to be incorporated into the command to start it on macOS... Do you think it might be a good temporary idea to just push this into all Epichrome apps for the time being when generating the updated version via Epichrome?

**Comment by dmarmor** [comment]
Thanks for the heads-up! I never use the Chrome/ium password storage, so never noticed this. I'll include a warning on the next beta, and will check to see if that flag is needed for importation. If it is, I'll add it.

**Comment by dmarmor** [comment]
This has been fixed in 2.3.0, so closing this issue. If you run into problems, please let me know and I'll reopen.
