### ISSUE TITLE
Won't upgrade on b7

### ISSUE THREAD

**Issue by GrogHills** [dmarmor/epichrome#204]
I installed beta 7. I'm prompted to upgrade on launching my app. I press upgrade. Nothing happens. I've tried this on all my apps. I can launch it again and select later and the app runs, but without the update.

**Comment by dmarmor** [comment]
What version are you upgrading from, and if it's 2.3.0bX, are the apps Chromium or Chrome engine?

Directly after one of the failed upgrades, can you send me the epichrome_app_log.txt file from that app's folder in ```~/Library/Application Support/Epichrome/Apps/<AppID>```? (Please be sure not to run the app a second time clicking the Later button, or it will overwrite the log.) Thanks!

**Comment by GrogHills** [comment]
Here is the log file you requested...
[epichrome_app_log.txt](https://github.com/dmarmor/epichrome/files/4253680/epichrome_app_log.txt)

The apps are Chromium and I have the beta installed, but I'm not sure what version. I know I didn't install the last one.

**Comment by dmarmor** [comment]
Thanks for the help on this, @GrogHills. I've isolated the problem, now just have to figure out how to fix it...

**Comment by dmarmor** [comment]
I've fixed the problem, but as it's specific to updating from beta 6, I'm going to use the fix as an opportunity to implement and test my solution for switching engines from Chrome to Brave (as beta 6 uses Chrome rather than Chromium as its internal engine). So it's going to take me a little time to get the new beta out. Thanks for your patience!

**Comment by dmarmor** [comment]
Give beta 8 a try and see if it helps.

**Comment by dmarmor** [comment]
I believe this got resolved with beta 8. As I mentioned on Patreon, you'll definitely need to update any remaining beta 6 apps to beta 10 *before* updating them to the final 2.3.0 release. That version will not be able to update beta 6 apps. What a horrorshow that beta 6 was...
