### ISSUE TITLE
Really liking Brave

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#205]
So the move to Brave has seemed nice. If we could get a flag to manually set, I'd like to try migrating some more apps at this point to Brave to see how it goes.

**Comment by dmarmor** [comment]
That's great, I'm glad Brave is working well so far. It's been pretty flawless on my system too.

Can you elaborate a bit on what you mean by getting a flag to set manually? Do you mean a way to migrate apps from the external Chrome engine to the built-in Brave one?

**Comment by ylluminate** [comment]
Well I know we don't want folks to be generally cross upgrading yet as per our discussion and the level of preparedness that is needed to migrate in the first place... So I was thinking maybe modifying a variable somewhere in `/Applications/Epichrome/Epichrome.app/Contents/Resources/Scripts/` or another config file to allow us to go ahead and get the prompt to migrate over when getting the upgrade prompt as before for Chromium.

**Comment by dmarmor** [comment]
OK, got it. Yeah, I can probably do something suitably arcane like adding a flag you have to set in config.sh or something. I'm not going to enable that until I figure out some way to migrate extensions from Chrome to Brave, which is proving to be tricky. I considered adding all current extensions to the ```External Extensions``` folder, but then you end up with a system where if they get deleted from that folder they disappear from the app.

My current thought is that on the first run after the update, the app would open a bunch of extra tabs each one with the Chrome Web Store page for an extension. That way the user could just click Add To Brave for each one and get them back. A bit of work to be sure, but that way they'd just be in the app without being tied to the ```External Extensions``` folder.

Would that be a workable solution for you?

**Comment by ylluminate** [comment]
Right.  

Actually that sounds like a good idea re: extensions. I have mine bookmarked generally per app, but that's really workable for folks who don't.

**Comment by ylluminate** [comment]
Oh, FYI, just thought this would be useful to trigger by default: https://community.brave.com/t/hiding-showing-brave-rewards-button-from-shell/109793

**Comment by dmarmor** [comment]
That would be very good. In the link you sent, I couldn't see that you'd gotten an answer to how to do it, though. If there's not a command-line flag, then it'll have to wait for a future plan I have to use a master prefs file to set initial sane prefs for new apps...

**Comment by ylluminate** [comment]
Right, no answer yet - just wanted you to be aware. Nice idea re: sane master prefs.

**Comment by dmarmor** [comment]
I managed to find the setting and the Brave rewards button is now hidden by default in new apps. You'll still have to turn it off manually from Brave settings page on older beta apps. Closing this for now, but ready to reopen if needed.
