### ISSUE TITLE
Deregistering Epichrome apps as system browsers?

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#206]
It occurred to me that perhaps I should try to de-register many of my Epichrome apps as web browsers to see if it would affect the problem I'm having with LSD.  

What's the current registration process that Epichrome follows when setting an app as a browser?

**Comment by dmarmor** [comment]
Currently it would be rather a pain to try to deregister an app. It would require making changes to the Info.plist by hand, which I don't recommend. If you really want to give it a try let me know and I'll talk you through it offline, but otherwise I'd recommend instead trying to recreate the apps taking care they keep the same ID (and thus reconnect to the same data folder). I do have it on my to-do list to make apps editable...

**Comment by ylluminate** [comment]
Thanks, I would like to know when you do have a chance. I do want to try a couple things here in an attempt to restore sanity.

**Comment by ylluminate** [comment]
@dmarmor did you per chance ever document this process? I've been poking around trying to find the option(s) or settings to change, but not much luck (well, confidence) so far. I was thinking we had a discussion about this, but this issue has been the only thing that's popped up so far...

**Comment by dmarmor** [comment]
I didn't document it as such, but it's one of the core settings in an Epichrome app, so the way to change it would be to edit your app (either by dropping the app onto `Epichrome.app` or running Epichrome and choosing the `Edit` option on the first dialog). Then you can just change the setting when it gets to the "Register as Browser" dialog.

**Comment by ylluminate** [comment]
Oh yeah! That totally slipped my mind, good call thanks.  So I did do that with an app and then diff'd the directories and it appears that there are the following differences:
In `APPBUNDLE/Contents/Info.plist` the following is present when it is registered as a browser (and gone if not):
```
	...
	<string>2.4.27</string>
	<key>CFBundleSignature</key>
	<string>????</string>
######## END COMMON ################################################################
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>Web site URL</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>http</string>
				<string>https</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleURLName</key>
			<string>FTP site URL</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>ftp</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleURLName</key>
			<string>Local file URL</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>file</string>
			</array>
		</dict>
	</array>
######## BEGIN COMMON #############################################################
	<key>CFBundleVersion</key>
	<string>204027.100.1</string>
	<key>LSArchitecturePriority</key>
        ...
```

And in `APPBUNDLE/Contents/Resources/Scripts/main.sh`, the following were updated by the update process:
```
...
BEFORE EDIT: SSBRegisterBrowser=''
AFTER EDIT: SSBRegisterBrowser='No'
...
BEFORE EDIT: SSBBackupData=''
AFTER EDIT: SSBBackupData='No'

BEFORE EDIT: SSBSkipWelcome=''
AFTER EDIT: SSBSkipWelcome='No'
...
BEFORE EDITSSBEdited=''
AFTER EDIT: SSBEdited='20220411194958'
...
```

So to do it manually one simply needs to remove the `CFBundleURLTypes` section from the `Info.plist` and change `main.sh`'s `SSBRegisterBrowser` to `No` it would seem.

Thanks so much!

**Comment by dmarmor** [comment]
Yeah, to confirm, I think those two things are all you'd need to change.
