### ISSUE TITLE
Instructions for Helper extension should not be chrome-specific

### ISSUE THREAD

**Issue by jonathanpberger** [dmarmor/epichrome#209]
CURRENT: Now that we're in a Brave new world (hah!), the instructions don't apply.
DESIRED: The `welcome.html` should include instructions for the Brave (or Chromium) browser.

file:///Applications/Fractal.app/Contents/Resources/FirstRun/welcome.html

**Comment by dmarmor** [comment]
Funny you should mention this! One of the big changes in beta 9 (posting today or tomorrow) is a completely rewritten welcome page that is much more informative and specific to each app. Check it out and let me know your thoughts!

**Comment by dmarmor** [comment]
Closing this for now!
