### ISSUE TITLE
Epichrome fails to create browser in /Applications from a non-admin account

### ISSUE THREAD

**Issue by Zettt** [dmarmor/epichrome#21]
I've tried to create a SSB for Trello with a non-admin account and it failed to write the app. I presume it's got something to do with permissions, because the dialog to ask if the script can write to something outside $HOME didn't come up.

**Comment by dmarmor** [comment]
I'm looking into how/if I can run the app creation with admin privileges from a non-admin account. No guarantees, but I'll keep you posted here if I figure out how to make it work. Thanks for the feedback!

**Comment by dmarmor** [comment]
Hi @Zettt,

I've just posted version 2.1.5 which should now allow you to create SSBs anywhere on your system even with a non-admin account. If Epichrome doesn't have permission to create an SSB in a given folder (/Applications, for instance), it'll prompt you to enter admin credentials.

Hope that helps! Let me know how it works for you.

Cheers,
  Dave

**Comment by Zettt** [comment]
@dmarmor Works for me. Thanks!
