### ISSUE TITLE
Choosy won't send the URL to the SSB if already open

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#210]
Currently on Catalina and Epichrome 2.2.4

When i choose in Choosy the SSB to open the URL in, *and* that SSB is already open, then nothing would happen. If that SSB is *not* open, then it will correctly send the URL to that SSB (that will open it).

I already described a similar problem (#174) as i was on El Capitan. Updating to Mojave solved the problem for some of my SSBs. I can't find the comment i did on that behavior anymore. Briefly: when choosing a SSB on choosy, with some SSBs (not always the same!) and *sometimes* (!) instead of opening the link in that SSB, a news icon of that SSB would "jump" in the dock and then disappear again. I found out that it had to do with the fact that sometimes the app started from the /Applications folder, sometimes from ~/Library/Application Support/Epichrome/[Name of the SSB]/[Some subfolder here, i forgot which]. 

However: no on Catalina, i'm back to a similar situation on El Capitan.
Choosy works correctly on that issue with Chrome, Chromium, Chrome Canary, Ghost Browser, Brave, Safari, Firefox, Opera.

I have some hope that the version 2.3.0 will fix that as i read on Patreon  about "fixes the way the engine launches". If not: i'm willing to help debugging but i would need some instructions...

And no: Browser Fairy is definitely not an option - i really integrated some main features of Choosy in my workflow that really boost my productivity....

**Comment by talleux** [comment]
Ah! i just better read #208 and i thing my issue is at least related, probably exactly the same... In this case, sorry, just close my duplicated.

As i read there the problem is fixed in 2.3.0 so, just waiting... I didn't dare to test the betas in my productivity environment (using around 30 SSBs on a daily basis).

**Comment by dmarmor** [comment]
Yeah, this should be fixed in 2.3.0. If you have a chance, maybe you could create a test app in beta 9 and give it a try just to make sure it's all good on Choosy? For now, I'll close this issue, but if you run into any trouble, we can reopen.

**Comment by talleux** [comment]
fixed for me on 2.3.0 beta 9+10
