### ISSUE TITLE
Unlocking 1Password X with Brave engine single-page app

### ISSUE THREAD

**Issue by chrisminett** [dmarmor/epichrome#212]
I kept the Chrome engine during the betas as I prefer the traditional 1Password extension experience (native integration with desktop, single-unlocking, etc.), but when upgrading to the stable release, I switched my single-page apps to the Brave engine, as by nature I only need to put the user/pass in once and I thought 1Password X would satisfy that basic need!

The problem seems to be unlocking 1Password X in the first place! As it's a single-page app, I have the address bar disabled so the app is the full window. The 1Password icon appears in the login fields, but clicking it shows a prompt to unlock 1Password X by pressing Cmd+Shift+X. This key combination does nothing. If I right-click I can choose the Epichrome option to show the address bar, after which the shortcut _does_ work, as the extension icon is now visible next to the address bar and the 1Password login box can be shown as it is anchored to the extension icon.

The installer notes suggested 1Password X for the Brave engine, so I hope that you've come across this same issue and have an easy solution?

(This isn't a problem in the Chrome engine with the traditional 1Password extension, as the unlock dialog is anchored to the 1Password menubar icon, so it doesn't matter that the Chrome extension icon isn't visible.)

**Comment by dmarmor** [comment]
Yeah, I've noticed this myself with app-style windows. It's not something I can control, as that shortcut is either captured or not by 1PasswordX. I'm not sure why it doesn't pick up the shortcut when the front window is app-style, and probably the only solution there would be to put in a bug report with AgileBits and ask them to fix that.

Meantime, the workaround I use myself is to quickly convert the window to tab-style with Epichrome's built-in shortcut, Cmd-Shift-L. then unlock 1PasswordX, then convert back to app-style with the same Cmd-Shift-L shortcut. Not ideal, I know, but it should get the job done.

**Comment by chrisminett** [comment]
@dmarmor I'm not sure that it's a problem capturing the shortcut - I think it's because the window is anchored to the extension icon in the toolbar, and that's not visible on screen.

It may still be their issue that they need to handle when the icon isn't visible (if there's even a hook for that?), but I would expect a likely response would be they can't help it if the browser has been modified to hide the icon.

If you think this is still their issue I can report it to them - is there a correct term to use to explain when the address bar and extension icons are hidden? Is it a particular engine mode which I can refer them to investigate?

**Comment by dmarmor** [comment]
I mean, there has to be some workaround they could do, as the keyboard shortcut in my Epichrome Helper extension still works with app-style windows.

I think the way to reference it would be to tell them the keyboard shortcut doesn't work in app-style windows. Many different extensions and websites create windows like this (including Gmail when you pop out a composition window by shift-clicking the expand icon), and they can be invoked by running Chrome from the command-line using the --app flag. App windows are a supported use of the browser and not due to any modification, so hopefully they'll be able to support it. We'll see!

**Comment by chrisminett** [comment]
For anyone that stumbles across this, I've posted this to AgileBits at https://discussions.agilebits.com/discussion/113463/1password-x-keyboard-shortcut-doesnt-work-in-chrome-app-mode/

I'll update this issue if there's any useful response.

**Comment by dmarmor** [comment]
Thanks for posting that! It looks like someone on their team has noted it before and is reflagging it for the devs, so at least it's on their radar. I posted a reply as well just to say I've experienced it too. Hopefully they'll get to it soon...
