### ISSUE TITLE
Epichrome 2.3.0 apps blocked as unsafe "threat" by anti virus software

### ISSUE THREAD

**Issue by crumley** [dmarmor/epichrome#213]
Not sure if this is an issue of an overzealous anti virus software configuration or preventable issue by Epichrome side... either way this may be useful to some who experiences the symptom and think Epichrome is broken.

**Symptom:** On first launch of an app created with Epichrome 2.3.0 it will appear to launch and never show up. Subsequent launches result in a Finder dialog with text: "App can not be launched". 

In the MacOS console I see the following message:

> Threat:Blocked path:/Applications/My Epichrome App.app/Contents/MacOS/Epichrome score:-100 running:False, SHA:6F551940380E2A4D4DB3C9B25E85EF9D3C7628DBB60994B0EC066024CD355D45

So far I've tried using both Brave and Chrome options when creating the app with the same result.

**Comment by dmarmor** [comment]
Interesting. I've not seen this before. Can you send me a little more info on your setup (feel free to message me if you don't want to post details here):

1. What version of macOS are you running?
2. Do you have any third-party anti-virus software installed?
3. Could you send me a screenshot or rundown of your settings under ```System Preferences>Security & Privacy>Firewall``` and also the ```General``` pane (specifically the "Allow apps downloaded from" setting).

Thanks!

**Comment by crumley** [comment]
1. Catalina 10.15.4
2. `Cylance` is the AV software that is logging `Threat:Blocked`. _(I meant to include this in the original post, doh!)_
3a. Firewall is ON and blocking all incoming connections. 
3b. "Allow apps downloaded from: App Store and Identified Developers"

**Comment by dmarmor** [comment]
I'm not familiar with Cylance, but I suspect what's happening is that it refuses to run any app that is not signed. As Epichrome apps are created on the fly on your system, they are not signed. The built-in Mac Gatekeeper doesn't have a problem with this as they were not downloaded from elsewhere, but it seems like Cylance does.

My best recommendation would be to look through the settings for Cylance and see if there's a way to relax its security around codesigned apps. Otherwise, it might just be a situation where Epichrome and Cylance are incompatible.

Please let us know what you find either way, as it could be useful for other users with AV software installed.

**Comment by jwalker343** [comment]
Also have this problem with Cisco Amp 4 Endpoints after updating to 2.3.1 today.
![Screen Shot 2020-05-21 at 9 08 09 AM](https://user-images.githubusercontent.com/15674935/82562101-9baa5680-9b42-11ea-92b1-d435736a1b0e.png)

I get Threat: 'Win.Trojan.pistacchietto', I googled around and it looks like it may be linked to a false positive on apps using Platypus.

**Comment by dmarmor** [comment]
Ah, I see. This could potentially be troublesome for people with AV software for a while, then. I do have it on my long-term roadmap to get away from Platypus, but that's not going to be able to happen anytime soon.

In the meantime, the best bet might be to see if there are exclusions you can set in the AV software so it won't quarantine your Epichrome apps. Meantime, I'll look around at the false positive issue and see if there's any more general solution I can do with Platypus.

**Comment by dmarmor** [comment]
OK, I found a way (I think) to codesign the Platypus executable. Would you give [**this beta**](https://www.dropbox.com/s/74gygka2dsw0rvp/epichrome-2.3.2b1.pkg?dl=0) a try and see if it passes your AV software?

**Comment by crumley** [comment]
👏 -- Worked for me with Cylance.

**Comment by dmarmor** [comment]
That's great! It'll be signed going forward, so hopefully no more AV problems. Thank you both for the reports.

**Comment by jwalker343** [comment]
👏 -- Worked for me with Cisco AMP 4 Endpoints.

**Comment by dmarmor** [comment]
Excellent! I'm going to be releasing 2.3.2 in the next day or two and this fix will be in there. Thanks for finding this issue!

**Comment by dmarmor** [comment]
Version 2.3.2 is released with this fix, so I'm closing this issue. If any problems arise with 2.3.2, please let me know and we can reopen.
