### ISSUE TITLE
microphone not accessible for Google Voice and Hangouts

### ISSUE THREAD

**Issue by gregschroeder** [dmarmor/epichrome#216]
I've made new SSBs for Google Voice and Hangouts with 2.3.0 on Catalina latest, choosing the Brave option for both, and they say that they cannot access the microphone.

I clicked 'Allow' and brave://settings/content/microphone?search=mic reflects the correct status, with https://voice.google.com:443 in the Allow block.

But, attempting to use it gives:

```
Allow mic access
In your browser settings, allow Voice to access your microphone

```

**Comment by dmarmor** [comment]
When you first clicked the Allow button in the app, did you get a macOS dialog asking you to give the app permission? It would've looked something like this:

<img width="532" alt="mic_permission" src="https://user-images.githubusercontent.com/3878113/81994944-dae61e00-95fd-11ea-8162-c0eebb0ec08e.png">

Sometimes that dialog takes several seconds to appear, so it's possible if you switched away from your app at the wrong moment or something, you could've missed it.

Anyway, if you didn't see the dialog, then for some reason Brave didn't request access from the system. If that's the case, you could try quitting the app and resetting the system mic permissions (you'll then need to give mic access back to each app you use it in the next time you run them). You can do it from the terminal like this:

```bash
tccutil reset Microphone
```

Then run the app again, make a call (or do anything that accesses the mic) and wait a few seconds, and the dialog should appear.

If, on the other hand, you *did* see that dialog, and clicked "OK" and you still don't have microphone access, then I'm not sure what's going on. If that's the case, let me know and we can try some other steps to diagnose the problem.

**Comment by gregschroeder** [comment]
well.. interesting - i did the tccutil reset, and then ran one of the apps (Hangouts), and it worked.

then i tried the Google Voice one, and it didn't.  i have tried repeated tccutil reset attempts, no change.

Hangouts SSB works, Voice one doesn't.  'allow voice' is prompted and accepted in the browser, and the brave://settings shows it enabled, but it still claims to need access.

I suspect this will get fixed with the same fix for the Keychain/session/local storage fix.

Thanks for being so responsive.

**Comment by dmarmor** [comment]
Hmm! Very very weird that it would work on one app and not the other. If it's not too much of a pain, I'd be curious to see if it would make any difference if you reset the permissions and then ran the Voice app first?

And yes, this seems like it might well be related to the keychain problem (issue #215 for reference for those following along). Something is going awry with these apps requesting system resources. I'll have more to say on that issue over there.

**Comment by dmarmor** [comment]
I'm hoping closing this means it got resolved. If so, I'm curious, did you do anything particular, or did it resolve itself somehow?
