### ISSUE TITLE
Update to Chrome 83.0.4103.61 prevents Chrome-based SSBs from opening

### ISSUE THREAD

**Issue by knoxilla** [dmarmor/epichrome#225]
My last version of Chrome was 81.0.4044.138 and all as well with legacy Chrome-based SSBs!

In fact, I had not yet updated to Epichrome 2.3.0 or 2.3.1 - this happened _before_ that, while I was still using Epichrome 2.2.4. 

I updated this morning to Chrome 83.0.4103.61 and none of that apps will open! They pop upon for a blip and die.  Checking the Console, I see this:

internal_TCCCreateDesignatedRequirementIdentityFromMessage: **Refusing TCCCreateDesignatedRequirementIdentityFromAuditToken (kTCCServiceAppleEvents)** RESP:{ID: com.apple.sh, PID[86353], auid: 501, euid: 501, responsible path: '/Users/foo/PathToSSB.app/Contents/MacOS/Epichrome', binary path: '/bin/sh'}, ACC:{ID: com.apple.osascript, PID[86383], auid: 501, euid: 501, binary path: '/usr/bin/osascript'}, REQ:{ID: com.apple.appleeventsd, PID[72], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}: unable to compute designated requirement for: file:///Users/foo/PathToSSB.app/Contents/MacOS/Epichrome.,...

After installing the 2.3.1 version of Epichrome, I get the same result on opening (console log) but then Epichrome_also_ pops a dialog saying:

    Unable to update app to new version of Google Chrome. (Error filtering Info.plist file. (ascii)) It may or may not run properly.

So there seem to be two things going  on here...  The signature failure _and_ the plist fail. 

I can see that is is related to issue #215 , but am not sure how.  At least I can give you a sequence that separates things a bit.

**Comment by dmarmor** [comment]
Thanks for reporting this. I think this is actually related to some of the problems described in issue #218 and may be a problem with the new version of Chrome. I'll look into it. I'm going to close the other issue and we'll handle the conversation through this one.

**Comment by knoxilla** [comment]
For the record, I love Epichrome!  Thanks so much for what you do.  It really changed the way I work and makes it so much easier to juggle projects, identies (work versus personal) and more.

**Comment by emanaku** [comment]
Hi, I have the same problem. I use 20+ Epichrome apps - none of them start anymore since upgrade of Chrome to 83. I did NOT update Epichrome to 2.3.1
From a time machine I reinstalled an older Chrome version 81, then my apps work, but I cannot switch off the automatic update of Chrome - so after a day (or a couple of hours) all my apps are rendered useless right now. 
A quick solution would be very much appreciated - I really love the Epichrome generated apps!!!

**Comment by dmarmor** [comment]
OK, the good news is this appears to _only_ be a problem in Epichrome 2.2.4. Looks like I released 2.3.0 just in the nick of time. So @emanaku and @bendehghan, I would recommend updating a test app to 2.3.1 and then see if the problem goes away.

@knoxilla, it appears to me that the app you thought you updated to 2.3.1 didn't actually update. The error message you saw (```Unable to update app to new version of Google Chrome. (Error filtering Info.plist file. (ascii)) It may or may not run properly.```) uses different wording in 2.3.1, so that message had to have been generated by a 2.2.4 app.

Can you double-check that, try updating a test app to 2.3.1 and report back how it goes?

**Comment by bendehghan** [comment]
I have 2.3.1 but when I open a 2.2.4 app I get the error message to download 2.3.1. There is no update option, only download, later, or ignore. Later or ignore get me 

> Unable to update app to new version of Google Chrome. (Error filtering Info.plist file. (ascii)) It may or may not run properly.

Then a log or quit option. So the problem is as it was before.

**Comment by emanaku** [comment]
Hi, @bendehghan , this happened to me, too. 2.3.1 comes with some instructions how to do the update. I don't know a link to these instructions, so I am copying the part about the update with switching to Brave here. Following these instructions made all apps I tried to switch usable without problems.

_"HOW_ TO SWITCH
1. Prepare the app:
• If you have saved passwords, the switch will cause you to lose them. Here’s how to export them: Open Settings ( ⌘-, ) then click Passwords under the Autofill header (you can use ⌘-F and type “passwords” to find it quickly). Click the little button menu to the right of the Saved Passwords header (it looks like ... turned sideways), and choose Export passwords....
• The switch will also cause you to lose any extensions you have installed. It will create a list of the lost extensions with easy links to reinstall them, and most extensions will retain their settings. But some seem to lose them, so take note of your installed extensions and if any of them offer the ability to export settings, do that now.
 
• The switch will log you out of any websites you were logged into, so you’ll need to save any information or do whatever you need to prepare for that.
2. Update the app. You need to run the app with the environment variable SSBAllowEngineSwitch set. The simplest way to do this is to run the app from the terminal like this:
    SSBAllowEngineSwitch=1 open <App Name>.app
When you click the Update button, another dialog will pop up allowing you to choose which engine you want. Click Built-in (Brave) and you should be on your _way."_

Good luck!

**Comment by emanaku** [comment]
Hi, @bendehghan , I see, what you mean: When I try the procedure as I described in my former answer with Chrome 83 installed, it does NOT work - exactly like you wrote.
So I downgraded Chrome to 81 - then I can "switch" or update all my apps. Afterwards I plan to upgrade Chrome to 83. I do no longer use Chrome for the apps - only Brave.

**Comment by dmarmor** [comment]
Hi @bendehghan, the message to download 2.3.1 is not an error. That's just telling you there's a new version on GitHub. You should click Download (or just go to the Releases page here) and download the package, then install it on your system. Once you do that, the next time you run each app, it should offer to update to 2.3.1. I've tested this with 2.2.4 and even if they've updated to Chrome 83 and are unable to run, if you run them with 2.3.1 installed on your system, they will update properly, and then they should run fine.

**Comment by dmarmor** [comment]
Hi @bendehghan & @emanaku, if you're still having trouble updating to 2.3.1, there's a related issue #228 with more info on that and you could see if it helps.

**Comment by emanaku** [comment]
Thank you, @bendehghan , I am good now. I updated all apps to 2.3.1 with Brave (as decribed above), and I am running Chrome 83. Everything is good - thank you all for this great work!

**Comment by dmarmor** [comment]
Excellent! Glad it's working for you.
