### ISSUE TITLE
Apps not working, still prompting to upgrade with 2.3.1 installed

### ISSUE THREAD

**Issue by asmod3us** [dmarmor/epichrome#228]
Hello,

I was running Epichrome 2.2.4 and my apps stopped working, possibly due to a newer Chrome version (83.0.4103.61). The apps would just silently quit when launched via Spotlight, but there was an error around Info.plist processing when I investigated running the app from the CLI. I no longer have the exact error message.

I updated to Epichrome 2.3.1 via homebrew:

```
❯ grep -A1 CFBundleShortVersionString /Applications/Epichrome/Epichrome.app/Contents/Info.plist
	<key>CFBundleShortVersionString</key>
	<string>2.3.1</string>
```

This changed the situation slightly:

- The app (Inoreader in my case) seems unaware of my upgraded Epichrome, still prompting me to upgrade Epichrome to 2.3.1.

- Proceeding to upgrade 'Later' yields a popup with:
`Unable to update app to new version of Google Chrome. (Error filtering Info.plist file. (ascii)) It may or may not run properly.` It doesn't run properly and presents another popup with title `Unable to Run` and no content. `View Log` takes me to a file at `~/Library/Application Support/Epichrome/Apps/Inoreader606/Logs`:

```
*[24650]Inoreader606(404)/updatessb(70)/{osascript}: Returned code 1 with no logged output.
*[24650]Inoreader606(404)/updatessb(70): FAILED
*[24650]Inoreader606(529)/alert(1440)/dialog(1391): Showing alert 'Warning' with text 'Unable to update app to new version of Google Chrome. (Error filtering Info.plist file. (ascii)) It may or may not run properly.'
![24650]Inoreader606(536)/abort(834): Aborting: 
```

How do I get the app working again?

**Comment by asmod3us** [comment]
Snippet from `~/Library/Application Support/Epichrome/epichrome.plist`:

```
...
	<key>updateCheckVersion</key>
	<string>2.2.4</string>
```

**Comment by henderea** [comment]
You should try installing directly with the installer and _not_ with homebrew. Homebrew doesn’t necessarily install apps properly, and I wouldn’t recommend sticking with it if it doesn’t seem to be working.

**Comment by Zettt** [comment]
I'm having the same issue. Tried running a different SSB after installing the non-homebrew version of Epichrome, which seemed to work. Sadly, the other apps, that I would like to use, still show the same ascii error.

**Comment by asmod3us** [comment]
Just to rule out homebrew installation I installed the pkg from the Releases tab directly. I still experience the issue.

**Comment by dmarmor** [comment]
Hey guys, this is discussed in issue #225. @asmod3us, unless I'm misunderstanding what you're saying, you just need to update your app to 2.3.1. Old 2.2.4 apps will not work with Chrome 83. When the app offers to update to 2.3.1, just click "Update" and it will do it.

**Comment by dmarmor** [comment]
Duplicate of #225

**Comment by asmod3us** [comment]
This is not solved, let me elaborate. I am unable to Update the app. The app does not recognize the installed version v2.3.1 of epichrome and keeps informing me of an "Update Available".

**Comment by asmod3us** [comment]
User Experience with 2.3.1 installed when launching an app that is on 2.2.4:

![Screenshot 2020-05-23 at 16 17 17](https://user-images.githubusercontent.com/450168/82732964-28e6da00-9d00-11ea-8884-0a9850b56114.png)

**Comment by henderea** [comment]
Where is the main epichrome.app installed? And if it’s a shortcut/symlink, can you please also list where that link points?  It’s possible that epichrome.app isn’t where the 2.2.4 apps are looking. Did you install for all users or just yourself when running the installer? Did you change the install location when installing?

**Comment by asmod3us** [comment]
It's at:

`drwxr-xr-x  3 root  wheel  96 May 23 16:07 /Applications/Epichrome/Epichrome.app`

and it's not a symlink. I ran the pkg installer with default options, which I've confirmed to be 'Install for all users'. I left the install location at default.

**Comment by asmod3us** [comment]
```
❯ [[ -L /Applications/Epichrome/Epichrome.app ]] || echo "not a symlink"
not a symlink
❯ [[ -L /Applications/Epichrome/ ]] || echo "not a symlink"
not a symlink
```

This:

`SSBAllowEngineSwitch=1 open -a APP`

is also not working for me. Still getting that Update Available popup.

**Comment by asmod3us** [comment]
I got the app to update with this procedure:

```
APP/Contents/MacOS
bash -x Epichrome
```

That triggered the update. There must be a difference to how the app launches via Spotlight?

**Comment by dmarmor** [comment]
I can't quite understand why it would not offer to update the app once 2.3.1 is installed. On my system it works fine with 2.2.4 apps. Do you have Spotlight turned off or not searching /Applications?

One possible workaround you could try is to try moving or trashing the 2.2.4 copy of Epichrome.app (which is most likely at /Applications/Epichrome.app. It might be that for some reason your system is getting confused and thinking that's the latest version (though I still can't see how that's possible unless Spotlight is turned off).

Worst case, if it's working for you to run it from the terminal, then continue doing that.

**Comment by asmod3us** [comment]
I don't quite get it either... Spotlight is on and indexing my volume and also /Applications. It locates Epichrome just fine:

```
❯ /usr/bin/mdfind  "kMDItemCFBundleIdentifier == 'org.epichrome.Epichrome'"
/Applications/Epichrome/Epichrome.app
```

There is only the 2.3.1 copy of Epichrome, there are no previous versions on my system.

**Comment by marnen** [comment]
Having the exact same situation, right down to being prompted to download Epichrome 2.3.1 even though I already installed it. Chrome 83 on Mojave. Please fix this...Epichrome rocks and I don't want to give it up!

**Comment by marnen** [comment]
The `bash -x Epichrome` trick worked for me, but I had some Chrome extensions installed in my Epichrome app and lost all my data for them. Where does Epichrome store extension user data?

**Comment by christefano** [comment]
For some reason on my system `bash -x Epichrome` didn’t work (iTerm 3.3.9 on Catalina 10.15.4), though `./Epichrome` did, and I was able to update to 2.3.1. (Thanks, @asmod3us!)

It’s worked for each Epichrome app I’ve done this for, and now I’m wondering how to switch from the external Chrome engine to the built-in Brave engine. Does anyone know if this is possible?

**Comment by dmarmor** [comment]
If you want to run Epichrome from the terminal, you need not use ```bash -x Epichrome```, but can directly invoke the executable from the terminal prompt:

```bash
<YourApp.app>/Contents/MacOS/Epichrome
```

My guess is this is some kind of Catalina security issue where your old app was not allowed to show the update dialog, but Terminal has sufficient permissions. I'd tried to code around in the update, but my guess is that on some systems it's not working. Running those apps from the terminal as shown above should work. If you're running into problems, please run the app with debug on as follows and send me the logs:

```bash
<YourApp.app>/Contents/MacOS/Epichrome --debug
```

@christefano: You can switch engines, but only on update, so if you've already updated those apps you won't now be able to switch the engine. I am working on a later update that will allow apps to be edited, so you'll be able to switch them later, just not at the moment. For any apps you haven't updated yet, try this from the terminal prompt:

```bash
SSBAllowEngineSwitch=1 <YourApp.app>/Contents/MacOS/Epichrome
```

@marnen: Regarding your problem with losing extension data, can you open a separate issue with as much info as you can give me (did you switch engines on update, any logs generated, etc.). I'd like to keep this issue focused on the inability to update 2.2.4 apps at all. Thanks!

**Comment by marnen** [comment]
@dmarmor:
> If you want to run Epichrome from the terminal, you need not use `bash -x Epichrome`, but can directly invoke the executable from the terminal prompt:
> 
> ```shell
> <YourApp.app>/Contents/MacOS/Epichrome
> ```
> 
> My guess is this is some kind of Catalina security issue where your old app was not allowed to show the update dialog, but Terminal has sufficient permissions.

For me, this happened on Mojave.

> I'd tried to code around in the update, but my guess is that on some systems it's not working. Running those apps from the terminal as shown above should work. If you're running into problems, please run the app with debug on as follows and send me the logs:
> 
> ```shell
> <YourApp.app>/Contents/MacOS/Epichrome --debug

I'll do this if I run into problems with any other Epichrome app.

> @marnen: Regarding your problem with losing extension data, can you open a separate issue with as much info as you can give me (did you switch engines on update, any logs generated, etc.). I'd like to keep this issue focused on the inability to update 2.2.4 apps at all. Thanks!

Sure.

**Comment by Zettt** [comment]
> If you're running into problems, please run the app with debug on as follows and send me the logs:
> 
> ```shell
> <YourApp.app>/Contents/MacOS/Epichrome --debug
> ```

Where are the logs saved?

**Comment by asmod3us** [comment]
> My guess is this is some kind of Catalina security issue where your old app was not allowed to show the update dialog, but Terminal has sufficient permissions.

Not sure if it's relevant, I'm also still on Mojave (10.14.6).

**Comment by christefano** [comment]
> You can switch engines, but only on update, so if you've already updated those apps you won't now be able to switch the engine. I am working on a later update that will allow apps to be edited, so you'll be able to switch them later, just not at the moment. 

Excellent! Although I have Time Machine backups, I think I will just wait for the future update. (In all honesty, I’m not sure where all the app data is saved even though I see a lot of stuff in `~/Library/Application Support/Epichrome` — is this documented anywhere?)

> For any apps you haven't updated yet, try this from the terminal prompt:
>
>> `SSBAllowEngineSwitch=1 <YourApp.app>/Contents/MacOS/Epichrome`

Is this done before or after executing it from the terminal and updating to 2.3.1?

**Comment by dmarmor** [comment]
@Zettt: On 2.2.4 the logs will just appear on stderr, so you'd need to copy paste from there, or collect them with something like:

```bash
<YourApp.app>/Contents/MacOS/Epichrome --debug > debuglog.txt 2>&1
```

@marnen & @asmod3us: It may have still been Mojave where I first saw the dialog permissions problem. In any event, it seems most likely that's the problem, and it does appear that running the executable directly from the terminal is allowing people to update.

@christefano: Each app's data is saved in its own directory: ```~/Library/Application Support/Epichrome/Apps/<YourAppID>```

The command I suggested doesn't happen before or after executing the app--it *is* the command you would use to run the app. The ```SSBAllowEngineSwitch=1``` prefix sets that variable in the app's environment, and then the second part (```<YourApp.app>/Contents/MacOS/Epichrome```) runs it.

**Comment by Zettt** [comment]
@dmarmor 
> @Zettt: On 2.2.4 the logs will just appear on stderr…
Thank you!

It's pretty much the same still. Here's my logs.

`/Applications/Coinigy\ Epichrome.app/Contents/MacOS/Epichrome --debug > ~/Desktop/debug.log 2>&1` gives the same output as `SSBAllowEngineSwitch=1 /Applications/Coinigy\ Epichrome.app/Contents/MacOS/Epichrome --debug > ~/Desktop/debug.log 2>&1`:

```
mcssbinfo (640):  found Epichrome instance at '/Applications/Epichrome/Epichrome.app'
mcssbinfo (640):  found Epichrome instance at '/Volumes/Calcifer - Data/Applications/Epichrome.app'
mcssbinfo (659):  latest Epichrome instance found: version 2.3.1 at '/Applications/Epichrome/Epichrome.app'
```

**Comment by dmarmor** [comment]
OK, so the logs you showed from running the app with ```--debug``` are what I'd have expected, and show that it'd definitely finding the 2.3.1 version. When you run it this way from the terminal, do you get the Update dialog and are you able to complete the update?

Regarding the other error message you found, thank you! It shouldn't affect any of this, but definitely a good thing to fix.

**Comment by Zettt** [comment]
> Regarding the other error message you found, thank you! It shouldn't affect any of this, but definitely a good thing to fix.

You're welcome.

> When you run it this way from the terminal, do you get the Update dialog and are you able to complete the update?
That's why I'm still posting here, I don't get the "switch" dialog, nor does the other app launch.

The app named "MindMeister" above does launch, and doesn't have any problem. However it doesn't show a "switch to Brave engine" dialog. The other app named Coinigy shows the "ascii" error mentioned above, followed by an empty dialog with an OK button.

**Comment by Zettt** [comment]
Maybe this is helpful for some of you. I found a way to get open tabs from the Current Tabs and Current Session files. The result is not pretty, but workable. Workable enough for me to delete affected SSB's who won't cooperate. (I'm keeping the ones we were talking about to help debugging.) 

→ https://github.com/JRBANCEL/Chromagnon/tree/SNSS

```
git clone https://github.com/JRBANCEL/Chromagnon.git
git pull origin SNSS
python chromagnonTab.py Current\ Tabs > ~/Desktop/currenttabs.txt
```

I hope this helps!

**Comment by dmarmor** [comment]
> The app named "MindMeister" above does launch, and doesn't have any problem. However it doesn't show a "switch to Brave engine" dialog.

My guess is that by the time you ran MindMeister with ```SSBAllowEngineSwitch``` set, it had already updated to 2.3.1. The engine switch will only happen on an update (I'm working on allowing apps to be edited, but it's a big task and not ready yet). If you want to switch engines on that app, be sure to use that switch the first time you run it after installing the next version of Epichrome (I'll hopefully be releasing 2.3.2 in a couple days).

> The other app named Coinigy shows the "ascii" error mentioned above, followed by an empty dialog with an OK button.

So it looks to me like Coiningy is still on 2.2.4 and still won't show the update dialog even when you directly execute it from the Terminal. I really can't understand why that is, but might have a workaround. I'm going to post a new beta here, hopefully later today that I'd love you to try. In the meantime, can you give me a little more information by confirming that you're able to display a dialog from the Terminal? I just need to know if this command pops up a dialog box:

```bash
osascript -e 'display dialog "Hello"'
```

Thanks!

**Comment by dmarmor** [comment]
OK, here's **[Epichrome 2.3.2b2](https://www.dropbox.com/s/mrj8akopb04vhep/epichrome-2.3.2b2.pkg?dl=0)**, a beta with an attempt to fix this problem. It *should* allow an update on those 2.2.4 apps that were failing with the Info.plist error and then never showing an update dialog.

_Note: Depending on your security settings and the permissions of your old app, you may see two update dialogs, or you may see none and the app will just automatically update. So please back up your old app before you attempt this update. If you see two dialogs, just click "Update" both times._

Please do let me know how it works for you! If this fixes the problem, I'd like to get the full release out ASAP to fix it for everyone.

**Comment by mclow** [comment]
This is definitely NOT a Mojave/Catalina-specific thing. I'm getting these "Error filtering Info.plist file" errors on El Capitan.

In Initial testing, Epichrome 2.3.2b2, appears to be working. Thanks!

**Comment by dmarmor** [comment]
Excellent! Glad to hear it's working thus far.

Yeah, I wasn't saying that the inability of 2.2.4 apps to run on Chrome 83 was a Mojave or Catalina problem. The problem is that starting with Mojave (I think, but possibly earlier), macOS clamped down on app security and it caused some 2.2.4 apps to not be able to reliably display the update dialog box. I tried to work around that in 2.3.0 but there was an edge case that this Chrome 83 problem hit, and so the apps were not able to run, and also not able to update. 2.3.2b2 is an attempt to fix that edge case.

**Comment by Zettt** [comment]
I can confirm that the beta is working. 

<img width="530" alt="Screen Shot 2020-05-31 at 06 25 35" src="https://user-images.githubusercontent.com/42497/83344471-aa91c580-a307-11ea-860d-4f232daa7d79.png">

> (I'm working on allowing apps to be edited, but it's a big task and not ready yet)

That would be great, but I believe it's a low priority task.

**Comment by dmarmor** [comment]
Thanks, @Zettt . Seems like it's working so I've just 2.3.2 with this fix. Closing this issue for now, but if this problem crops up for anybody with 2.3.2, let me know and we can reopen.

**Comment by urb4nc4rl** [comment]
I am getting this issue again on 2.3.3

STR:
- Launch epichrome
- Step through options (choose defaults for everything, including custom icon)

Observed:
Error dialog appears:  "Creation failed: Error filtering Info.plist file. (ascii)"

![Screenshot 2020-06-22 at 11 49 57](https://user-images.githubusercontent.com/65182227/85279570-8e082980-b47e-11ea-8a8b-22faa7cb9478.png)
![Screenshot 2020-06-22 at 11 50 05](https://user-images.githubusercontent.com/65182227/85279574-8fd1ed00-b47e-11ea-9244-95c1d2de2e85.png)

**Comment by dmarmor** [comment]
That's not 2.3.3. It looks like you've accidentally run 2.2.4 instead. Since 2.3.0, Epichrome is installed in `/Applications/Epichrome/Epichrome.app` rather than `/Applications/Epichrome.app`. Given that 2.2.4 no longer seems to work since the latest Chrome update, I'd recommend deleting it off your system to avoid any more confusion.

**Comment by urb4nc4rl** [comment]
Thanks for the swift reply - you're right, I had two copies on my system.

Have deleted the old one and will re-upgrade.

**Comment by dmarmor** [comment]
Excellent! Let me know if you have any more problems.
