### ISSUE TITLE
Deleting app relies on the AppName, not the AppID

### ISSUE THREAD

**Issue by andresrinivasan** [dmarmor/epichrome#230]
In [the troubleshooting guide](https://github.com/dmarmor/epichrome/blob/master/TROUBLESHOOTING.md), the instructions are

> Delete /Applications/<AppName> (or wherever you created the SSB app)
Delete /Applications/Epichrome/EpichromeEngines.noindex/<User>/<AppID>
Delete ~/Library/Application Support/Epichrome/Apps/<AppID>
Delete ~/Library/Preferences/org.epichrome.eng.<AppID>.plist
Delete ~/Library/Preferences/org.epichrome.eng.<AppID>.plist
Delete ~/Library/Caches/org.epichrome.eng.<AppID>
Delete ~/Library/Saved Application State/org.epichrome.eng.<AppID>.savedState

Note the 4th and 5th deletes are the same.

I just went through this process with the latest Epichrome to correct for a generic icon being used with my app. In each delete step, I did not find an AppId but rather an AppName.

I believe this list should be

1. rm -rf /Applications/<AppName> (or wherever you created the SSB app)
1. rm -rf /Applications/Epichrome/EpichromeEngines.noindex/<User>/<AppName>
1. rm -rf ~/Library/Application Support/Epichrome/Apps/<AppName>
1. rm -rf ~/Library/Preferences/org.epichrome.eng.<AppName>
1. rm -rf  ~/Library/Caches/org.epichrome.eng.<AppName>
1. rm -rf ~/Library/Saved Application State/org.epichrome.eng.<AppName>

**Comment by dmarmor** [comment]
Thanks for the heads-up. I'll get it corrected for the next update.

**Comment by dmarmor** [comment]
Looked at this more closely. In fact the steps marked ```<AppID>``` are correct. It's just that in some cases (and I'm guessing in your case) the app ID might be the same as the app name. This will often be true if an app's name doesn't have any spaces or strange characters in it.

Also, the identical 4th and 5th steps is a typo. One of them should be ```org.epichrome.app.<AppID>.plist``` rather than ```.eng```.

**Comment by talleux** [comment]
@dmarmor After seeing this comment you could delete my PR #234

**Comment by dmarmor** [comment]
The troubleshooting guide is now updated with this edit, so closing this issue. Thanks!
