### ISSUE TITLE
Which version of epichrome has an app?

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#236]
How to know with which version of epichrome an app was created?
How to know the version epichrome an app is now based on? It may differ from the version it was created with, if it was updated in between.

**Comment by dmarmor** [comment]
The easiest way to tell what version of Epichrome an app is currently based on is to `Get Info` on it in the Finder. There's no way to tell which version of Epichrome was used to create an app, only which version of Epichrome the app is currently based on. The version will be at the bottom of the first block of information under `General:`. If you are using the column view in the Finder, you don't even need `Get Info` but can just look at the pane of info that appears to the right of the app when you select it.

There's no way to find out what version of Epichrome was used to create an app once it's been updated to a new version. When an update happens, it recreates the entire internal structure of the app, and the old one is gone. Starting with 2.3.0, the welcome page attempts to store bookmarks of itself that can act as a log of updates, but any apps that originated pre-2.3.0 won't have kept that info.
