### ISSUE TITLE
Feature wish: Templates for apps

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#239]
Each time a create a new (chrome based) app i repeat all the same steps:
* Going through the chrome settings and configure like i need
* Installing all extensions is usually need, including some of their settings
* Maybe i would login into some web apps in order to store their password in the new app

It would be so great to have something like templates or simply (even better) the ability to copy some of these settings from existing apps while creating new apps. It would be nice to choose what to copy: Extensions, Settings, Passwords, etc....

The first step has be done: now we get on the welcome page a list of extensions installed in the default browser, including links to install them.
Thanks a lot @dmarmor for that!!

As a temporary solution: is it possible to copy some folders from existing apps into new ones?

**Comment by dmarmor** [comment]
Yeah, something like this would be very useful, but I'm not sure how much can be done, and the interface would be very complicated and probably is beyond anything I have time to work on in the near future.

I think your idea of copying folders is the best one for now. If you're creating many apps that you want to have identical extensions and/or login state, here's what I would try (I haven't tested this, so can't guarantee it will work):

1. Create one app and get it all set up how you want.

2. Quit the app and make a zip of its `UserData` directory (in `~/Library/Application Support/Epichrome/Apps/<AppID>/UserData`).

3. Create a new app and run it once, then quit.

4. Replace that app's `UserData` directory with a copy of your saved one.

5. Run the new app again.

This might work, or certain parts (passwords, etc.) might not. Chrome security has gotten tight in terms of encrypting session data and such, and some of the data might not be copyable. But I'd be very curious to know if it works!

**Comment by talleux** [comment]
@dmarmor finally i found time to test this - actually i really needed it. 
I did exactly like you wrote, using Epichrome 2.4.0 BETA 7. As i cloned an app that i used for years, i was happy to find all the User Data i could think of - even passwords! Thanks! 

Maybe you will find some time one day to make a clone function, but that it only a comfort feature actually ;-)
As there probably are much more important issues, you may want to close this issue.

**Comment by dmarmor** [comment]
Great to know that worked so smoothly! I guess since all the encrypted stuff is copied to the same user on the same system, it doesn't present any security issues for Chrome/Brave.

I will add this to my to-do list, as I agree it would be cool to be able to easily clone an app with all its settings, and wouldn't be all that difficult to do, except for the interface of course, as the stupid dialog-based system is so limited and ugly. Might have to wait until that glorious day when I finally have a chance to rewrite the whole thing with a proper interface...
