### ISSUE TITLE
Tips on editing existing apps

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#240]
I know that editing existing apps is a feature that may come in the future. Is there any way to manually edit _some_ settings editing config files?
Like:
* Name of the app
* Behavior mode (App / Browser)
* Tabs on start: remove, add, edit
* Other?

**Comment by dmarmor** [comment]
Yes, for now the things that can be reasonably easily edited are behavior mode and tabs on start, though editing them requires editing your app's main executable script, which of course can render it unable to run. So be careful! Here's what to do:

1. Edit `<App Name>.app/Contents/Resources/script`

2. Look for the line that begins `SSBCommandLine` near the top of the script. It will look like this:
```
SSBCommandLine=( '--app=http://example.com/' )
```
If it is browser-style, it will look like this:
```
SSBCommandLine=( 'http://example.com/' 'http://example.com/' )
```
If it's an app with no configured tabs, it will look like this:
```
SSBCommandLine=()
```

3. Edit that line to look like whichever style you want, and to have the URLs you want. *Please remember the single-quotes around each item in the list!*

I wouldn't try to edit anything else about an app at the moment. Editing the name or the icon or anything else cannot be done by making a single change like this, and you're more likely to break the app than successfully edit it. This feature is coming!
