### ISSUE TITLE
Error filtering Info.plist file

### ISSUE THREAD

**Issue by ljavierrivera** [dmarmor/epichrome#244]
Brand new install on brand new laptop (OS 10.15). Upgraded to EpiChrome 2.2.4 because it asked. Believe I initially set it up with Brave browser. Now it won't let me create any apps.

Please help!

**Comment by ljavierrivera** [comment]
Corrected the info above. Seems my shortcuts was using 2.2.4 instead of the latest. I was able to create an app albeit with the same error as found here: https://github.com/dmarmor/epichrome/issues/235

Going to close this ticket as it's now technically a duplicate

**Comment by dmarmor** [comment]
I'm glad you found the problem, @ljavierrivera. If you have more info on the #235 problem, please post it there. I would love to see logs of the master prefs error so I can figure out why that's happening. (The good news is it's not very serious and you can still use the apps just fine.)
