### ISSUE TITLE
Engine payload executable 'Google Chrome' not found.

### ISSUE THREAD

**Issue by hr2334** [dmarmor/epichrome#247]
Creating a new app using the brave engine and get this pop up

<img width="423" alt="Screen Shot 2020-06-02 at 10 40 34 AM" src="https://user-images.githubusercontent.com/66319308/83533552-b7f0b080-a4bd-11ea-9901-5c2407016940.png">

The log says: 

*[13206]Asana(580)/setwelcomepage(681)/getextensioninfo(1389): Unable to get locale en name for extension nckgahadagoaajjgafhacjanaoiihapd. Using ID as name.
*[13206]Asana(685)/setenginestate(1974): Engine payload executable 'Google Chrome' not found.
![13206]Asana(687)/abort(834): Aborting: Engine payload executable 'Google Chrome' not found.

No matter how many times I delete and create, same issue and doesn't open the app, but it's "running" under activity monitor

**Comment by dmarmor** [comment]
Hmm! This is very weird. Looks like something went wrong and the app is confused as to whether it's Brave or Chrome. I need to look at the innards to see what happened. Could you zip the app and send it to me? (No need to zip the data directory or engine, just the app you created with Epichrome. And if you'd rather not post it here, let me know and I'll set up a way to have you send it to me directly.) Thank you!

**Comment by hr2334** [comment]
If it helps, I think when you released the recent major release a month ago, I started having issues and despite creating new epicchrome apps with different names for this same website, it has issues.

I tried to attach the zip file, but it was rejected by gmail.  Is there a better way to share?

Really appreciate it.

**Comment by hr2334** [comment]
[Asana.zip](https://github.com/dmarmor/epichrome/files/4724203/Asana.zip)

**Comment by dmarmor** [comment]
I got the zip through the file request. Thank you! I'll try to take a look tomorrow or this weekend and will let you know as soon as I have an update.

**Comment by dmarmor** [comment]
Sorry for the delay on this. I finally had a chance to take a look, and the app seems fine, and runs with no problem on my system. I suspect this actually has to do with the fact that you had created several apps using the same website. I wonder if you somehow ended up creating a new app with the same ID as an old Chrome one you'd deleted.

You can find out if this is the problem by looking at the config file for this app, in `~/Library/Application Support/Epichrome/Apps/Asana/config.sh`. If you see a line like this:

```
SSBEngineSourceInfo=( 'com.google.Chrome' 'Google Chrome' 'Chrome' 'Google Chrome' '83.0.4103.97' 'app.icns' 'document.icns' '/Applications/Google Chrome.app' 'Google/Chrome' 'Google Chrome Master Preferences' '--enable-features=PasswordImport' )
```

then that's your problem, and you should be able to fix it by deleting that line from the config file, then rerunning the app.

Please let me know if that turns out to be the problem. If not, we'll keep looking...

**Comment by hr2334** [comment]
Thank you, not sure if I'm looking in the wrong place, but under that path of application support, I don't see Epichrome?

**Comment by dmarmor** [comment]
Hmm. That is very odd. Are you looking in Terminal or in the Finder? Sometimes the Library folder is hidden in the Finder, but you can get to it by hitting Cmd-Shift-G or from the menubar at `Go->Go to Folder...` and then entering `~/Library`. Then if you select `Application Support` you *should* see an `Epichrome` folder, and an `Apps` folder inside that which contains the data directories for all your apps.

If you're missing that `Epichrome` directory then I'm super confused and not sure how any of your apps are actually functioning!

**Comment by hr2334** [comment]
thank you very much! That worked.  How do I donate?

**Comment by dmarmor** [comment]
Glad it worked! And thank you for asking about donating. The best way to support Epichrome is to become a patron on Patreon, which also gets you access to beta versions and early access to release versions. Here's the link:

https://www.patreon.com/bePatron?u=27108162

**Comment by dmarmor** [comment]
FYI, I've added a check for this situation, so it shouldn't happen again starting with 2.3.3.
