### ISSUE TITLE
Developer Tool dock in Browser

### ISSUE THREAD

**Issue by martyLauders** [dmarmor/epichrome#25]
Is it possible to dock the developer in the browser screen. Now, if I open developer tools, it always opens in a new window, which is not nice behavior when in fullscreen. Not very urgent, but would be nice.

**Comment by dmarmor** [comment]
The way to do this would be to convert the app window to a regular window (the shortcut in the Epichrome Helper extension is Command-Shift-L), then open the developer tools. They should open docked to the tab. Then click anywhere on the main tab (not in the developer tools), and then use the same shortcut to convert the window back to an app window.

You can also right-click anywhere on the app window page and select Show Address Bar and Hide Address Bar to accomplish the same thing as the shortcut key.

Let me know if you have any trouble with that procedure!

**Comment by martyLauders** [comment]
Worked perfectly. Thanks!
