### ISSUE TITLE
Auto-create custom icons (feature request)

### ISSUE THREAD

**Issue by MalEbenSo** [dmarmor/epichrome#253]
Epichrome creates identical default icons for every app. 

It would be immensely helpful if Epichrome tried to add a custom icon for apps.
Sources could be favicons and logos on the site.

For reference: nativefier has such a feature.

**Comment by dmarmor** [comment]
Hi @MalEbenSo, thanks for the request! This idea has actually been on my to-do list for quite a while, but it's not feasible to do with the current architecture of Epichrome.

At some point my plan is to do a major overhaul that would streamline app building a lot, and scraping favicons is part of the plan for that. (I don't have any time frame on this, unfortunately, as I don't have a ton of time to work on Epichrome these days.)
