### ISSUE TITLE
Brave Nightly

### ISSUE THREAD

**Issue by eleaner** [dmarmor/epichrome#255]
Hi

Would it be possible to add Brave Nightly as an option?
Currently Brave Desktop does not have sync capabilities but they are available in Nightly

**Comment by dmarmor** [comment]
Hi @eleaner, thanks for the idea. I've looked into this, but the Brave Nightly is inherently unstable (pre-beta) so doesn't seem like a good option for a built-in engine. I think your best bet if you need sync would be to lobby the Brave developers to restore that feature to the release build as soon as possible (presumably they're working on this if it's in the nightly channel).

Eventually I am hoping to be able to open up the external engine option to allow users to use whatever Chromium-compatible browser they want (though that wouldn't have the advantages of the built-in engine--it would be akin to the current Chrome option).
