### ISSUE TITLE
App with custom icon switches to default Chrome icon occasionally

### ISSUE THREAD

**Issue by mkb218** [dmarmor/epichrome#256]
I have one Epichrome app that occasionally reverts to a Chrome icon in the Dock and in the Finder. When I created it, I added a custom icon. When the icon switches to the Chrome icon, I can quit and restart and the icons go back to the custom icon I had specified. I'm on Epichrome 2.3.3, Chrome 83.0.4103.106, and OS X 10.14.6.

**Comment by dmarmor** [comment]
Hi @mkb218, this is a problem folks used to experience in 2.2.x but I haven't seen reports of it since 2.3.x and haven't seen it myself. Have you seen any pattern to when the problem occurs? Anything you're doing with the app at the time, or any interaction with the regular Chrome browser (being run, not being run, one or the other being launched after the other, etc.)?

**Comment by mkb218** [comment]
I typically have regular Chrome open but not actively using it at the time. I'll keep an eye out for other patterns.

**Comment by mkb218** [comment]
Aha! It happens every time I change my display configuration! I usually work with my laptop closed and an external monitor attached. When I open my monitor up to use the camera, the icons turn into Chrome icons. When both displays are active, the main display is set to the built-in display, so the Dock changes locations. If I set my external monitor to be the main display all the time, I don't experience the issue when opening or closing my laptop, and it doesn't seem to matter if regular Chrome is running or not.

**Comment by dmarmor** [comment]
Hi @mkb218, that's very odd! I just tried to recreate it on my own system, but can't make it happen. Does it happen every single time you open the laptop, whether the app in question is in front or another app is, and/or whether Chrome is running/not running? I tried a bunch of permutations but couldn't get it to happen. Also, do you have multiple Spaces or anything like that happeneing? (My system has "Displays have separate Spaces" checked in the Mission Control pane in System Preferences, but I tried unchecking that and it didn't make any difference.)

**Comment by mkb218** [comment]
I have "Displays have separate Spaces" checked too, but I don't use Spaces. It does appear to happen every time I open or close the laptop and change main displays, whether Chrome is open or quit. I tried moving the Dock away from its usual location on the right hand side of the screen, and that didn't change anything either. One last weird thing is that only two out of the three Epichrome apps in my Dock exhibit this problem.

**Comment by mkb218** [comment]
Oh, and if the affected Epichrome app is not running when I switch monitors, the icon doesn't change.

**Comment by dmarmor** [comment]
I've tried to recreate this setup exactly, but I cannot get it to work at all.

I doubt updating to 2.3.4 would make any difference, but the update will trigger the engine to be deleted and recreated, so maybe that could have some kind of effect? I'm sort of grasping at straws here, as I cannot get this to happen on my system, so it's very hard to diagnose. I assume rebooting doesn't improve matters at all?

**Comment by mkb218** [comment]
No, rebooting didn't make a difference. I should mention that these use the Chrome engine, not the Brave engine.

**Comment by mkb218** [comment]
Aaaaand updating everything to 2.3.4 fixed it. Weird.

**Comment by dmarmor** [comment]
Hmm! Yeah, nothing changed in that version that should affect your icon problem. This makes me suspect that something had just gotten messed up with your engine, as the update would've caused the app to delete and recreate the engine. I should've thought to ask you to delete that before. Anyway, hopefully it was just something random and fixed now, but let me know if it starts doing it again...
