### ISSUE TITLE
App freezes temporarily

### ISSUE THREAD

**Issue by MalEbenSo** [dmarmor/epichrome#264]
I have an app for https://ebay-kleinanzeigen.de.

The app repeatedly freezes temporarily (10-15s), e. g. menu not accessible, login data not shown, no data loaded.
The same page works fine in Safari.

I have tried the following troubleshooting steps without success:
- Quit and restart
- Deleting the old app as described below and re-building from scratch
https://github.com/dmarmor/epichrome/blob/master/TROUBLESHOOTING.md#to-delete-an-epichrome-app
- Upgrading from 2.3.4 to 2.3.5
- Disabling Brave ad-blocker and other extensions

**Comment by dmarmor** [comment]
Hi @MalEbenSo, I've tried creating a Brave app with this URL and am not experiencing any freezing on my system.

Do you have the regular Brave Browser installed on your system? If so, could you try opening this URL in Brave itself and see if you get similar problems to when you open it in your app? That could indicate that for some reason Brave doesn't like the site.

**Comment by MalEbenSo** [comment]
I have tried Brave, and it is showing the same problems. 

So while Epichrome Apps are showing the problem, the cause seems not lie in the Epichrome code but the underlying Brave components.

**Comment by dmarmor** [comment]
OK, gotcha. Yeah, that's definitely a Brave problem then. If you haven't already tried 2.3.6, that has an updated version of Brave in it (though if you've had the problem on Brave itself in the last few days, it's likely the latest version, which is 1.11.104 as of this writing).

If 2.3.6 doesn't help, then for the purposes of your app, I'd say unfortunately probably the best solution would be to create a new app using the Chrome engine. In issue #263 I outlined a procedure for how to connect a new app to the old app's data, in case you have a lot of saved sessions, bookmarks or whatnot. Here's that procedure:

https://github.com/dmarmor/epichrome/issues/263#issuecomment-662762749

I'll close this issue for now, but if you have more info, please don't hesitate to add another comment.

**Comment by MalEbenSo** [comment]
I will sit it out and just wait for it to be fixed eventually in the Brave engine.

Thanks for looking into this.
