### ISSUE TITLE
Gmail shortcut links aren't delegated

### ISSUE THREAD

**Issue by treyharris** [dmarmor/epichrome#27]
Google Gmail and Inbox both have shortcuts that let you visit a link an "Update" email references without opening the body of the message. In Gmail, for example, here's how some GitHub notifications look:
![image](https://cloud.githubusercontent.com/assets/97895/9706128/0bbb2a06-54aa-11e5-9062-d2ca48dd993a.png)

Clicking one of those Gmail buttons opens a new tab in the Epichrome SSB rather than launching the default browser.

In Inbox, blue callout links serve the same purpose as the Gmail buttons:
![image](https://cloud.githubusercontent.com/assets/97895/9706149/f37812c8-54aa-11e5-9720-c3524ddc4f58.png)

However, clicking these links _do_ correctly open the default browser (or whatever other handling was assigned in the Epichrome extension).

Is there a way to make the Gmail buttons work as the Inbox ones do, too?

**Comment by dmarmor** [comment]
Hi @treyharris,

Yeah, I have a gmail SSB and have noticed this same problem. It comes from the fact that those "View ..." buttons are not actually HTML links. They're javascript buttons that end up calling a link, so my usual link-handling logic doesn't catch them.

I've added this to my to-do list. I should be able to catch the new window when it opens and redirect as usual. (Not sure why it's not already doing it, to be honest, but when I get a chance I'll take a look.)

Thanks for the feedback!

Cheers,
  DAve

**Comment by treyharris** [comment]
This appears to potentially be fixed, at least for some GitHub quicklinks I just tried? I see you closed and reopened though, so maybe it's more subtle than that?

**Comment by dmarmor** [comment]
Hmm. It still doesn't work right on my system. It's possible you have some different rules in your Epichrome Helper that allow it to work? If you have a moment, maybe you could export your rules and send them? (No hurry, since I won't have time to work on this for a while.)

**Comment by treyharris** [comment]
Sure, this is all I've got:
![image](https://cloud.githubusercontent.com/assets/97895/13055891/e35892fa-d3df-11e5-9670-a4f44b8ce261.png)

**Comment by dmarmor** [comment]
Hmm. Yeah, that doesn't look like it's doing anything fancy my rules aren't. Those little quicklinks are working for you, huh? I can't really figure that. They still don't work for me. I guess for now, let's not look a gift horse in the mouth, and I'll try to figure out what's going on when I've got some more time...

**Comment by treyharris** [comment]
Are the quicklinks working for you now? Recently they've been okay for me, though I did need to adjust my custom rules a bit due to changes in Google's handling of Hangouts, now I have:

![image](https://cloud.githubusercontent.com/assets/97895/15785184/edcb057a-2983-11e6-9495-cc360bc37313.png)

**Comment by dmarmor** [comment]
Quicklinks still don't work for me! I did notice that in the current version of Chrome if I hit Cmd-N to open a blank tab, it sends that to my default browser! Chrome's tab-handling is a big mess, and seems to change version to version. I guess I'll close this issue for now, since it seems to work for you and nobody else is complaining (yet). Of course, reopen if anything changes...
