### ISSUE TITLE
Any way to enable native notifications?

### ISSUE THREAD

**Issue by purevertigo** [dmarmor/epichrome#271]
I would like an epichrome instance to use native notifications and not integrate with the system. Any way to do this?

thanks

**Comment by dmarmor** [comment]
Hi @purevertigo, I'm not sure I understand what you mean by this. What do you mean by native notifications? When I think of native notifications I'm thinking of the Chrome ones that use the macOS notification system. Is there another Chrome or Chromium notification system that doesn't integrate with macOS?

**Comment by purevertigo** [comment]
@dmarmor before this update for brave/chrome, the browser produced its own notifications which I prefer now the flag is gone.

Here is the same question asked by someone else (I also use it for TweetDeck),

https://support.google.com/chrome/thread/18102285?hl=en

 thanks

**Comment by dmarmor** [comment]
Thanks for the clarification. It looks like this is a change to the architecture of Chromium (on which both Chrome and Brave are based), so I think your best bet would be to follow the instructions posted by Derek in the support thread you sent:

https://support.google.com/chrome/thread/18102285?hl=en&msgid=20525144

In the case of an Epichrome app, the relevant `Local State` file will be found in `~/Library/Application Support/Epichrome/Apps/<AppID>/UserData/Local State`.

Good luck!
