### ISSUE TITLE
Any way to block changes to local state?

### ISSUE THREAD

**Issue by purevertigo** [dmarmor/epichrome#273]
When trying to add native flags to the local state file, described here https://github.com/dmarmor/epichrome/issues/271

the file resets itself. 

How do I avoid this?

thanks

**Comment by dmarmor** [comment]
Hi @purevertigo,

This sounds like a Chromium issue. Basically all Epichrome does is launch the browser with a specific user directory and set of URLs, so it doesn't have any control over how the browser engine handles that local state file, and wouldn't have any way to affect this behavior.

My suggestion would be to try to get the behavior you want working in an actual Chrome or Brave browser. If you can get it to work there, then the same solution should work for your Epichrome apps as well.
