### ISSUE TITLE
Losing app name

### ISSUE THREAD

**Issue by relluf** [dmarmor/epichrome#276]
I noticed that the name of the application in the menubar has changed to Chrome in all of my Epichrome-based apps. Similar to: https://github.com/dmarmor/epichrome/issues/173

**Comment by gregschroeder** [comment]
same. may be coincidence, but started for me after the recent update to Catalina 10.15.7 
I've tried blowing them away (including deleting all the parts referenced in Troubleshooting) and recreating, and still called 'Chrome' in the menubar.

**Comment by relluf** [comment]
I am still on 10.15.6 (19G2021)

**Comment by henderea** [comment]
Thought I would mention this, but I'm encountering the same issue on 10.14.6, so it must be from a Chrome update rather than the OS.

**Comment by dmarmor** [comment]
Thanks for this report, @relluf, and for the confirmations @gregschroeder & @henderea. I've confirmed this is a change in the latest update of Chrome and it appears I can fix it relatively straighforwardly. I'm going to see if I can slot it in easily on the 2.3 release branch and get it out in the next update, but if it's too complicated it might have to wait until 2.4.0...

**Comment by dmarmor** [comment]
Hey all, I just released 2.3.13 with this fix in it. Please give it a try and let me know how it works for you!

**Comment by parkben01** [comment]
@dmarmor, I haven't done a bunch of testing but the 2.3.13 release fixed this issue! It also fixed the issue where the the application icon was reverting to the default Chrome icon instead of my custom icon. Thanks!

**Comment by relluf** [comment]
@dmarmor Works perfect here. Thanks a bunch really :-D

**Comment by gregschroeder** [comment]
@dmarmor, seems to work - Thanks!

**Comment by dmarmor** [comment]
Thanks for all the feedback! Seems like this fixed it, so I'll close this, but if it comes up again, please let me know.
