### ISSUE TITLE
Recreating apps on crash

### ISSUE THREAD

**Issue by grantyoung-ww** [dmarmor/epichrome#277]
Hi there.

I know I've raised this before, but it's now getting terribly frustrating...

If the computer crashes unexpectedly, all open Epichrome apps lose their settings and open up in the other app spaces (i.e. if I have Google Drive in one app, it opens up my Gmail app space). This never used to happen before the switch to Brave, and I'm not sure why it's considered acceptable functionality since that change.

Do you plan to fix this any time soon?

If not, I will have to seek alternatives, as I lose about 15–20 mins every time it happens recreating all of the apps I've setup that way.

Thanks in advance.

Regards, Grant

**Comment by dmarmor** [comment]
Hi @grantyoung-ww,

I assume this is on 2.3.x? If so, the first item in the troubleshooting guide addresses this issue. You do _not_ need to recreate all your apps.

https://github.com/dmarmor/epichrome/blob/master/TROUBLESHOOTING.md#opening-an-app-from-the-dock-opens-a-generic-browser

**Comment by grantyoung-ww** [comment]
Thanks. This was not the case last time I logged the issue. I will try this fix next time it occurs, and hopefully this will address the issue.
