### ISSUE TITLE
minor release request to update to Brave latest (1.15.76)

### ISSUE THREAD

**Issue by demmer** [dmarmor/epichrome#279]
First of all thank you for all the work you put in. Epichrome is a huge productivity improvement for me.

Unfortunately I can't use it to access several internal sites at my company because they are protected by Duo 2FA and they block access from Brave 1.15.72 as it is over 20 days old.

I would much appreciate a minor release whenever you get a chance. Thanks!

**Comment by dmarmor** [comment]
Hi @demmer, thanks for checking in on this, and apologies for the delay getting this maintenance release out. I've just posted it, so you should be able to download and install now.
