### ISSUE TITLE
macOS big sur

### ISSUE THREAD

**Issue by infira** [dmarmor/epichrome#280]
After upgrade to bigSur epic chrome stoped working.
I had this error in log
"*[10940]Gmail062(739)/clearmasterprefs(2481): Timed out waiting for app prefs to appear.
![10940]Gmail062(860)/abort(884): Aborting: The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting.
"
Tried to clean remove with App cleaner "https://freemacsoft.net/appcleaner/" and reinstall in still same error

**Comment by barak-haviv** [comment]
Have the same problem

**Comment by dmarmor** [comment]
Duplicate of #275
