### ISSUE TITLE
1passwordx unlock hot key doesn't work in app window

### ISSUE THREAD

**Issue by demmer** [dmarmor/epichrome#288]
## Description
The hot key to unlock 1PasswordX doesn't work in the main app window

## Details
When starting an epichrome app and trying to use 1PasswordX, the password vault is of course initially locked.

The extension prompts to unlock using a hot key (Shift-Cmd-X) but that does nothing when I push it.
Only if I create a new window with Cmd-N, then enter the hot key, then close the window it does the trick.

Is there some way to make this work in the main window so I don't have to go through this extra steps?

**Comment by dmarmor** [comment]
Yeah, I've noticed this problem, but there's nothing I can do about it in Epichrome. It's a problem with the 1Password extension--for some reason, the hot key only works in browser-style windows, and not app-style windows (this is true in the regular Chrome and Brave browsers too). I'm not sure why.

It might be worth submitting a bug on the 1Password forum about it. If you do so, please add a link to the post here, so I and other users can comment in support...
