### ISSUE TITLE
Open Link in main window if app not started (chrome and brave based)

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#291]
@dmarmor as promised in #227 (https://github.com/dmarmor/epichrome/issues/227#issuecomment-707964635) i open this new issue. Although this isn't an issue for me anymore.

Short description of the original issue:
- Open a link in an app that isn't started (for instance, open a link in an email, in the finder etc.. and have a context that will open that link in an chrome or brave based epichrome app - for example using a browser chooser like choosy, having the app as default browser, dropping the link on the app icon etc.
- The app starts and the link will open in a new window instead of in the main window

In #227 you said:
>  that is the expected behavior. When you send a link to an unopened Epichrome app, it's basically launching the app and signaling it to open whatever URL you are sending. Since the app will always open its main app window, or preconfigured tabs, or in your case whatever tabs were open on last launch, the new link will either get opened in a separate window or in another tab of the main window. Which opens first is not choosable, and just depends on the timing of when the app processes the open event. You'll see the same behavior if you try to send a link to an unopened Chrome or Brave browser.

Indeed i can reproduce that behavior with native chrome and brave apps. Interestingly i can't reproduce that on any of my Epichrome 2.4b app - i even tested this with fresh chrome or brave based epichrome apps. It behaves like i like: open link in the main window (in my case all apps have only one window open when i start them). So for me there is no issue but it could interesting to understand why Epichrome Apps behave here differently than the native chrome. But please, don't change this ;-)
So you may want to close this issue.

**Comment by dmarmor** [comment]
That sounds like good news! 2.4 handles opening URLs differently from 2.3 so that's probably what's going on. I'm still not quite sure how it's giving you this behavior, but if it's good behavior I guess that's good! I'll close this for now, but if problems come up, we can revisit.
