### ISSUE TITLE
Can I flexibly open some links in my app window and send others to a tab in Brave?

### ISSUE THREAD

**Issue by bjornhansell** [dmarmor/epichrome#294]
I've built an "app-style" app and set Epichrome helper to open links within the app in the main app window. It opens links to other domains in a tab in my main Brave browser window. Works like a charm.

However, I sometimes want to open an extra instance of my app site in a tab in my Brave window. I was hoping that using command+click a link would send it to Brave, but it just opens a new window in my app. This is not helpful.

It seems the best way to achieve that would be if I could send command+click links to Brave. I've tried to adjust Epichrome helper to send links that should open in another tab to Brave, but that did not work, it still opens a new tab in my app. 

I'm attaching my current settings from Epichrome helper.

<img width="589" alt="Screen Shot 2021-02-01 at 8 10 52 AM" src="https://user-images.githubusercontent.com/42928283/106500913-3bacd380-6477-11eb-8055-ea832a1b5367.png">

**Comment by dmarmor** [comment]
Yeah, this isn't really possible easily in this version of the extension. The best way would be to right-click the link and choose Copy Link, then paste into Brave. Not ideal, but it'll work. I do have options for this working in my internal version of the next extension release, which I'll be working on more once 2.4.0 is released. I'll have the beta available for testing at that point and will post the link here. Thanks!

**Comment by bjornhansell** [comment]
Thanks @dmarmor! I actually solved my problem by downloading Contexts that lets me switch between full-screen windows of apps on my Mac with a keyboard command. Now, I'm directing regular links to open in Brave and letting command-click links open a new window of my Epichrome app.
