### ISSUE TITLE
Deep links don't work 

### ISSUE THREAD

**Issue by eduard-k** [dmarmor/epichrome#297]
Links like https://workflowy.com/#/d20d10c6eaf1 opens WorkFlowy in Epichrome, but does not navigate to the deep link.
Can I fix it through settings of Epichrome?

**Comment by dmarmor** [comment]
I'm not sure I understand what you mean by "deep link." I don't have a Workflowy account, so when I click that link (in Chrome) it just takes me to a sign-up page, which I assume is not what you mean. Is it that the site should do some kind of redirect once it gets there? Epichrome apps should basically work just like a full browser, so any behavior you'd get by launching a link in your browser should be possible in an app, no setting required (and in fact there are no settings, as once an Epichrome app is launched, it essentially _is_ just a browser)...

**Comment by eduard-k** [comment]
Possible explanation. WorkFlowy desktop application, which is also just a browser, correctly processes links within a subdomain beta.workflowy.com by redirecting them to the main domain. 
I will disable the beta and do additional testing.

**Comment by eduard-k** [comment]
In Safari paste the link https://workflowy.com/#/d20d10c6eaf1. Epichrome gets the link https://workflowy.com. Part of the link /#/xxx is lost along the way.

**Comment by dmarmor** [comment]
Can you help me understand the sequence here? You paste that link into Safari. Then what happens? How is it getting sent to your Epichrome app?

**Comment by eduard-k** [comment]
I use Default Apps in System Preference. After installing WorkFlowy desktop, which is also just a browser, there is new parameter in URLs - workflowy-deep-link.
If this parameter is set to WorkFlowy desktop. When I enter a link to an WorkFlowy item (deep link) in Safari, link opens this item in WorkFlowy desktop.
If this parameter is set to WorkFlowy in Epichrome. When I enter a link to an item in Safari, link opens Epichrome app, but does not go to deep link. There is short link https://workflowy.com in Adress Bar of Epichrome app, not full deep link.

**Comment by dmarmor** [comment]
Well, I'm not sure what's going on there, and as I don't have Workflowy, I can't easily test it. I would suspect, though, that the problem might be that it's not sending it as a plain link, but possibly using some URL scheme.

As a test, could you take the URL for one of these deep links (e.g. the one you posted above, `https://workflowy.com/#/d20d10c6eaf1`) and use the terminal to open it in one of your apps, like this:

```bash
open -a '/<path>/<to>/<your-app>.app' 'https://workflowy.com/#/d20d10c6eaf1'
```

And let me know what happens. If the link comes through properly, then the problem must have something to do with the way this workflowy-deep-link parameter works. If it *doesn't* come through properly, and you see the same problem, then there must be something else going on. Either way, I'd love to know!

**Comment by eduard-k** [comment]
I test without Epichrome, with settings in Default Apps to open deep links in WorkFlowy desktop application.
From terminal open in Safari. The deep link open in Safari and then with redirect  in WorkFlowy desktop.
From terminal open in Brave. The same - in Brave and in app. 
From terminal open in WorkFlowy desktop. The deep link don't work.

**Comment by dmarmor** [comment]
To make sure I understand, do you want these links to end up in WorkFlowy Desktop? Or do you want them to end up in your Epichrome app?

If the links open correctly in the Epichrome app from the terminal (as I think they do from your description?) then the problem seems to be with how Epichrome is sending links to the Epichrome app. Is that correct?

Sorry for any confusion. This is very difficult for me to diagnose without having a way to test it...

**Comment by eduard-k** [comment]
I need deep links in Epichrome to connect pages from WorkFlowy with Hook. Here is the [Hook forum thread](https://discourse.hookproductivity.com/t/epichrome-single-site-browser-compatibility/2905) where Epichrome is discussed.

**Comment by breeden** [comment]
@eduard-k FYI @dmarmor is winding down Epichrome development by the end of 2021 (see #336 #338) but developers looking to continue the project are encouraged to contact him!
