### ISSUE TITLE
Extensions that you activate via hotkey doesn't work 

### ISSUE THREAD

**Issue by zendude213** [dmarmor/epichrome#299]
Hi -- on the epichrome home page here in github, it's mentioned that 

> "Epichrome lets you create web-based Mac applications compatible with the full range of extensions available in the Chrome Web Store. It includes an extension to route links to your default browser." 

This is true in the sense that if I have say Tampermonkey or Stylus extension installed and have scripts, then those will work with the desktop web app created via epichrome

However, extensions that can be triggered, and in triggering > shows a prompt---these don't work at all. For example of how this looks like, on any other browser, hitting the opt + W key will show this 

![image](https://user-images.githubusercontent.com/59263556/109441291-ea0a5100-7a02-11eb-9748-aef7d69bfd13.png)

This means that extensions like Slapdash, Stationhq, basically most extensions don't work

Is this a limitation? Or am I doing something wrong?

**Comment by dmarmor** [comment]
Thanks for the report. I'm not able to reproduce the problem. As a quick test, I installed Slapdash on Chrome, one Chrome-based Epichrome app, and one Brave-based Epichrome app. The Cmd-J shortcut worked for me the same everywhere, both in tabbed windows and in app-style windows. I did have to reload the page after installing the extension, but after that, when I relaunched the apps it worked on the first try.

So I'm not sure what's going on on your system. Could you try creating a new app, installing Slapdash and letting me know if you consistently can't get it to launch with Cmd-J? Thanks!

**Comment by zendude213** [comment]
Hi sorry for the long delay. I re-tested and it this time it worked. However, it doesn't work with some extension I use such as [WFX](https://chrome.google.com/webstore/detail/wfx-for-workflowy/jbehgpdjkcconnaagjhddddfdajbpfhi?hl=en) . I think this may be a problem that could be extension specific although the one I just mentioned is relatively new (Aug 22, 2020)

Thanks

**Comment by dmarmor** [comment]
Hi @zendude213,

I just tested WFX and I think I see the problem you're experiencing. Unfortunately, it's not one I can solve. Some extensions, for reasons I don't understand, don't properly handle keyboard shortcuts in Chrome or Brave app-style windows such as Epichrome apps can create. You can confirm this is the problem by opening a regular tab-style window in the same app and trying the WFX keyboard shortcut in that window. It will work properly there.

I haven't been able to find why some extensions' shortcuts work in app-style windows and others don't (the current 1Password extension has this problem and it drives me nuts). It's out of my control, as it's a problem with the underlying browser.

Sorry I don't have a proper solution. Here are a couple possible workarounds:

- If you have an app where you make heavy use of an extension like WFX, you could edit the app and change it to a Browser Tab-style app.
- You can use the Epichrome Helper extension shortcut Cmd-Shift-L to switch an app-style window to tab-style (and back). So you could switch your app window to tab-style, invoke WFX, then switch back after you've finished with WFX.
