### ISSUE TITLE
Use System Dialog as default for Print window. 

### ISSUE THREAD

**Issue by 4eyez** [dmarmor/epichrome#30]
Hello

Great app, love having SSB's again!

I changed the defaults of my Chrome (actual app) so that when I print I use the System's Dialog by default as opposed to the Chrome one. I did that by typing this into Terminal:

defaults write com.google.Chrome DisablePrintPreview -bool true

How would I do the same thing for one of the SSB's I created with Epichrome?

**Comment by dmarmor** [comment]
Hi @4eyez,

This is doable, you just need the identifier of your Epichrome app. That will be:

```bash
org.epichrome.app.<something>
```

The easiest way to find it is with this command:

```bash
defaults read <path-to-your-epichrome-app>/Contents/Info CFBundleIdentifier
```
For example, for my Gmail app, the command is:

```bash
defaults read /Applications/Gmail.app/Contents/Info CFBundleIdentifier
```

Then take the identifier returned by that command, and enter the same command you used for Chrome:

```bash
defaults write org.epichrome.app.<app-ID> DisablePrintPreview -bool true
```

You'll have to restart your app, but then it should use the system dialog as expected.

Closing the issue, but if you have trouble, go ahead and reopen and let me know. Cheers!
