### ISSUE TITLE
Upgrading to version 2.4.0 no longer make apps recognized as browser in Big sur

### ISSUE THREAD

**Issue by jarvisluong** [dmarmor/epichrome#302]
Prior to version 2.4.0, apps created by Epichrome can still be treated as browser and can open URLs from other apps.

**Comment by deafgreatdane** [comment]
I'm on Catalina and have the same problem. I use Browser Fairy map urls to the epichrome apps, and they're no longer showing in the picklist of browsers to launch

**Comment by dmarmor** [comment]
Hi @jarvisluong & @deafgreatdane,

It's possible you're experiencing a limitation of macOS. On Catalina, the system will only ever list 32 browsers, so if you have more apps than that registered as browsers, it will arbitrarily only show 32 of them. On Big Sur, the limitation has gotten worse and it will only show 24 browsers. If this is the problem, the only solution is to delete (or deregister) some of your apps to bring the number below the limit.

If you don't have that many apps registered as browsers (i.e. if you look at the list in `System Preferences->General->Default web browser` and its list is shorter than the system limit), then the next thing I'd try is editing one of your apps that isn't showing up as expected. You can do this by dropping it on Epichrome.app. Just go through the dialogs until you get to step 5 ("Register app as a browser?") and make sure the app is currently set to `Yes`.

Please let me know if this helps you solve the problem. If not, I'll take a look and see if something else is going on.

**Comment by jarvisluong** [comment]
> Hi @jarvisluong & @deafgreatdane,
> 
> It's possible you're experiencing a limitation of macOS. On Catalina, the system will only ever list 32 browsers, so if you have more apps than that registered as browsers, it will arbitrarily only show 32 of them. On Big Sur, the limitation has gotten worse and it will only show 24 browsers. If this is the problem, the only solution is to delete (or deregister) some of your apps to bring the number below the limit.
> 
> If you don't have that many apps registered as browsers (i.e. if you look at the list in `System Preferences->General->Default web browser` and its list is shorter than the system limit), then the next thing I'd try is editing one of your apps that isn't showing up as expected. You can do this by dropping it on Epichrome.app. Just go through the dialogs until you get to step 5 ("Register app as a browser?") and make sure the app is currently set to `Yes`.
> 
> Please let me know if this helps you solve the problem. If not, I'll take a look and see if something else is going on.

Hi! Thanks for your reply! Currently I only have 8 browser including the epichrome ones

**Comment by dmarmor** [comment]
Are these apps not showing as browsers both while they are running and when they are not running? To test this, you'll need to quit `System Preferences`,  run one of the apps, then load `System Preferences->General` and look at the `Default web browser` list. Then quit `System Preferences` again, quit the app (give it 10 or 15 seconds to be 100% sure it's fully quit) and then load `System Preferences->General` again and look at the `Default web browser` list. Let me know if you see any difference. Thanks!

**Comment by jarvisluong** [comment]
@dmarmor Thank you for some guidance. I tried to move the apps under /Applications/Epichrome/Apps, then run Epichrome scan again. Now the browsers are registered back again!

**Comment by flegfleg** [comment]
Hi @jarvisluong, i have the same problems. Also, i am nowhere near the browser limit. 

what do you mean by 

>  I tried to move the apps under /Applications/Epichrome/Apps

Thanks!
