### ISSUE TITLE
Bulk Updates?

### ISSUE THREAD

**Issue by henderea** [dmarmor/epichrome#306]
Is there a way, either by script or by GUI, that I could update my apps to the latest Epichrome in bulk? It's a pain to have to open each app to update it.  I'm currently on the latest 2.4.1 version, but if it includes bulk updates, then I must not be seeing where to do it.

**Comment by dmarmor** [comment]
Yes! In the Finder, select all the apps you want to update and drop them right onto Epichrome.app. It'll bring up a dialog asking if you want to edit or just update them. Click `Update` and it should just do them one after another.

I've tested it a bit myself, but I don't have all that many apps, so haven't really given it a proper stress test. Let me know how it works for you!

**Comment by henderea** [comment]
Hmm, I tried it just now, and it didn't want to let me drop them on Epichrome.app.  I tried putting Epichrome in my dock, and it didn't want to let me drop it there either.  We're talking about /Applications/Epichrome.app, right? I also tried running ```/Applications/Epichrome.app/Contents/MacOS/applet /Applications/AtTask.app /Applications/Scrum\ Stuff.app /Applications/Jenkins.app /Applications/HockeyApp.app``` and it just brought up the regular Epichrome creation first step dialog.

**Comment by dmarmor** [comment]
No, `/Applications/Epichrome.app` is a very old version! You should probably throw it away. The current version will be in `/Applications/Epichrome/Epichrome.app`. Give that a try and let me know how it goes.

**Comment by henderea** [comment]
Ah, that worked.  Didn't realize it had moved. Looking at the /Applications/Epichrome.app, it looks like the version on it is 2.3.0b3 😓 

I've deleted it now, so I should be good.
