### ISSUE TITLE
epichrome did not auto-update from 2.4.0 to 2.4.1

### ISSUE THREAD

**Issue by gregschroeder** [dmarmor/epichrome#311]
Congratulations and thanks on 2.4.x - this is a much improved version and the clear result of a lot of work.  

This may just be my confusion, but I wanted to get clarification on how updates are supposed to work.  I never got any indication that 2.4.1 had been released while happily running 2.4.0 - even though it had been 5 days since 2.4.1 was released.  I only discovered it by manually checking Github.  This surprised me, as it used to check for new versions.  

I had used "Edit" to select Advanced Options -> Update Automatically.  I thought that this meant it wouldn't prompt me for updates, but rather, would just go grab the latest once available.

After more thinking, it seems that there are 2 distinct kinds of update:
1. Update of Epichrome itself (eg, 2.4.0 -> 2.4.1)
2. Update of each SSB app

Item (1) didn't seem to happen for me.  However, after I manually downloaded and installed 2.4.1, when I would then start each SSB anew, it would automatically upgrade.  So it seems that (2) works beautifully, and perhaps "Update Automatically" only refers to (2) and not (1)?

Is this understanding correct?  If so, why didn't (1) happen?  Is there a minimum time period > 5 days that I didn't wait?  Is there a setting somewhere?

Sorry if I'm simply misunderstanding something simple.

Thanks.

**Comment by dmarmor** [comment]
So the "Update Automatically" option refers only to the app itself, meaning that once you install a new version of Epichrome, the next time you run that app, it will auto-update to that new version.

I don't have a good way to automate the downloading and installation of new versions of Epichrome. A library like Sparkle would be the way to go for that, but given the current architecture of Epichrome, that's not possible. So for now, the best I can do is the GitHub check and download prompt.

Regarding that, I suspect you just happened to have had a check of GitHub recently when 2.4.1 released. I have it set to check every 7 days, so it seems likely that if you'd waited another day or two you'd have seen the prompt. If you ever find that you haven't seen a prompt *more* than 7 days after a new release, then something has gone wrong with the GitHub-checking.

If you (and others) feel that 7 days is too long a waiting period for the GitHub check, I'm open to making it shorter in a future release. It was set that long back when *each* app had its own timer and so it was annoying people that a new release would come out and then each app would start popping up the prompt. But now it's unified, so maybe 7 days is too long?

**Comment by gregschroeder** [comment]
ok, i waited more patiently this time and did finally get prompted for 2.4.2.  :)

i think it could check more frequently than 7 days.  if there is no update available, not a problem to have checked.  updates are now pretty streamlined so it isn't hard to do, and i'd prefer to minimize how long i have to stare at the 'update' warning from the browser.  :)

thanks!

**Comment by dmarmor** [comment]
I will be releasing 2.4.3 very soon, which has the interval set to 2 days. That should hopefully be much more on-the-ball. (Of course you won't be notified about it on that schedule since 2.4.2 is still 7 days, but going forward it will help.) I'll post here when it's out to let you know. Thanks for the feedback!

**Comment by dmarmor** [comment]
I just released 2.4.3. So starting with 2.4.4, you should get notified much sooner than before...
