### ISSUE TITLE
Backup Actual App Settings in Backups subfolder

### ISSUE THREAD

**Issue by ylluminarious** [dmarmor/epichrome#313]
In 2.4.0, there is a new feature which backs up the app bundle when the app is edited or updated. The new backup is located at:

```
~/Library/Application Support/Epichrome/Apps/MyChromeApp/Backups
```

However, I was disappointed to see that only the app bundle is backed up - not the actual app data which lives under `UserData` (one level up from the `Backups` folder). Is it possible that we could get a backup of the `UserData` folder as well, which holds all the important settings for the app such as history, extensions, cookies, passwords, etc.? It would be a really nice sanity check, just in case something went catastrophically wrong during an upgrade. Of course, it should probably be compressed since it could be rather large.

**Comment by dmarmor** [comment]
I made a conscious decision not to also back up the data directory as the data directory is often rather huge and would drastically slow down the update process, which I figured most users would *not* want. I am open to adding that as an `Advanced Settings` option in a future release if there's enough interest.

**Comment by ylluminarious** [comment]
@dmarmor Yeah, I think adding it as an advanced setting is definitely a good idea. It doesn't need to be on by default, but it would definitely be a good sanity check in case an update goes sideways.

**Comment by dmarmor** [comment]
This setting has been added to 2.4.3, which I've just released. Please check it out and let me know how it works for you. Thanks!

**Comment by ylluminarious** [comment]
@dmarmor  Fantastic! Thanks so much. It seems to work perfectly. I'll go ahead and close this now.

**Comment by ylluminarious** [comment]
@dmarmor One additional related question: do you know if it's possible to clear an app's cache through the CLI? Perhaps if we could figure this out, we could significantly cut down on backup size.

**Comment by dmarmor** [comment]
I looked through the Chromium switches but couldn't find anything on this. I'm very leery of trying to skip saving any directories for fear that it would defeat the purpose of the data backup, but if you wanted to try some experiments, the likeliest directories to exclude look like:

```
UserData/GrShaderCache
UserData/Default/Application Cache
UserData/Default/Service Worker/CacheStorage
```

If removing those doesn't lose you any session state or cause the browser settings to be corrupt, skipping them would save a lot of space/time during data backups...

**Comment by ylluminarious** [comment]
@dmarmor Thanks for the info. I'll have to play around with those at some point and see what happens.
