### ISSUE TITLE
Epichrome no longer registers apps as browsers 

### ISSUE THREAD

**Issue by flegfleg** [dmarmor/epichrome#314]
Version 2.4.1 | built-in Brave engine

All of my Epichrome Apps are no longer registered as browsers, e.g. [Browser Fairy](https://www.browserfairy.com) does not list them as browsers. 
I tried re-creating the apps, no change.

 Any help appreciated

**Comment by dmarmor** [comment]
Is it possible this is related to the browser limits in Catalina and Big Sur? Check out issue #302 and let me know if that helps. If not, I can look into it further.

**Comment by flegfleg** [comment]
Hi, 

1. running apps does not make them available in the browser selector
2. i only have around 6 browsers

Probably a different issue than #302  and related to the 2.4.**1** update? 
I used 2.4 and the browsers were registered. 

Thanks for investigating!

**Comment by flegfleg** [comment]
A bit more detail… i tried to create the app again, this window opened (for me, the first time): 

<img width="420" alt="CleanShot 2021-04-03 at 10 20 18@2x" src="https://user-images.githubusercontent.com/4009931/113472982-f2710400-9466-11eb-8450-19e11d3fa74d.png">

Also: now some of the older apps *does* show up in the browser selector, so i guess it has something to do with the browser limit? 
("Older Apps" meaning: apps migrated from Epichrome 2.3, not newly created with 2.4.1)

<img width="380" alt="CleanShot 2021-04-03 at 10 24 41@2x" src="https://user-images.githubusercontent.com/4009931/113473001-10d6ff80-9467-11eb-9791-4e04c465791f.png">
 
the list in browser fairy is quite a bit longer than in system preferences (i have marked the Epichrome Apps): 
![CleanShot 2021-04-03 at 10 31 33@2x](https://user-images.githubusercontent.com/4009931/113473104-d0c44c80-9467-11eb-80cf-99a7fa505a09.png)

The 2 older apps showing up in the browser selector are placed in  `/Applications` (not the new path `/Applications/Epichrome/Apps/`, so i tried deleting them. Did not solve it.

**Comment by dmarmor** [comment]
Can you confirm that the new app you created and does not show up as a browser was created with "Register as Browser" (Step 5) turned on?

What happens if you drop one of the existing apps you think should be showing up as a browser onto Epichrome.app to edit it? When you get to Step 5, does it show Register as Browser marked Yes?

If you can confirm all this, let me know and we'll do some further diagnosis on the misbehaving apps...

**Comment by flegfleg** [comment]
> Can you confirm that the new app you created and does not show up as a browser was created with "Register as Browser" (Step 5) turned on?
> does it show Register as Browser marked Yes?

Yes, it is!
<img width="420" alt="CleanShot 2021-04-04 at 14 51 39@2x" src="https://user-images.githubusercontent.com/4009931/113509335-507c1500-9555-11eb-8848-67e16c4743e2.png">

I have created the app with that name before is there some kind of cache/plist/etc somewhere that i could delete?

**Comment by dmarmor** [comment]
Thanks for the reply. Yeah, that's exactly as it should look, and no, just creating an app with the same name should not cause any confusion, as Epichrome would have created a unique ID for the new app.

If you have an app that's misbehaving with no sensitive info in it (secret URL or name), could you please make sure it is **not** running, and then zip it up and submit it to this URL so I can see how it behaves on my system? It should only be a couple MB. (Note that none of your session info or history is stored in the app itself, so nothing else sensitive will be in that zip.) Thanks!

https://www.dropbox.com/request/2GcCSIYVXCqy1ru8zEOL

**Comment by flegfleg** [comment]
Uploaded!

**Comment by dmarmor** [comment]
Thank you! I'll check it out and let you know what I find.

**Comment by flegfleg** [comment]
Hi,  thanks again  for all your help!
And sorry, turns out it was not Epichrome, but my Launch Services database seemingly got corrupted around the time i installed 2.4 of Epichrome. 

I solved it with this command (see [this article](https://eclecticlight.co/2017/08/11/launch-services-database-problems-correcting-and-rebuilding/) if you have the same problem):

`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user`

**Comment by dmarmor** [comment]
Aha! Great that it's solved. I didn't think of the LS database, but of course that could cause problems. Glad you got it fixed!
