### ISSUE TITLE
Package version is missing

### ISSUE THREAD

**Issue by zenopopovici** [dmarmor/epichrome#316]
When packaging Epichrome you're somehow not correctly setting package version. This prevents automated updates via Munki and other managed software tools.

![Graffino 2021-04-05 at 23 43 47](https://user-images.githubusercontent.com/767998/113624822-c91fc600-9668-11eb-8bef-1eafbc49474a.png)

**Comment by dmarmor** [comment]
Good catch! For some reason back in 2.3.x the version seems to have been there. I've explicitly added it now during package build and it should be properly set starting with 2.4.3 (which I'll release to coincide with the next Brave version). I'll post another comment here when that happens, and would appreciate if you could let me know if everything is working the way it should on your end. Thanks!

**Comment by dmarmor** [comment]
OK, just released 2.4.3, which should have this fixed. Please let me know how it works for you!

**Comment by zenopopovici** [comment]
Fixed! Thank you!

**Comment by dmarmor** [comment]
Excellent! Thank you for reporting it.
