### ISSUE TITLE
Feature Request - Use extension as start page

### ISSUE THREAD

**Issue by asrinivasan** [dmarmor/epichrome#32]
I'm trying to figure out how to turn [Postman](https://www.getpostman.com/) into an SSB.  I can obviously load the extension into an epichrome instance but I can't figure out how to launch my new Postman SSB directly into the extension.

**Comment by breeden** [comment]
Hi Andre,

I'm not familiar with Postman. Can you tell us a little bit more about how
it works when using the extension in a full Chrome browser? Do you have to
manually launch into the extension on each use, or is it your default on
startup?

KB

**Comment by dmarmor** [comment]
I had a chance to check out Postman, and I don't think there's a good way to auto-launch it from within an Epichrome SSB. Postman is a Chrome app, not an extension, and it launches its own window with its own menubar. I poked around, but I don't think there's a way to launch it via a URL, which is what would need to happen for it to auto-launch in Epichrome.

I'm not sure Epichrome is the right environment for Postman anyway. You can create a native app shortcut for it directly within Chrome by going to the apps screen in Chrome, right-clicking on Postman and choosing "Create Shortcut..." Then click the Create button and it'll take you to the finder where it's created a Mac app that will launch Postman. When launched, it'll have its own dock icon and menubar, though it will also launch Chrome, which it requires to run properly.

I hope that helps! I'll close the issue for now, but if you have other thoughts or questions about it, feel free to reopen.
