### ISSUE TITLE
Epichrome 2.4 - Google Meet screen sharing not possible

### ISSUE THREAD

**Issue by jirkab** [dmarmor/epichrome#324]
Hi,

Many thanks for this wonderful tool !
I have created a 4 different Google Chrome instances on my computer. One is the "normal" Chrome for work and another for my other project. Let's call it Second.app.
When I hold a Google Meet meeting on the Second.app and I want to share a screen, it tells me I need to allow Screen sharing in Preferences...however, this is only on for the default Chrome and I see no way to add this Second.app to the allowed apps.

Am I missing something, is there a setting that allows this?
I just copy the meeting link to the default Chrome and do it from there, but I would like to avoid having to switch during meetings. 

Many thanks,
Jirka

**Comment by dmarmor** [comment]
Unfortunately screen-sharing permissions do not work with Chrome apps. For whatever reason, macOS treats screen recording differently from camera and mic permissions, both of which work fine on Chrome apps. But the screen recording one gets confused by the fact that all Chrome-engine apps have the same ID, and it refuses either to ask for screen-recording permission, or to grant it, even if Chrome itself has already been granted the permission. Until and unless they change that so this permission works more like camera or mic, Chrome-engine apps won't work, and if you need screen-recording you'll have to use a Brave-engine app.
