### ISSUE TITLE
Version 2.4.3 app aborted with error: "Unknown error launching engine. The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting." [main(666)]

### ISSUE THREAD

**Issue by greenhodge** [dmarmor/epichrome#326]
```
2[77936]YNAB(546)/launchapp(2872){osascript}: /Applications/Epichrome/Payload.noindex/aaron/YNAB/Launcher/Resources/Scripts/apputil.js:1182:1274: execution error: Error on line 41: TypeError: myStream.writeDataError is not a function. (In 'myStream.writeDataError($(aStr + '\n').dataUsingEncoding($.NSUTF8StringEncoding), null)', 'myStream.writeDataError' is undefined) (-2700)
*[77936]YNAB(546)/launchapp(2872): Unknown error launching engine.
![77936]YNAB(666)/abortreport(1155)/abort(1093): Aborting: Unknown error launching engine. The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting.

```

**Comment by dmarmor** [comment]
I'll look into this. Thanks for the report!

**Comment by dmarmor** [comment]
I can't replicate this exact error. I've added a bit more error-handling to routine where it occurred so if it happens again it will handle it more gracefully, but I can't quite understand why it happened at all, and can't get it to occur in my tests.

 Does it happen consistently with this app (or others) or was it a one-off?

**Comment by greenhodge** [comment]
I think it was a one-off. I often experience something funky when I first upgrade Epichrome and then launch one of my apps for the first time. This was the only time I can remember that produced an error. Find w/me to close; just trying to help by reporting when there's something to report!
