### ISSUE TITLE
Offer to create icon from an URL without the need of setting that URL for the app

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#329]
I love the comfort of letting epichrome create icon from a url. But i never set a tab/url on my apps. So to use this feature i need to first set epichrome to start with a tab/url, let the icon beeing created, then edit it again and remove the tab setting:

![image](https://user-images.githubusercontent.com/5243081/116259757-6062cf80-a776-11eb-8d43-f7b329b97c8d.png)

It would be nice if i could just give an url to created the icon without the need of this work around....

We speak about comfort ;-)

**Comment by talleux** [comment]
Now i have an app that Epichrome Scan decided to rebuild this morning, without apparent reason. 
Now the app has this icon:

![image](https://user-images.githubusercontent.com/5243081/116395341-4c75a700-a824-11eb-920e-57e6fe6af8bc.png)

I recreated the icon with Epichrome Edit and while it looks good while editing, but it still has this icon. Don't see a way to fix it without using a backup...

When closed, the app size is around 2.5MB

Any clue how to fix this?
@dmarmor do you want a copy of it?

**Comment by dmarmor** [comment]
Regarding the idea of prompting for a URL when none is provided for the app, that's a great idea and I'll add that feature as soon as I can.

As for the other comment about Epichrome Scan, I'm going to move that discussion back to issue #290.

**Comment by dmarmor** [comment]
Sorry, closed this by mistake.

**Comment by dmarmor** [comment]
This feature is in version 2.4.5, which should be up later today. Please give it a try, and if it's working well we can close this issue. Thanks!

**Comment by talleux** [comment]
@dmarmor thanks for that new feature! Works like a charm.

**Comment by dmarmor** [comment]
Great! Glad it's working. Closing this for now.
