### ISSUE TITLE
Discussion of abandonment note...

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#334]
I wanted to create a location to have further open discussions about the project abandonment note found here:
https://github.com/dmarmor/epichrome/blob/master/README.md#important-note

@dmarmor could you please further the details behind your your statement here?:
> coming changes to macOS and the Chrome extension ecosystem.

**Comment by ylluminate** [comment]
FWIW, after looking more closely at @dmarmor's options, I've found that Coherence X is the closest option to Epichrome - and provides *perhaps* an even smoother experience. Further the developer said a major release will be coming out later this month that will improve Coherence X even further. He also said that if enough people request Epichrome migration to Coherence X then they will consider adding it so that we can take our Epichrome app config's with us...

Presently the options appear to include the same Chrome + Brave options but also has the Canary option as well.

**Comment by gregschroeder** [comment]
1. NOOOOOOOOOOOOOOO!  You can't quit!  :)
2. Thanks, @dmarmor, for all that you've done - Epichrome is great, particularly this latest major release.
3. See # 1

Coherence does seem the closest, but I haven't had a chance to test it very much.  Very limited trial before you need to buy it.

It does not seem to be scriptable, and I use this 'feature' (the direct calling of `epichrome.sh`) heavily. I also use @dmarmor's suggested trick of using a zip with a known base state as a template, then using `edit` to change that base into my desired destination.  In this way, everything is copied - extensions, bookmarks, passwords, history - which is VERY useful.  I also wrote a little script to update bookmarks, etc.

I don't see any way to do that in Coherence.  Profile copying is supported but doesn't seem to include much of the above except extensions.  I don't know how I might tackle the common-base-template problem.  There are little nits, like requiring perfectly square icons, that are solvable but annoying.

As for helping maintain Epichrome, I would be open to helping, but I was unable to do the build locally for a number of reasons the last time I tried - needed Adobe InDesign or Photoshop or something, needed to be able to codesign, etc.
