### ISSUE TITLE
New empty Brave window opens when clicking dock icon, even when Epichrome app is already open.

### ISSUE THREAD

**Issue by danlurie** [dmarmor/epichrome#339]
This behavior started for me upon installing 2.4.15 and updating my apps to the new version.

OS 10.15.7

**Steps to reproduce:**
1. Open Epichrome app (homepage opens as expected in a window without tabs).
2. Switch focus to a different application (e.g. Mail, Preview, etc).
3. Click the dock icon for the Epichrome app.

**Expected results:**
Focus switches to existing Epichrome app window.

**Actual results:**
Focus switches to exiting Epichrome app window, but a new blank Brave window (with tabs) also opens.

**Comment by fulltrucker** [comment]
I am also experiencing this behavior after I updated Epichrome to 2.4.15 in MacOS 10.15.7.

**Comment by danlurie** [comment]
Possibly useful additional information: I created new SSB apps in Chromeless and am seeing the same behavior.

**Comment by danlurie** [comment]
Likely more useful: 
1. Repeating the steps outlined above will not open more and more windows. Once a blank (tabbed) window is open (in addition to the un-tabbed main window), clicking the Epichrome SSB icon in the dock will bring focus to the blank tabbed window (if it has been minimized to the dock, it will pop back out).
2. This issue can be avoided by creating a new SSB and setting it to use a tabbed window. It's almost like Chrome/Brave aren't recognizing that the un-tabbed main window exists, and tries to open a new window because it doesn't think any area open.

**Comment by dmarmor** [comment]
This appears to be a change in Brave itself starting with 1.27.108, and thus out of my control. Sorry for an inconvenience.
