### ISSUE TITLE
Feature request: Portable version (aka redirect Chrome profile)

### ISSUE THREAD

**Issue by evansthompson** [dmarmor/epichrome#34]
I've become quite enamoured of Epichrome lately. The isolation of the Chrome Profiles and extensions is pretty sweet.

I've forked the repository to see what would be required to get something quasi-portable.

**Comment by dmarmor** [comment]
Hi @evansthompson,

I'm not sure I follow what you're trying to do. Can you give me a little more detail about what you mean by "portable" or redirecting Chrome profiles?

Thanks!
  Dave

**Comment by dmarmor** [comment]
Hey @evansthompson, just checking again to see if you can give me a little more info on what you're trying to do?

**Comment by dmarmor** [comment]
Closing this for now. @evansthompson, if you can give me a bit more info on what you're looking for, I'll reopen.
