### ISSUE TITLE
New window opens when clicking dock icon on Mac

### ISSUE THREAD

**Issue by chr0max** [dmarmor/epichrome#342]
Hi,
I know that this is a brave-behaviour, but it really kills me. It is so annoying. 
Has anyone any solution, hack or workaround?
There musst be a way to disable this.

**Comment by chr0max** [comment]
It seems, that in general a click on the dock icon triggers a New Window.

**Comment by Shepstar** [comment]
I have the same problem. I know this is not under development anymore after this year but I tested the other companies and Epichrome is just so much better and slimmer. Hope you change your mind. I have the same problem, but I have this with any browser I use. Everytime i click in the dock on the app it opens the window and a second browser window. I haven reinstalled MacOS and did everything new, but this problem still occurs. So it would be great if you could help us on this or have an idea what this could cause.
Thanks.

**Comment by dmarmor** [comment]
Unfortunately, there's no way around this within Epichrome. Once an Epichrome app is running, it really is just whatever browser underlies it, Chrome or Brave. If you find a way around it for the real browser, that should also work in Epichrome apps...

**Comment by chr0max** [comment]
The behaviour is from brave, epichrome can´t change it.
