### ISSUE TITLE
Thanks for all of your work on Epichrome! 🙏✨

### ISSUE THREAD

**Issue by ixley** [dmarmor/epichrome#343]
Just wanted to leave a final comment saying thanks for all that you invested in Epichrome! I begrudgingly explored the obvious alternatives and was disappointed that each of them had their own respective shortcomings compared to Epichrome. It's fine—my use cases are not especially critical or demanding, but it helped to emphasize the great experience and functionality that you were able to achieve and prioritize with Epichrome. Wishing you all the best on your future endeavors in the new year!
✨🙏✨🙏✨🙏✨

**Comment by dmarmor** [comment]
A belated thank-you for this, @ixley! I'm sorry you haven't found a good replacement for your use case. I've had good luck myself with WebCatalog, but that's its own beast and does things a bit differently from Epichrome.

In any event, it means a lot to me to know you got good use out of Epichrome, and I'm sorry I don't have time to maintain it any more. Best wishes to you too!
