### ISSUE TITLE
Epichrome app suddenly opens default Brave install; all settings, history, plugins lost [workaround found, see comments]

### ISSUE THREAD

**Issue by kupietools** [dmarmor/epichrome#344]
All of a sudden after restarting my laptop, the Epichrome app I have used as my primary browser for ages has suddenly started only opening an ancient default Brave install. All tabs, download history, plugins, everything have been restored to match this ancient long-since-unused default Brave profile.

I tried removing Brave and it's various Library folders completely, and now the Epichrome app creates a new default Brave profile as if it was just newly installed. 

I do have some backups around but I don't even know where to fish the correct profile out of. I had a lot of things in progress, open tabs, saved session information, saved logins, etc, and I need them. Where are they stored?

**Comment by kupietools** [comment]
And just like that, after quitting and reopening the browser a few more times, it snapped back to normal and I have everything back. I did open the epichrome.app main app to see if there was an option in there to fix it, but quit without saving any change. So... until next time... ???

**Comment by dmarmor** [comment]
I wouldn't be suprised by increasing trouble using Brave-based Epichrome apps. Unfortunately, as I'm no longer updating Epichrome, the version of Brave embedded in your apps is falling further and further out of date. Since Epichrome has reached end-of-life, I'd recommend you start transitioning your apps over to an alternative (there are some resources and suggestions on the [Readme](https://github.com/dmarmor/epichrome#important-note) page).

**Comment by kupietools** [comment]
Thanks; yeh, I've been aware of the transition for a long time but unfortunately I've got things set up intricately enough that migration is not trivial. Moving to an alternative is definitely among the chainsaws I'm planning to add to the ones I'm currently juggling but until I get the time I'm going to have to make do. 

I would have thought that, having worked a few months ago, the internal brave should continue to work, seeing as how I haven't updated my system or extensions at all... the mere appearance of new versions shouldn't introduce new bugs into older ones running on the same platform and configuration as it has been previously. 

Although, in practice, there may be something I don't understand, because that is indeed happening... just for the last day or two, after I closed this, Epichrome has suddenly begun redirecting web links from any app on my system to the internal chromium instance in a completely unrelated, non-browser app that happens to include chromium internally. I might have to add that chainsaw sooner rather than later. 

At any rate, I understand you've moved on — my only thought in posting here was that hopefully other users might still be checking in here, I didn't expect a reply from you, please don't feel obligated to respond.

**Comment by kupietools** [comment]
I wanted to leave a final comment here as I've found a potential solution, in case anyone is still using Epichrome and finds this issue in the future.

1.) It seems like just opening and then quitting the epichrome.app, the one used to create the SSBs, is all by itself enough to temporarily fix a created SSB opening the wrong profile or browser. After my last comment, my epichrome-created browser began opening my old default Brave profile again, and this seemed to fix it.

2.) For those looking to migrate away from an Epichrome SSB without losing their profile, it turns out that in the settings, at least for Brve-powered ssbs, there is a "Brave sync" feature to allow syncing up profiles between multiple copies of Brave. It takes a little setup, by default I think it only shares bookmarks, but you can set it to share everything: extensions, all configuration, tabs, history, etc. It takes a while for everything to migrate, but I used this to successfully migrate all my complex setup away from my epichrome SSB back into my install of the main Brave browser, so at least everything was saved and I can work without problems for the time being. I imagine any of the other SSB-creating apps that can use Brave as an engine can take advantage of this, too.

And with that, I have, with regrets, finally migrated away from Epichrome, thankfully much more easily than I expected thanks to Brave Sync. Thank you to @dmarmor for your work and support, it was useful while it lasted and much appreciated.
