### ISSUE TITLE
command-click domain-relative links open in default browser

### ISSUE THREAD

**Issue by trak3r** [dmarmor/epichrome#37]
to reproduce:
* create SSB for github.com
* in the SSB, normal-click a repository to see it properly loads in the SSB as expected (good)
* in the SSB, command-click a repository and see it loads in the default browser rather than a new tab or window in the SSB

note: same happens if you right-click and select "open in new tab" or "open in new window" - they all result in the default browser rather than the SSB instance.

**Comment by dmarmor** [comment]
To check this out, I need to know what settings you have in the helper extension. Can you do an export of your settings and attach them for me? Thanks!

**Comment by trak3r** [comment]
github wont let me attach a .json file so here's a copy and paste of the export:

{"ignoreAllInternalSameDomain":true,"optionsVersion":"1.1.1","redirectByDefault":true,"rules":[],"sendIncomingToMainTab":false,"stopPropagation":false}

**Comment by dmarmor** [comment]
Try creating a rule something like:

*Matches this pattern:* **github.com/***
*And would open in:* **Either**
*Then open it with:* **This app**

That should make github links open in the app even if you command-click them.
