### ISSUE TITLE
Applescript Localizations

### ISSUE THREAD

**Issue by linusbobcat** [dmarmor/epichrome#38]
Hey, I've noticed you said that you couldn't find a good way to enable localizations with Applescript. I've actually managed to get localizations to work on [my project](https://github.com/linusbobcat/create-elementary-os-installer). I'll say how I did it in case you want to implement it; it's not the easiest thing to google.

You can use ``localized string "piece of text"`` to output text based on the Mac's language. To see examples on how to use them, just take a look at my applescript app. If you're using a ``tell application Finder`` (or any app) statement, make sure to add a ``tell current application`` statement before showing any dialog or anything in order for the translations to show up. Otherwise it will try to source the translations from the other app, which won't work.

Then you need to make the translations with ``en.lproj`` (en being the language code) and ``language.lproj`` where applicable. You can easily grab some from the System UI Server at ``/System/Library/CoreServices`` You can also temporarily rename en.lproj and English.lproj to test translations, and then make the testing language below English in System Preferences without changing the language of the whole Mac.

The translations are just "Localizable.strings" files inside those folders. Make sure they're encoded in utf-16. The Applescript editor, as of 10.10 doesn't like to pick up translations while you're editing the script, so you'll have to quit AppleScript entirely and relaunch it. I've noticed that OS X is quite fiddly with Applescript translations, so you might have to end up mucking about.

I hope this helps.

**Comment by dmarmor** [comment]
Hey @linusbobcat!

Thanks for the tips--good to know it's possible in AppleScript. Sounds like it's a bit awkward, but then everything is a bit awkward in AppleScript. At least it can be done!
