### ISSUE TITLE
Request: Non-sync extensions for each app

### ISSUE THREAD

**Issue by Zettt** [dmarmor/epichrome#41]
Hi,

I thought it would be a good idea if Epichrome would have some sort of mechanism to allow certain extensions to *not* sync to the other browsers through Google's syncing system. 

Practical example:

I have a browser for Instapaper. I would like to configure an extension that shows me a different font for the text that I read only for this particular app. But of course I don't want my normal browser, or the other browsers, to adopt this change. I still would want the normal font to be used. 

I hope this makes sense. Still loving the app. Good work!

**Comment by evansthompson** [comment]
I've done the same thing.  You have two options, Zett.  Your first option is to not login to the Chrome part of the Instapaper browser. Your second option is to configure Sync to not sync extensions (but do sync whatever else you want, eg bookmarks). You'd then install whatever extensions you want in the Instapaper browser, and they remain separate from your main browser.

**Comment by dmarmor** [comment]
That's exactly right, @evansthompson. In my own apps, I do log in to Chrome in preferences, and I just set sync to not sync my extensions. It then works perfectly to install whatever extensions you want in your app and it won't affect Chrome or any of your other apps.
