### ISSUE TITLE
Default icon should come from defined fluid-icon tag (see example)

### ISSUE THREAD

**Issue by wizonesolutions** [dmarmor/epichrome#45]
For example, IRCCloud outputs `<link rel="fluid-icon" type="image/png" href="/apple-touch-icon-precomposed.png">`

Would be awesome if Epichrome would try loading the URL that was given and parsing the HTML output for a `fluid-icon` and use that as the default if it was defined.

**Comment by dmarmor** [comment]
That's a good idea, I'll add it to my to-do list. (As I've been telling everyone else, though, I probably can't get to new feature requests anytime soon, as my day job has just gotten extremely busy.)
