### ISSUE TITLE
Change Icon?

### ISSUE THREAD

**Issue by bkonia** [dmarmor/epichrome#47]
Is it possible to change the icon after creating an SSB? I tried changing it by doing "Get Info" on the app and dragging a new icon to the window. However, instead of changing to the new icon, it now displays a generic PNG placeholder image.

**Comment by breeden** [comment]
As far as I know, there is no way to change the image after creating the SSB. You'll have to create a new SSB and add it when prompted.

**Comment by trak3r** [comment]
instead of dragging, try doing copy (command-c on the image file) and paste (command-v when the icon has focus in the "get info" window) that works for me.

**Comment by dmarmor** [comment]
That's basically right, @trak3r, though I doubt the new icon will survive the app being updated when a new version of Epichrome is installed. Not 100% sure, but as of now, the safest solution is the one @breeden suggested--just recreate the SSB.

Note that if you do this, if you want to keep all your settings from the old SSB, the best course of action is to completely remove the old one from your computer first (trash it and empty the trash, or use rm in the terminal). Then create the new one with the exact same long and short names as the old one.

Another alternative, of course, is to just copy the settings directory from the old SSB to the new one (these are found in ~/Library/Application Support/Epichrome/Apps/).
