### ISSUE TITLE
Stops working with Chrome update 48

### ISSUE THREAD

**Issue by bramvandenbulcke** [dmarmor/epichrome#48]
I'm an active user of Epichrome. I really like the application and the implementation. 

Whenever there's a Chrome update, the SSB updates. This is great! But with Chrome 48 all my SSB's crash and I can't open them. 

![screen shot 2016-01-29 at 11 36 38](https://cloud.githubusercontent.com/assets/8631196/12673398/d36dd41a-c67c-11e5-99e8-e0c693703848.png)
![screen shot 2016-01-29 at 11 36 44](https://cloud.githubusercontent.com/assets/8631196/12673402/d693f458-c67c-11e5-9c90-0bdf9a8a1eec.png)

**Comment by alanthing** [comment]
@bramvandenbulcke see #46

**Comment by dmarmor** [comment]
Hi @bramvandenbulcke, did updating to 2.1.8 solve this for you?

**Comment by bramvandenbulcke** [comment]
Yes, it did. Problem solved. Thanks!

**Comment by dmarmor** [comment]
Excellent, thanks @bramvandenbulcke, good to hear.
