### ISSUE TITLE
app crashes after updating chrome

### ISSUE THREAD

**Issue by arvindvenkataramani** [dmarmor/epichrome#50]
When starting an app today, I got a message that Chrome was updated, and the app needed to restart. On clicking Ok, the app restarted, but immediately crashed. I have tried removing the preferences and saved states, but the app now just crashes immediately on opening.

the crash report is attached [dump.txt](https://github.com/dmarmor/epichrome/files/112912/dump.txt)

I'm using v 2.18, btw.

**Comment by arvindvenkataramani** [comment]
I'm running Chrome version 48.0.2564.97 (64-bit);
On quitting chrome, installing v 2.19 and re-creating the app, it has stopped crashing.

**Comment by alex1529** [comment]
getting the same result and I also recreated the app with also the same result

**Comment by breeden** [comment]
I think it's usually a safe bet to restart Chrome after updates, as mentioned by @arvindvenkataramani. @alex1529, did doing so fix your crashes? Otherwise, please provide step by step instructions for others to recreate the error.

**Comment by adamors** [comment]
Restarting didn't help. Simply updating to the newest version is enough to reproduce. Tested on 10.10.5 and latest 10.9 version of OS X.

**Comment by breeden** [comment]
I'm running the following configuration:

OSX 10.9.4
Chrome 48.0.2564.97 (64-bit)
Epichrome 2.1.8

Upon first run after the latest update, I observed the same loss of icon described in #51. Restarting the SSB restored the custom icon, and all is well. (I'm not getting any crashes.)

Can anyone else help narrow this down?

**Comment by adamors** [comment]
Ok, deleted Epichrome and downloaded the 2.1.9 binary from GH. After the apps updated the runtime all is ok.

**Comment by zeartist** [comment]
I also had similar issues. I had a few SSBs built with makechromessb 2.0.1. Chrome updated and all my SSBS (about 8 of them) were not launching at all and crashed silently (no error code, nothing to help debug). Eventually I tried using the command-line:

`open -a "SSB App Name"`

I'm not sure if it helped or not, but for me it did. For a few I'm still getting an error code (see my other issue). The other ones worked eventually, I was prompted at first to upgrade the SSB app (I downloaded and installed the latest Epichrome dmg), did so, and then re-launched the apps again. So after 2 launches, it finally did the trick and now it works! 

Just posting this in case it might help others...

**Comment by zeartist** [comment]
Ok I was able to workaround this issue, mostly... It seems to be a permissions problem. Perhaps there should be a check beforehand in the code and a more useful error dialog if Epichrome notices it does not have these permissions, just an idea...

I tried 
sudo open -a "The SSB Name"

I had 3 / 8 of my SSBs still refusing to launch. With this workaround, now I'm only left with a single one who is still stubborn. Hope it helps...

**Comment by dmarmor** [comment]
I have a fix for the icon problem (keep an eye on issue #51 for that). That fix should be up very soon. If you're updating very old apps from the makechromessb days, it just may not work. I don't have the resources to test updates from those versions at this point, so your best bet might be to recreate those apps with the latest Epichrome. Sorry for the inconvenience!
