### ISSUE TITLE
Error launching

### ISSUE THREAD

**Issue by zeartist** [dmarmor/epichrome#52]
I have a few SSBs that were built with makechromessb 2.0.1. It worked fine previously, but recently Chrome updated to Version 48.0.2564.97 (64-bit) and afterwards they were all crashing silently at launch. I updated to Epichrome latest (2.1.9) using the dmg and after clicking the upgrade ssb prompt at startup and re-launching again I managed to start most (5/8). But some still refuse to launch. After digging a bit, it gives an error code when launched from command-line:

`open -a "SomeSSB"`
`LSOpenURLsWithRole() failed for the application /Applications/SomeSSB.app with error -10810.`

Also, from Finder and dock, I get this error dialog:

`The application “SomeSSB.app” can’t be opened.`

**Comment by JonathanAquino** [comment]
I'm seeing a similar issue: when I click the SSB, the icon appears for a second in the dock then disappears.

When I run it from the command line as above, I don't see an error message though:

> $ open -a "Toodledo"
> $

**Comment by dsernst** [comment]
Came to report same issue

**Comment by zeartist** [comment]
@dsernst Open your Applications folder, right click on Epichrome and choose "Get Info", you'll see version number there. 

While I'm at it, I'm on OSX 10.11.1.

**Comment by dsernst** [comment]
Ah yes, I missed the 2.1.7 update that fixed this. Upgrading to 2.1.9 seems to have fixed my apps, now. Apologies for the confusion and cluttering this Issue.

**Comment by zeartist** [comment]
I was able to workaround this issue, partially. I tried this:

`sudo open -a "SomeSSB"`

So I imagine perhaps it was some permissions problem. I'd suggest Epichrome should maybe check for these permissions and adjust or perhaps display a useful error dialog if it can't get those permissions. just an idea. I still can't start one SSB, but it's not important anyway. :+1:

**Comment by JonathanAquino** [comment]
I switched to using nativefier - it is working well.

**Comment by dmarmor** [comment]
Hey guys, sorry for the inconvenience. There definitely shouldn't be permission problems with running an Epichrome app day-to-day. They're supposed to be created owned by whichever user creates them. It is possible that there are issues in updating from much older versions of Epichrome, and in those cases, probably makes most sense to recreate the app from scratch.

I'll close this issue for now, but if you continue getting problems, I'm happy to reopen and try to fix it.

@JonathanAquino -- I checked out nativefier and it looks pretty cool. It may be a better solution for some cases. For one thing, it appears to have some facility for adding icon badges (though I couldn't figure out how to do it). It may be more limited than Epichrome for other uses, though, as it doesn't allow multi-tab SSBs or the use of Chrome extensions, as far as I can tell.
