### ISSUE TITLE
get info on version 2.1.9 reports version 2.1.6 after copying into /Applications

### ISSUE THREAD

**Issue by jab** [dmarmor/epichrome#54]
1. download and mount the 2.1.9 dmg
1. get info on Epichrome.app in the mounted disk image
1. observe version 2.1.9 reported
1. drag and drop to copy into /Applications
1. get info on /Applications/Epichrome.app
1. observe version 2.1.6 reported
1. wtf?

![screen shot 2016-02-05 at 15 06 14](https://cloud.githubusercontent.com/assets/64992/12857811/3e2ffce0-cc1a-11e5-8d6e-e1814177071d.png)

**Comment by jab** [comment]
note size, created, and modified are all identical

**Comment by dmarmor** [comment]
This is probably just a matter of Spotlight and/or Finder not being updated. I've definitely seen this behavior myself. I'm going to close the issue for now on the assumption that after a few days it has resolved itself. If not, please let me know and I'll reopen.

**Comment by jab** [comment]
Still seeing this. I even tried forcing a Spotlight reindex with `sudo mdutil -E /` and still no dice.

**Comment by dmarmor** [comment]
Can you do me a favor and take a look at Epichrome's Info.plist file? In the terminal, find Epichrome.app, and then look at Contents/Info.plist. If you search it for **CFBundleShortVersionString**. You should see something like this:

```shell
        <key>CFBundleShortVersionString</key>
        <string>2.1.10</string>
```
If that shows the correct version, then you have the correct version, no matter what Finder says. Very strange that it's still not updating (even across reboots, I assume?) but I don't think it has anything to do with Epichrome specifically. It seems like a Spotlight problem of some kind...

**Comment by jab** [comment]
Info.plist shows 2.1.9. I haven't rebooted in a while and can't right now, unfortunately.
