### ISSUE TITLE
File menu still says "Google Chrome"

### ISSUE THREAD

**Issue by peterpk** [dmarmor/epichrome#56]
I love Epichrome!  It's exactly what I've been looking for.  We have a work website that makes Fluid.app crash, but works fine in Chrome, so Epichrome is perfect!

With one cosmetic issue, of course. :)  Though my selected Application name shows up fine in the Dock and in the Menu bar, under the application menu itself, you still see entries like "About Google Chrome", "Hide Google Chrome", and "Quit Google Chrome".  Any chance there might be a way to rename those menu items?

Feel free to mark this as very low priority...

**Comment by dmarmor** [comment]
Thanks! Glad Epichrome is working for you. As for this cosmetic issue, unfortunately I don't think there's anything I can do about it. All Epichrome really does (beyond the helper extension) is create a nice wrapper for an instance of Chrome itself. This is why it's able to run Chrome extensions, for instance. So when you run an Epichrome app, you really are just running Chrome and in the poking around I've done, I haven't found a clean way to change any menu text.

I'll close this issue, but I feel similarly to you about that menu text, so if I ever do find a way to fix it, I definitely will!
