### ISSUE TITLE
App icon is stil changing

### ISSUE THREAD

**Issue by aghuwalewala** [dmarmor/epichrome#57]
I am on Epichrome 2.1.10.

Within my SSB, if I open a new browser window and then download a file, the app icon still changes. This time to a normal Google Chrome icon instead of the specific one I had selected while creating the SSB.

**Comment by dmarmor** [comment]
Was your SSB created with an earlier version of Epichrome and then updated to 2.1.10? If so, this is likely just a sort of leftover side effect. Sometimes it can take a while for OSX to realize that app bundles have been updated. I've found that rebooting often fixes it. If not, you can try dragging the SSB to a different folder, and then dragging it back. Sometimes that works.

If none of that works, there are more drastic steps you can take to force it to update, but try those first and let me know if you're still having trouble. Thanks!

**Comment by dmarmor** [comment]
Is this still a problem for you? I'll close the issue for now, but if you're still having problems, let me know and we can reopen.

**Comment by Colin5000** [comment]
I am having exactly this problem. I've deleted my SSB and created a new one, I've rebooted, but still the custom icon disappears every time I download a file and is replaced with the standard Chrome icon, except with a circle and slash over the top of it.
![image](https://cloud.githubusercontent.com/assets/20413931/16757337/95824920-484e-11e6-81a4-c811dabd71a0.png)

**Comment by Colin5000** [comment]
My apologies - I was using 2.1.9. I've downloaded 2.1.11 and recreated the SSB with it, and the problem seems to be gone.
Thanks!

**Comment by dmarmor** [comment]
Great, glad it's working! For future reference, you shouldn't have to recreate your SSBs when you update Epichrome. When you install a new version of Epichrome (assuming you delete the old version), your SSBs should notice and update themselves next time they launch. (In the case of 2.1.11, I found that I also had to reboot to get the icon fix to take hold.)
