### ISSUE TITLE
Suddenly can't run new or existing epichromes

### ISSUE THREAD

**Issue by treyharris** [dmarmor/epichrome#58]
My first clue was when the Dock icon for my Inbox SSB was replaced by a Chrome icon with a "don't go there" icon over it. The Inbox epichrome continued to work, though, until I restarted it. Now it fails.

I even created a new epichrome, it similarly failed. Crash reports have been saved, so I'm attaching one.
[systemstatsd__Treys-MacBook-Pro.crash.txt](https://github.com/dmarmor/epichrome/files/141310/systemstatsd__Treys-MacBook-Pro.crash.txt)

Any idea? No epichrome, new or old, is working at the moment.

**Comment by dmarmor** [comment]
Hmm. Is this upon updating your SSBs to 2.1.11? Or did this just suddenly start happening without installing a new version of Epichrome?

**Comment by rschend** [comment]
If it helps, over the past several days (while troubleshooting #55), I've created, deleted, and re-created well over 100 instances of Epichrome, on both Yosemite and El Cap, (not to mention fiddling with a ton of stuff under the hood, while having zero idea what I'm doing) and haven't experienced any crashes. Only the icon issue.

@dmarmor , should he clean out his Epichrome folder in the Application Support dir? I'm not a dev, so it took me awhile to figure out that's where you were storing SSB prefs, etc. Clearing out that folder was what allowed me to test without wondering if my results were just a result of leftover data and cruft.

**Comment by dmarmor** [comment]
It can't hurt to try starting with a fresh profile, so definitely worth trying. In this case, I suspect the crashes might be happening even before the SSB launches Chrome, in which case a fresh profile wouldn't help--but even knowing that would tell us something.

The main thing I need to know first is whether the crashing @treyharris is seeing started with updating to 2.1.11 or not...

**Comment by treyharris** [comment]
@dmarmor: It did seem to coincide, but I'm not sure if it did precisely. I
did try uninstalling the Epichrome I'd built myself, removing
`~Library/Application Support/Epichrome`, and installing the one from
homebrew-cask, removing the .app and recreating it, but it also crashes on
startup with similar crash report.

**Comment by treyharris** [comment]
@dmarmor: It did seem to coincide, but I'm not sure if it did precisely. I did try uninstalling the Epichrome I'd built myself, removing `~Library/Application Support/Epichrome`, and installing the one from homebrew-cask, removing the .app and recreating it, but it also crashes on startup with similar crash report.

**Comment by dmarmor** [comment]
It's possible I'm misunderstanding the problem. You're saying that Epichrome.app itself is crashing? Not just SSBs created with Epichrome? That is very puzzling, since Epichrome is just an AppleScript app. That would mean the AppleScript runtime itself is crashing somehow...

**Comment by treyharris** [comment]
Sorry, I meant the SSB. See the attached crash [from above](https://github.com/dmarmor/epichrome/files/141310/systemstatsd__Treys-MacBook-Pro.crash.txt).

I'm about to get rid of the Mac that's happening on, and my new Mac isn't showing the issue, so unless you're interested in tracking it down feel free to just close this. I'm a bit distressed that I can't seem to get a zap-everything-and-reinstall to even work, though, it bothers me not to understand where the stink is coming from....

**Comment by dmarmor** [comment]
OK, sounds like it may be some mysterious gremlin. My only reasonable theory (and this is sort of a long-shot given what you've told me) is that it could have to do with Chrome's auto-update. Is it possible you have "auto-update for all users" turned on in Chrome?

Once it's turned on there's no way to turn it off in Chrome's settings, but you can tell by going to /Library/Google. I've outlined the procedure in the README (along with a way to get rid of it), so maybe check and see if that's turned on? If so, that can definitely cause SSBs to become non-functional.

But all that said, it doesn't quite sound like what you described, so I'm not that hopeful.

Anyway, I'll close the issue for now, but if it starts cropping up on your new Mac (and congratulations on a new Mac!) we'll open it up again and get to the bottom of it. Sorry for the trouble!
