### ISSUE TITLE
After updating to version 49.0.2623.75 of Chrome Epichrome apps won't launch anymore

### ISSUE THREAD

**Issue by Zettt** [dmarmor/epichrome#59]
Here's a pastebin of the crash: http://pastebin.com/CfRkDds9

**Comment by dmarmor** [comment]
Hmm. Just updated myself and it's working fine for me. Assuming you're using 2.1.11 and not an earlier version of Epichrome? Do you have auto-updates turned on for all users? If so, please see the Readme for instructions on turning that off.

If not, then I'm not sure what's going on. Are you able to create a new SSB that works?

**Comment by Zettt** [comment]
Works. I didn't know there was a new version of Epichrome. Is it hard to have an update system for it, e.g. Sparkle or something?

**Comment by dmarmor** [comment]
You're right--it would be good to have some kind of update system. I can't use Sparkle, because Epichrome apps aren't Cocoa apps. But I've added it to my to-do list to add at least some kind of notification system that could prompt the user when a new version is available. Thanks!
