### ISSUE TITLE
Redirect links to other (SSB) apps ?

### ISSUE THREAD

**Issue by APMOadmin** [dmarmor/epichrome#61]
tried to redirect links for a specific website that I handle in another SSB to that SSB instead of the default browser - is that possible at all and where/how would I add the other apps ?
(don't mind if it's now via the UI at this point)

**Comment by dmarmor** [comment]
You'll need to get Browser Fairy (it's on the app store). Make that your default browser, and then you can use it to set up rules to redirect URLs to different browsers based on their addresses. It works great for me, and I know other Epichrome users have had good results with it too.

(Note that you will need to have set up your Epichrome SSBs with the "Register as a browser" option for them to appear as options in Browser Fairy.)

**Comment by APMOadmin** [comment]
works like a charm - thanks for the hint !
