### ISSUE TITLE
Creating new SSB's has extra ignorable "Choose Application" step

### ISSUE THREAD

**Issue by treyharris** [dmarmor/epichrome#63]
I've recently (just since upgrading my Epichrome to v2.1.11) been getting the following dialog _after_ the seven usual questions:
![image](https://cloud.githubusercontent.com/assets/97895/14564720/d8458d24-02f5-11e6-8c0f-24fee915474d.png)

I'm not sure where this comes from, but the SSB I just created is _not_ in the list. Not knowing what to do, I clicked "Cancel"... and as far as I can tell, that resulted in no problem. Subsequent launches of the SSB do not cause this dialog to appear.

**Comment by treyharris** [comment]
And, as i mentioned there, this could be related to #62.

**Comment by dmarmor** [comment]
Hmm. That dialog is supposed to pop up when Epichrome can't find a version of Chrome to link to. I'm not sure why it would pop up like that, and especially why cancelling it wouldn't cause Epichrome to abort the creation process. Is it reproducible? Does it now happen every time you try to create an SSB?

Usually that dialogue should only appear if you have Chrome installed in a strange place, and even then only if you have Spotlight turned off so Epichrome can't use that to search for Chrome. Are any of those the case on your system?

**Comment by dmarmor** [comment]
Did this problem go away for you? I'll close the issue for now, but if it's still happening, let me know and I'll reopen.
