### ISSUE TITLE
How to alter default sites that are opened initially?

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#67]
As you understand, we have the option to set a default or a number of default tabs to open upon app launch.  How can we edit these?  Is there a way to do this through the Epichrome extension or do we need to edit the plist?

**Comment by dmangin** [comment]
Hi, you can do this by opening package content, then navigating to Contents/Resources/Scripts. There you will find a config.sh file.
Just edit this file (using vi, or whatever you may like), and update the line beginning with "SSBCommandLine=".
Between the () you can add as many urls as needed, separated with spaces.
Example :
`SSBCommandLine=( https://mydomain.com http://mydomain.net http://mydomain.me)`

**Comment by ylluminate** [comment]
Hey that's great. Thanks so much, I was thinking they were in the home folder app prefs path vs this.

**Comment by dmarmor** [comment]
If you want an Epichrome app whose tabs you can edit once it's been created, probably the best way to do that would be to create an app with Browser Tabs, and then just immediately click "Done (Don't Add)." Then the app you create should just obey the settings in Chrome, so you can set whatever home tabs you want and then change them later in Chrome, and it'll change its launch behavior.

Hope that helps!
