### ISSUE TITLE
Feature Request: enable way to modify keyboard shortcuts

### ISSUE THREAD

**Issue by lianos** [dmarmor/epichrome#69]
I've set up an SSB for an application which expects to catch keyboard shortcuts that Epichrome is listening for, in particular: ⌘-⇧-L.

It would be handy if we could bind Epichrome's app-style/tab-style toggle to a different key combination.

**Comment by dmarmor** [comment]
Yes, this is definitely a priority on my to-do list. For now if it's a real problem you could just disable the extension (of course losing the ability to toggle the window style and route links to the default browser).

Closing the issue for now, but next time I have time to do an update on the extension I'll add this in (it may be a while as my day job doesn't leave much time for Epichrome)...
