### ISSUE TITLE
⌘L to access URL bar works inconsistently

### ISSUE THREAD

**Issue by jbyler** [dmarmor/epichrome#72]
For an "App Window"-style Epichrome SSB, when it's in Browser Tab Mode (with the URL bar visible): sometimes typing ⌘L selects the URL bar, and sometimes it hides the URL bar (switching back into App Window mode).

Given that ⌘⇧L consistently switches back and forth between App Window Mode and Browser Tab Mode, I don't think there's any need to have ⌘L also sometimes switch into App Window Mode.  I would prefer for ⌘L to consistently select the URL bar.

How to reproduce: 

1. Use Epichrome to make an SSB in App Window mode, with https://google.com as the URL.  
2. Open the SSB.  Observe no URL bar.
3. Type ⌘L.  Observe the app switch into Browser Tab Mode, without selecting the URL bar.
4. Type ⌘L.  Observe the URL bar is selected.
5. Press return.  Page reloads.  URL bar is still visible.
6. Type ⌘L.  Observe the app switch into App Window Mode

Note that just before Step 4 and just before Step 6, the app looks exactly the same: google search is visible, and a URL bar is at the top of the screen.  Step 4 and Step 6 are the same action, but different things happen.

Thanks for considering!

**Comment by jbyler** [comment]
I found one temporary workaround: disabling the Epichrome Extension solves the problem.  But it also disables other important Epichrome features.

**Comment by dmarmor** [comment]
Yeah, that's a bug in how Epichrome thinks it's in app mode or not. You're right--probably best to delete that Cmd-L shortcut. Longer-term my intention has always been to make that shortcut customizable, but for now I'll work on deleting the Cmd-L...
