### ISSUE TITLE
Error creating SSB

### ISSUE THREAD

**Issue by neilio** [dmarmor/epichrome#78]
When I complete the process of creating a new SSB I get a crash / error and nothing is created.

Creation failed: Error filtering InfoPlist.strings (Traceback (most recent call last):
  File "/Applications/My Epichrome App.app.5049/Contents.25522/Resources/Scripts/strings.py", line 52, in <module>
    print sys.exc_info()[1][1]
IndexError: tuple index out of range)

**Comment by kkthompson** [comment]
Same here.

**Comment by johngrimes** [comment]
This just started happening for me when I installed Chrome from the dev channel.

The version of Chrome I am running is 54.0.2816.4 dev (64-bit). Epichrome 2.1.11.

**Comment by dmarmor** [comment]
New release is out with vhf's fix. Note that I'm still not sure Epichrome will consistently work with Chrome dev channel releases. I'm not on that channel and only test Epichrome apps against the release channel.

**Comment by araxara** [comment]
I'm having this problem now with the non-dev Chrome [Version 54.0.2840.71 (64-bit)]

**Comment by smaccabe** [comment]
I am as well.

**Comment by smaccabe** [comment]
To expand this is the error (which is the same as above)  Creation failed: Error filtering InfoPlist.strings (Traceback (most recent call last):
  File "/Applications/Inbox.app.14147/Contents.1369/Resources/Scripts/strings.py", line 52, in <module>
    print sys.exc_info()[1][1]
IndexError: tuple index out of range)

**Comment by dmarmor** [comment]
Hi guys, this is the same as issue #85. There's a workaround in that thread. Also, if you can wait a bit I'm working on a script that will automate some of these workarounds...

**Comment by smaccabe** [comment]
Resolved - by running the script found in the latest dmg after installing the new epichrome.  Thanks a lot!
