### ISSUE TITLE
Send links to any browser

### ISSUE THREAD

**Issue by linesarefuzzy** [dmarmor/epichrome#79]
A great additional feature would be for the link handler in the helper extension to be able to send links to any browser on the system rather than just the default browser. That way you could set one of your epichrome apps to be the default browser and it could route links to either another epichrome app based on URL or default to your browser of choice. It would just be a matter of expanding the "open it with" dropdown to include all browsers registered in the OS (though I have no idea how to get that list or how hard it is). 

Thanks for a really great app!

**Comment by dmarmor** [comment]
I looked into this possibility, but it's very difficult (if not possible to achieve through a Chrome extension. The best (not free, but pretty cheap) solution I've found, and the one I use, is to install Browser Fairy (available on the app store) and make that your default browser. Browser Fairy can set up rules for routing links to whatever browser you want. It works flawlessly for me.

**Comment by linesarefuzzy** [comment]
Thanks for your response. What about a browse button that would allow you to select any application?

**Comment by dmarmor** [comment]
I looked into this too, but different browsers have different interfaces for opening links. It might be possible to make it work, but it would have to be kind of kludgy. Redirectors like Browser Fairy have handled every situation I've ever needed. Is there some scenario you have in mind that would require direct opening from the extension?
