### ISSUE TITLE
Local HTML app instead of URL to website?

### ISSUE THREAD

**Issue by sull** [dmarmor/epichrome#81]
Is there a way to use this to run a single html file as the app instead of pointing to a remote URL (website)?

**Comment by dmarmor** [comment]
That should work fine. Just use the URL of the local file as the app URL. It'll look something like this:

```bash
file:///Users/xxx/Desktop/app.html
```

The easiest way to get the URL would be to use File->Open File... in Chrome and browse for it, then copy the URL from the location bar and paste it into Epichrome.

Hope that helps!
