### ISSUE TITLE
Open all as window, not tabs?

### ISSUE THREAD

**Issue by dsemaya** [dmarmor/epichrome#82]
Is it possible to configure Epichrome to open all browser windows as windows, not tabs?  I'm using it for Gmail, Drive and Docs.  It would be great if I could completely hide the tab and toolbar in all windows.

Thanks.

**Comment by dmarmor** [comment]
There isn't a way to set Epichrome to start up with multiple app-style windows. The only way to start with multiple URLs is with tabs. The philosophy behind Epichrome is really to create single-use apps. It was never designed to run multiple different services in the same app.

I'm curious--what is your hoped-for functionality? Why not just create separate Epichrome apps for Gmail, Drive and Docs?

Thanks!

**Comment by dsemaya** [comment]
I already have separate apps for each, but each of those apps uses multiple windows. 

For example, Gmail displays notifications for new mail.  Clicking on a notification opens the new message in a separate tabbed window. I want all windows to be non-tabbed.  Another example is opening an existing document in Drive.  I'd like for it to open the Docs app with each document in its own separate, non-tabbed, window.  That way the apps feel more like native desktop apps.  

This Chrome extension can open an existing window as a "popup" window, which doesn't have the tab bar.  Using it repeatedly is cumbersome.  Chrome also forgets about these windows when it crashes.  

Any way to do this via Epichrome would be appreciated.

**Comment by dmarmor** [comment]
I'm not sure there's a good way to manage it, but I'll add it to the to-do list and take a look next time I'm working on the helper extension. (At the moment my day job is pretty insane, so I'm only addressing urgent bugs.) Thanks for the info!

**Comment by Akahadaka** [comment]
I've only recently discovered Epichrome and it's great!! But I've also come across this scenario where a page like Google Drive opens a document in a tabbed window. It'd be great if each of those sub-windows didn't have tabs and address bar, etc. (Unless the user specifically selects tabs)

Alternatively/Additionally see this example: I use multiple Chrome accounts (i.e. home and work). Something like Google Keep works beautifully as flipping between accounts remains in the same tab (and by extension Window), however something like Google Inbox uses `target="_blank"` links on switching accounts (yes, very consistent of them, I know). Anyway, would there be a way to extend the helper to force pattern matching links to ALWAYS open in THIS tab (window)?

A fantasy addition would be to have Epichrome Apps be aware of each other. Thus being able to use the helper to actually target specific apps, not just 'this app'. TBH I've not given the practical aspects of this scenario much thought.

**Comment by dmarmor** [comment]
Hi @Akahadaka!

Welcome to Epichrome, and I'm glad you're finding it useful. I'm working (very slowly) on an update that will incorporate a lot of what you're asking for, in particular, more flexibility about whether new tabs open as Chrome-style tabs or app-style windows. I'm also experimenting with whether it'll be feasible to force certain links to open in the current tab even if they want to open externally.

I don't have any plans to make Epichrome apps aware of each other. I've found that this functionality is already achievable through Browser Fairy, which I use myself and have found to be very stable and effective. You have to make it your default browser, and then it very effectively routes links to whatever browser you want based on URL patterns or other criteria. It's available in the App Store (not free, but pretty cheap).

Hope that helps!
