### ISSUE TITLE
Chrome 55

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#83]
Hearing the news of Chrome 55 beta potentially halving memory consumption has gotten some of us excited. Before I take the plunge, I wanted to know if there are any known problems with Epichrome and the beta release at present for upcoming 55?

**Comment by dmarmor** [comment]
I've had a few people report issues with the Chrome beta channel, so be aware that using it may break your Epichrome apps. I suspect that there's something different in the Info.plist for Chrome beta releases, or something like that.

Thus far, Epichrome has worked perfectly with all final Chrome releases, so I would guess once Chrome 55 comes out, Epichrome will happily update to use it. If not, I'll fix it as fast as I can. I use my own Epichrome apps daily, so I'll be as unhappy as anyone if they break!

Thanks, and if you do install the beta, please let me know how it works for you.

**Comment by ylluminate** [comment]
Thanks for the input!  I went ahead and gave it a shot and it blew up on me with an app.  It seemed to do something holistically to the app insomuch that it wouldn't even start after reverting back to Chrome stable.  I ended up having to copy the Epichrome app back over from backup.  I didn't have a chance to dig into it any further, but would be happy to poke about and see what the differential may be later here if you'd like.

**Comment by dmarmor** [comment]
Yeah, I was afraid of that. I'm not sure what's different in their beta releases. If you have time to poke around, I'd love to know. I have so little time to work on Epichrome these days I haven't had time to look into it myself. Thanks!

**Comment by ylluminate** [comment]
Hmm, before I dig into the 55 issue, 54 was just autoupdated this morning.  Everything seems to be good, except for one app.  Each time I update it, it blows up; loses its icon and won't start.  Can't seem to get any output on console and when I run it from the shell it runs "properly" and I just get the following output:
```
Unable to display alert with message: New version of Google Chrome found (54.0.2840.59). Updating app...
Unable to display alert with message: Unable to update app to new version of Google Chrome. (Unable to display dialog box!) It may or may not run properly.
```

Oddly I've updated a few other Epichrome apps now without a problem, it just seems to be this.  I can reproduce it since I have a backup of the app, but I'm not sure how to get appropriate output here to track down what may be going wrong...

**Comment by ylluminate** [comment]
Now I've found another Epichrome app that's behaving the same way so I suspect this is a bigger issue than I first anticipated.

**Comment by dmarmor** [comment]
I think I found the problem (some of my own apps that I hadn't run in a while had the same issue). The problem is trying to run an app that hasn't been run since you installed Epichrome 2.1.12 or later. The 2.1.11 and earlier engine doesn't work with the latest Chrome. Check my last comment on issue #85 for a couple suggested workarounds. Not ideal, but hopefully they'll get you back up and running...

**Comment by ylluminate** [comment]
@dmarmor good news is that ßeta channel seems to be working now with the most recent updates to Epichrome so we can take advantage of the new JS VM memory reduction for macOS...
