### ISSUE TITLE
Creating a new application fails

### ISSUE THREAD

**Issue by gnyrd** [dmarmor/epichrome#84]
Trying to create any new app now fails.

![untitled 3](https://cloud.githubusercontent.com/assets/2048411/19387792/ba55ae16-91d9-11e6-83a7-0e50124e08ac.png)

![untitled 4](https://cloud.githubusercontent.com/assets/2048411/19387797/c74e57bc-91d9-11e6-94de-8a4076643cc4.png)

**Comment by dmarmor** [comment]
I believe you're using an old version of Epichrome, 2.1.11 or earlier. If you install the latest, you should be able to create new apps just fine. I'll address the issue of existing apps in the other thread you created.
