### ISSUE TITLE
Love Epichrome, how can I make a donation?

### ISSUE THREAD

**Issue by alatteri** [dmarmor/epichrome#88]
As the subject says, how can I donate some cash to the effort.  Epichrome is crucial to my efficient workflow.

**Comment by dmarmor** [comment]
Hey, thank you guys! I really appreciate knowing the Epichrome is useful to people. I've kind of resisted taking donations in the past as my time to work on this has been so limited and I didn't want to frustrate donors with slow updates.

But Epichrome does incur a few costs (like the domain for app IDs, and I've been thinking about getting licensed for code-signing so people don't have to work around Apple's security to launch Epichrome the first time), so I'll look into whether there's a clean way of putting a donate button on the front page. I'll keep you posted.

Thanks again!

**Comment by dpickett** [comment]
also a big fan and would be interested in donating. Keep up the awesome work, and I'm super thankful for the recent updates.
