### ISSUE TITLE
Issue with Trello SSB card backs redrawing at random

### ISSUE THREAD

**Issue by admiraljuice** [dmarmor/epichrome#89]
Epichrome version 2.1.13; Chrome version 54.0.2840.71

I made a "Trello" app with Epichrome, but an update of Chrom had broken it so it wouldn't start.  This has happened before, and all I've had to do was update Epichrome and remake the Trello app, so I did that again the other day.  All seemed well, but now when I open a card it gives me trouble;  the text disappears and reappears, seemingly at random, though movements of the mouse seem to trigger

Here's a short video of the issue I put on Youtube: https://youtu.be/1KKU2gU5BaU

**Comment by admiraljuice** [comment]
Sorry, looks like this is an issue with Chrome as I'm seeing the same behavior in the regular Chrome browser as in the SSB

**Comment by dmarmor** [comment]
Gotcha, thanks for the update!
