### ISSUE TITLE
Unable To Recreate App As App Window

### ISSUE THREAD

**Issue by imtwotired** [dmarmor/epichrome#90]
I am trying to recreate my apps after the update and I would like to create some of the apps that I previously made as Browser Tabs as App Windows now; however, Epichrome seems to be holding on to the old styling. I've deleted the old profiles from within the Library and I've turned off Spotlight indexing but still am not having luck.

**Comment by imtwotired** [comment]
Or maybe it's just not making any App Windows now. Is anyone else having trouble with that?

**Comment by dmarmor** [comment]
Hmm. I'm not having any trouble making app-window style apps with the latest versions of Epichrome (2.1.14 is probably the one you've been using--I just now released 2.1.15 with a very tiny bug fix in it, but that should make no difference).

Is it possible that you somehow are still running the old browser-tab version of the app? Deleting the profiles in the library should make no difference--the style of the app is baked into the app itself...

Let me know if you can give me any more info about this!

**Comment by dmarmor** [comment]
Hey @imtwotired, I'm closing this issue for now, but if you continue having this problem, let me know and we can reopen. Thanks!
