### ISSUE TITLE
Update window even after update?

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#91]
Getting an odd issue where every time I open an Epichrome app it asks me if I want to update to 2.1.15.  This happened with 2.1.13+ as well, but I ignored it knowing of the problems.  I have manually updated to 2.1.15 so that shouldn't be an issue, but yet here it is:

![Window](https://cl.ly/341U0l042M1L/Image%202016-11-02%20at%2010.31.11%20AM.png)

**Comment by dmarmor** [comment]
To clarify, does this happen with each app even after you click Update and it successfully updates itself?

**Comment by ylluminate** [comment]
Well... It has, but now it does not seem to be.  Initially this would appear at each time I opened the window and when I would click `Update` it would load up the github release page on my GitHub Epichrome browser vs actually doing anything... but now it seems to have stopped.  I can't say this is the case for all of them since I have so many Epichrome apps and it will take some time to test, but perhaps I've been confused for this very reason.  I'll let you know if I can reproduce it reliably!

**Comment by dmarmor** [comment]
Yes, keep me posted! It's possible you were being overwhelmed by two similar-looking but different things going on. There was a minor bug in 2.1.14 that caused apps not to realize they had been updated for purposes of checking github for new releases. So even after updating to 2.1.14, you might still get a window saying there was a new release, 2.1.14, on github.

The image you posted is of the other update window, the one that appears when you've installed a new release of Epichrome and the apps realize they're out of date with that version. That one you should only see once if you click Update. In that case, the app should update itself and then be happy.

So yeah, if you're seeing some other behavior, like multiple runtime update windows or something, that would be another bug...let me know!

**Comment by stygiansabyss** [comment]
I am seeing this on all of my apps when I open them.  It pops up a dialog saying "Unable to display dialog box!  Please try update again later".  Then it would give me the box shown in OP.  After closing an app and restarting i just get the unable to display dialog box error.

https://infinit.io/_/3pCvUQ6

After updating to 2.1.5 do I need to tell existing apps to update to it somehow?

**Comment by dmarmor** [comment]
Hi @stygiansabyss. This is a known problem with version 2.1.13, and is addressed in the README file in the DMG for version 2.1.15. Please check that out and run the epichrome_fix.sh script on your existing apps. Then you should be able to update them no problem. Let me know if you still have trouble after that.

**Comment by alatteri** [comment]
I am getting this dialog since updating to 2.15
![screen shot 2016-11-04 at 12 00 41 am](https://cloud.githubusercontent.com/assets/625982/19997173/d939fb04-a221-11e6-85c5-363bb2878602.png)

**Comment by kefyn** [comment]
Sorry to be ignorant, but cannot see the instructions for installing and running the script in the readme. Any chance you can paste them here? Cheers.

**Comment by dmarmor** [comment]
Hey @kefyn, the instructions for installing and running the script are in the README in the DMG for the latest release. Cheers!
