### ISSUE TITLE
All my EpicChrome (2.1.11) apps are dead after rebooting laptop

### ISSUE THREAD

**Issue by williamku** [dmarmor/epichrome#92]
after rebooting my Mac and tried any of the previously saved EpicChrome apps, I see these messages in seccession:

(1)  New version of Google Chrome found (54.0.2840.71). Updating app..

(2) Unable to update app to new version of Google Chrome. (Error filtering InfoPlist.strings (Traceback (most recent call last):
  File "/Users/WilliamKu/Documents/EpicChromeApps/Dev_Test.app/Contents/Resources/Scripts/strings.py", line 52, in <module>
    print sys.exc_info()[1][1]
IndexError: tuple index out of range)) It may or may not run properly.

(3) Unable to install native messaging host. (Unable to copy manifest.) The SSB will still work, but the companion "Epichrome Helper" extension won't.

(4) Unable to create config file.

(5) Then the app will be dead.  Clicking on it again, will show this:
      The application [app name ] can't be opened.

----------
All the EpicChrome apps I made represents a lot of work and pain to create, book-mark and save.   Could anyone tell me what to do to revive them?     
Thanks

**Comment by williamku** [comment]
I read the trick of copying a new version of "strings.sy" to a target folder - but this ONLY works for any existing app that has NOT been clicked yet.   Once clicked and went thru the 5 messages, then seems that it got all wiped out and this trick does not work any more.   Could you confirm it?    Why would the action wipe out the app files?   Could you provide a way to revise those damaged apps?   Deeply appreciate it...

**Comment by dmarmor** [comment]
Unfortunately, no, there's no way to revive those apps. That update bug would destroy the apps. The only small plus side is it should be pretty easy to recreate them. Take a look at [this procedure](https://github.com/dmarmor/epichrome#simple-method) in the Readme. Obviously in your situation only the "simple method" will work. But if you're careful to keep the name identical to the original app, it should find your original settings and you should be able to pick up right where you left off.

Sorry for the trouble, but I think the bug is finally history, so things should be smoother going forward.

Closing this issue now. If anything else comes up, please reference issue #85, where this has been discussed most fully.

**Comment by williamku** [comment]
thanks for the reply - tried the "simple method" but unfortunately the previously saved bookmarks are no longer there.   i guess I will have to rebuild all apps from scratch...

**Comment by dmarmor** [comment]
Hmm. Those bookmarks are almost certainly saved in a profile folder. The other thing you can try is to rebuild the app and determine where it's put your new profile folder. Then, while the app is _not_ running, you can just replace the contents of the new profile folder with the old one (that presumably has your bookmarks saved in it). Maybe give that a try?

**Comment by williamku** [comment]
@dmarmor ,  actually it was my fault the first time using the "simple method" - i missed one important step, I did not remove the existing app first - instead, i created a new one of same name and saved over it in the same location.   I just tried another one by removing it first, now I do see all my bookmarks are there.   Thanks again for the help!

**Comment by dmarmor** [comment]
Ah, that's a relief--good to know you can at least save most of your apps. If you didn't already delete the old profile for the app where you lost the bookmarks, you might be able to retrieve them with the method I mentioned in my last comment. Good luck!
