### ISSUE TITLE
File does not contain an icon. (-50)

### ISSUE THREAD

**Issue by lofftjm** [dmarmor/epichrome#93]
Using OS X 10.10.5

I ran "make" to build "Epichrome.app".  When I try and run "Epichrome.app" I get the error message "File does not contain an icon. (-50)".

**Comment by dmarmor** [comment]
Hmm. Not sure why that would be. Did any of the commands in the make return errors?

**Comment by dmarmor** [comment]
Hey @lofftjm,

Closing this issue for now. If you're still having trouble, let me know and we can reopen it.

Thanks!
