### ISSUE TITLE
wrong launched app

### ISSUE THREAD

**Issue by pvinis** [dmarmor/epichrome#97]
i have the normal slack.app in my applications folder. i created slack.app on my desktop to try epichrome. i clicked "launch" in the end of the setup, and my old slack.app got launched.
i guess the fix is to remember the path i used in the setup and start the app from that directory.

**Comment by dmarmor** [comment]
Thanks @pvinis! You're right, that's just a consequence of the way Epichrome launches the new app. Simple bug, simple fix. I won't push out a whole new version just for that, since I imagine it comes up rarely, but it'll be fixed in the next release. Thank you!
